Script started on Fri Mar 27 20:21:47 2020
cygport --32 --debug automake all
+ [[ -z '' ]]
+ CYG_SYS_BASHRC=1
+ [[ ehimxBH != *i* ]]
+ export 'EXECIGNORE=*.dll'
+ EXECIGNORE='*.dll'
+ PS1='\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[33m\]\w\[\e[0m\]\n\$ '
+ [[ ehimxBH != *i* ]]
]0;/mnt
[32mAdministrator@- [33m/mnt[0m
$ cygport --32 --debug automake all
+ cygport --32 --debug automake all
+ shift
+ true
+ case ${1} in
+ break
+ argv=(${0} ${@})
+ declare -ar argv
+ declare -ir argc=3
+ defined 'argv[1]'
+ ((  1 != 1  ))
+ '[' -n automake ']'
+ return 0
+ defined 'argv[2]'
+ ((  1 != 1  ))
+ '[' -n all ']'
+ return 0
+ source /usr/share/cygport/lib/check_funcs.cygpart
++ readonly -f check_prog check_prog_req check_tool check_target_tool check_pkg_config check_girepository_module check_lua_module check_ocaml_module check_perl_module check_php_module check_python_module check_python2_module check_python3_module check_pypy_module check_R_module check_ruby_module check_tcl_module check_tex_module check_vala_module __check_depends __check_function __check_function_ro __check_unstable __version_at_least
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog bzip2
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash bzip2
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog cat
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cat
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog chmod
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash chmod
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog cp
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cp
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog diff
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash diff
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog diffstat
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash diffstat
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog dos2unix
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash dos2unix
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog file
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash file
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog find
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash find
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog gawk
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash gawk
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog grep
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash grep
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog gzip
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash gzip
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog install
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash install
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog ln
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash ln
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog mkdir
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash mkdir
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog mv
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash mv
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog patch
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash patch
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog rm
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash rm
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog rsync
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash rsync
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog sed
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash sed
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog sort
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash sort
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog tar
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash tar
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog xargs
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash xargs
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog which
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash which
+ return 0
+ for _myprog in bzip2 cat chmod cp diff diffstat dos2unix file find gawk grep gzip install ln mkdir mv patch rm rsync sed sort tar xargs which xz
+ check_prog xz
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash xz
+ return 0
+ unset _myprog
+ check_prog pbzip2
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash pbzip2
+ return 1
+ readonly _tar_bz2_flag=-j
+ _tar_bz2_flag=-j
++ nproc
+ declare 'MAKEOPTS=-j2 '
+ for conf in '${_sysconfdir}/cygport.conf' '"${HOME}/.cygportrc"' '"${HOME}/.cygport.conf"' '"${HOME}/.cygport/cygport.conf"'
+ '[' -e /etc/cygport.conf ']'
+ source /etc/cygport.conf
+ for conf in '${_sysconfdir}/cygport.conf' '"${HOME}/.cygportrc"' '"${HOME}/.cygport.conf"' '"${HOME}/.cygport/cygport.conf"'
+ '[' -e /home/Administrator/.cygportrc ']'
+ for conf in '${_sysconfdir}/cygport.conf' '"${HOME}/.cygportrc"' '"${HOME}/.cygport.conf"' '"${HOME}/.cygport/cygport.conf"'
+ '[' -e /home/Administrator/.cygport.conf ']'
+ for conf in '${_sysconfdir}/cygport.conf' '"${HOME}/.cygportrc"' '"${HOME}/.cygport.conf"' '"${HOME}/.cygport/cygport.conf"'
+ '[' -e /home/Administrator/.cygport/cygport.conf ']'
+ unset conf
+ source /usr/share/cygport/lib/config_registry.cygpart
++ readonly -f __config_equals __config_get __config_set
+ source /usr/share/cygport/lib/inheritance.cygpart
++ readonly -f inherit inherited
+ source /usr/share/cygport/lib/src_fetch.cygpart
++ readonly -f fetch __mirror_fetch __src_fetch
+ source /usr/share/cygport/mirrors
++ mirror_apache+=' http://www.apache.org/dist'
++ mirror_berlios+='
	http://download.berlios.de
	http://download2.berlios.de
'
++ mirror_cpan+=' http://search.cpan.org/CPAN'
++ mirror_cran+=' http://cran.r-project.org'
++ mirror_ctan+=' http://mirror.ctan.org/'
++ mirror_debian+=' http://ftp.debian.org/debian'
++ mirror_gcc+=' ftp://gcc.gnu.org/pub/gcc'
++ mirror_gentoo+=' http://gentoo.osuosl.org/distfiles'
++ mirror_gnome+='
	http://download.gnome.org
	http://ftp.gnome.org/pub/gnome
	ftp://ftp.gnome.org/pub/gnome
'
++ mirror_gnu+='
	http://ftpmirror.gnu.org
	ftp://ftp.gnu.org/gnu
'
++ mirror_gnustep+='
	http://ftp.gnustep.org/pub/gnustep
	ftp://ftp.gnustep.org/pub/gnustep
'
++ mirror_kde+=' http://download.kde.org'
++ mirror_mplayer+=' http://www1.mplayerhq.hu/MPlayer'
++ mirror_mysql+='
	http://mirrors.dotsrc.org/mysql
	ftp://mirrors.dotsrc.org/mysql
	http://ftp.gwdg.de/pub/misc/mysql
	ftp://ftp.gwdg.de/pub/misc/mysql
	http://www.mirrorservice.org/sites/ftp.mysql.com
	ftp://ftp.mirrorservice.org/sites/ftp.mysql.com
	http://mysql.oss.eznetsols.org
	ftp://ftp.oss.eznetsols.org/mysql
'
++ mirror_portage+=' https://gitweb.gentoo.org/repo/gentoo.git/plain'
++ mirror_rubyforge+=' http://files.rubyforge.vm.bytemark.co.uk'
++ mirror_savannah+=' http://download.savannah.nongnu.org/releases'
++ mirror_sourceforge+=' http://downloads.sourceforge.net'
++ mirror_sourceware+=' ftp://ftp.sourceware.org/pub'
++ mirror_qt+=' http://download.qt-project.org'
++ mirror_tlpretest+='
	http://ftp.math.utah.edu/pub/texlive/tlpretest
	ftp://ftp.math.utah.edu/pub/texlive/tlpretest
	http://mirror.hmc.edu/tlpretest
	http://ftp.cstug.cz/pub/tex/local/tlpretest
	ftp://ftp.cstug.cz/pub/tex/local/tlpretest
	http://ftp.ctex.org/mirrors/texlive/tlpretest
	ftp://ftp.ctex.org/mirrors/texlive/tlpretest
	http://ctan.ijs.si/mirror/tlpretest
'
++ mirror_trolltech+='  http://download.qt-project.org'
++ mirror_vim+=' http://ftp.vim.org/pub/vim'
++ mirror_xfce+=' http://archive.xfce.org'
+ source /usr/share/cygport/lib/src_prep.cygpart
++ readonly -f __cpio_gz_extract __gem_extract __srpm_extract unpack __gpg_verify __mkdirs cygpatch __src_prep
+ source /usr/share/cygport/lib/compilers.cygpart
++ declare -x CC=gcc
++ declare -x 'CFLAGS=-ggdb -O2 -pipe -Wimplicit-function-declaration'
++ declare -x CPPFLAGS=
++ declare -x CXX=g++
++ declare -x 'CXXFLAGS=-ggdb -O2 -pipe'
++ declare -x F77=gfortran
++ declare -x 'FFLAGS=-ggdb -O2 -pipe'
++ declare -x FC=gfortran
++ declare -x 'FCFLAGS=-ggdb -O2 -pipe'
++ declare -x GOC=gccgo
++ declare -x 'GOFLAGS=-ggdb -O2 -pipe'
++ declare -x OBJC=gcc
++ declare -x 'OBJCFLAGS=-ggdb -O2 -pipe -Wimplicit-function-declaration'
++ declare -x OBJCXX=g++
++ declare -x 'OBJCXXFLAGS=-ggdb -O2 -pipe'
++ declare -x LDFLAGS=
++ declare -x LIBS=
++ AR=ar
++ DLLTOOL=dlltool
++ NM=nm
++ OBJDUMP=objdump
++ RANLIB=ranlib
++ RC=windres
++ STRIP=strip
++ PKG_CONFIG=pkg-config
++ declare CC_SYSROOT=
+++ /usr/share/cygport/config.guess
++ declare CBUILD=i686-pc-cygwin
++ case ${CBUILD} in
++ CHOST=i686-pc-cygwin
++ unset _host_arch
++ declare CTARGET=i686-pc-cygwin
++ declare CROSS_HOST=
++ declare CROSS_SYSROOT=
++ declare TOOLCHAIN_TARGET=
++ declare ARCH=i686
++ declare ARCH_i686=1
++ '[' i686-pc-cygwin '!=' i686-pc-cygwin ']'
+ source /usr/share/cygport/lib/src_compile.cygpart
++ readonly -f lndirs cygmake
+ source /usr/share/cygport/lib/src_test.cygpart
++ readonly -f cygtest
+ source /usr/share/cygport/lib/src_install.cygpart
++ readonly -f __doinstall __fix_shebang dodir keepdir dobin newbin docinto dodoc newdoc exeinto doexe newexe insinto doins newins doicon newicon dolib doman newman domenu newmenu dosbin newsbin dosym make_autostart_entry make_desktop_entry make_etc_defaults update_etc_shells __prepinstalldirs cyginstall
+ source /usr/share/cygport/lib/src_postinst.cygpart
++ readonly -f __prep_fonts_dir __prep_freedesktop_mime __prep_gconf_schemas __prep_gdk_pixbuf_modules __prep_gtk2_modules __prep_gtk3_modules __prep_gtk_icon_theme __prep_python_bytecompile __prep_texlive __prep_xsessions __prepdoc __prepemacs __prepetc __prepman __prepinfo __prepperl __prepvargames __prep_empty_dirs __prepstrip __prepdebugsrc __prep_symlinks __prep_libtool_modules __src_postinst
+ source /usr/share/cygport/lib/pkg_info.cygpart
++ readonly -f __list_files __list_debug_files __list_deps __show_deps __show_info __show_web __pager
+ source /usr/share/cygport/lib/pkg_pkg.cygpart
++ readonly -f __pkg_binpkg __pkg_diff __gpg_sign __pkg_srcpkg __pkg_dist
+ source /usr/share/cygport/lib/pkg_upload.cygpart
++ readonly -f __pkg_upload __pkg_announce
+ source /usr/share/cygport/lib/pkg_cleanup.cygpart
++ readonly -f __finish
+ _autotools_CYGCLASS_stage1_=1
+ inherit autotools
+ local class
+ local classname
+ for class in '"$@"'
+ classname=autotools
+ '[' '!' -f /usr/share/cygport/cygclass/autotools.cygclass ']'
+ defined _autotools_CYGCLASS_
+ ((  1 != 1  ))
+ '[' -n '' ']'
+ return 1
+ export _autotools_CYGCLASS_=1
+ _autotools_CYGCLASS_=1
+ source /usr/share/cygport/cygclass/autotools.cygclass
++ defined _autotools_CYGCLASS_stage1_
++ ((  1 != 1  ))
++ '[' -n 1 ']'
++ return 0
+ unset _autotools_CYGCLASS_ _autotools_CYGCLASS_stage1_
+ unset NAME VERSION RELEASE
+ '[' -f automake ']'
+ '[' '' = yyy ']'
+ PF=automake
+ declare -r PF=automake
+ declare -r PN=automake
+ declare NAME=automake
+ declare -r PR=automake
+ declare RELEASE=automake
++ echo automake
++ sed -e 's/automake\-\(.*\)\-automake$/\1/'
+ PV=automake
+ declare VERSION=automake
+ declare -r cygportfile=automake.cygport
+ declare -r P=automake-automake
+ declare -r PVR=automake-automake
+ PVP=(${PV//[-\._]/ })
+ declare -ar PVP
+ PV=(${PV} ${PVP[*]})
+ declare -r PV
+ declare -r PV_MAJ=automake
+ declare -r PV_MAJ_MIN=automake.
+ declare -rx CYGPORT_PACKAGE_NAME=automake
+ declare -rx CYGPORT_PACKAGE_VERSION=automake
+ declare -rx CYGPORT_PACKAGE_RELEASE=automake
+ _topdir=automake
+ '[' xautomake = xautomake ']'
+ '[' -f ./automake.cygport ']'
+ _topdir=.
++ cd .
++ pwd
+ declare -r top=/mnt
+ unset _topdir
+ '[' '!' -e /mnt/automake.cygport ']'
+ source /mnt/automake.cygport
++ NAME=automake
++ VERSION=1.16.1
++ RELEASE=1
++ CATEGORY=devel
++ SUMMARY='Tool for generating GNU Standards-compliant Makefiles'
++ DESCRIPTION=
++ HOMEPAGE=http://sourceware.org/cygwinports/
++ SRC_URI='http://ftp.debian.org/debian/pool/main/a/automake-1.16/automake-1.16_1.16.1-4.dsc http://ftp.debian.org/debian/pool/main/a/automake-1.16/automake-1.16_1.16.1.orig.tar.xz http://ftp.debian.org/debian/pool/main/a/automake-1.16/automake-1.16_1.16.1-4.debian.tar.xz'
++ SRC_DIR=.
++ PATCH_URI=./automake.patch
++ DEBEMAIL=user@example.com
++ DEBFULLNAME='Firstname Lastname'
++ ARCH=noarch
++ DEPEND='autoconf autopoint bison cscope dejagnu default-jdk emacs expect flex gettext gfortran gobjc gobjc++ help2man install-info libglib2.0-dev libtool libtool-bin lzip ncompress pkg-config python python-docutils python-virtualenv sharutils texinfo texlive unzip valac xutils-dev zip'
++ REQUIRES='autoconf autotools-dev'
++ CYGPORT_USE_UNSTABLE_API=1
+ case ${ARCH} in
+ defined CYGPORT_DEPEND
+ ((  1 != 1  ))
+ '[' -n '' ']'
+ return 1
+ unset restrict
+ declare -r workdir=/mnt/automake.noarch
+ declare -r srcdir=/mnt/automake.noarch/src
+ declare -r origsrcdir=/mnt/automake.noarch/origsrc
+ declare -r configdir=/mnt/automake.noarch/config
+ declare -r logdir=/mnt/automake.noarch/log
+ declare -r patchdir=/mnt/automake.noarch/patch
+ declare -r spkgdir=/mnt/automake.noarch/spkg/automake.src
+ declare -r distdir=/mnt/automake.noarch/dist
+ SRC_DIR=.
+ '[' x. = x. ']'
+ declare -r S=/mnt/automake.noarch/src
+ declare -r B=/mnt/automake.noarch/build
+ declare -r D=/mnt/automake.noarch/inst
+ declare -r T=/mnt/automake.noarch/temp
+ declare -r C=/mnt/automake.noarch/src/CYGWIN-PATCHES
+ declare -rx CYGPORT_ARCH=noarch
+ declare -rx CYGPORT_OS=Cygwin
+ declare -rx CYGPORT_BUILD_ROOT=/mnt/automake.noarch/inst
+ declare -rx 'CYGPORT_OPT_FLAGS=-ggdb -O2 -pipe -Wimplicit-function-declaration'
+ declare -r compilelog=/mnt/automake.noarch/log/automake-compile.log
+ declare -r checklog=/mnt/automake.noarch/log/automake-check.log
+ declare -r installlog=/mnt/automake.noarch/log/automake-install.log
+ declare -r pkglog=/mnt/automake.noarch/log/automake-pkg.log
+ declare -r uploadlog=/mnt/automake.noarch/log/automake-upload.log
+ defined SRC_URI
+ ((  1 != 1  ))
+ '[' -n 'http://ftp.debian.org/debian/pool/main/a/automake-1.16/automake-1.16_1.16.1-4.dsc http://ftp.debian.org/debian/pool/main/a/automake-1.16/automake-1.16_1.16.1.orig.tar.xz http://ftp.debian.org/debian/pool/main/a/automake-1.16/automake-1.16_1.16.1-4.debian.tar.xz' ']'
+ return 0
+ for _src_uri in '${SRC_URI}'
+ '[' -f /mnt/http://ftp.debian.org/debian/pool/main/a/automake-1.16/automake-1.16_1.16.1-4.dsc ']'
+ _src_uri=http://ftp.debian.org/debian/pool/main/a/automake-1.16/automake-1.16_1.16.1-4.dsc
+ _src_uri=http://ftp.debian.org/debian/pool/main/a/automake-1.16/automake-1.16_1.16.1-4.dsc
+ _src_orig_pkgs+=' automake-1.16_1.16.1-4.dsc'
+ for _src_uri in '${SRC_URI}'
+ '[' -f /mnt/http://ftp.debian.org/debian/pool/main/a/automake-1.16/automake-1.16_1.16.1.orig.tar.xz ']'
+ _src_uri=http://ftp.debian.org/debian/pool/main/a/automake-1.16/automake-1.16_1.16.1.orig.tar.xz
+ _src_uri=http://ftp.debian.org/debian/pool/main/a/automake-1.16/automake-1.16_1.16.1.orig.tar.xz
+ _src_orig_pkgs+=' automake-1.16_1.16.1.orig.tar.xz'
+ for _src_uri in '${SRC_URI}'
+ '[' -f /mnt/http://ftp.debian.org/debian/pool/main/a/automake-1.16/automake-1.16_1.16.1-4.debian.tar.xz ']'
+ _src_uri=http://ftp.debian.org/debian/pool/main/a/automake-1.16/automake-1.16_1.16.1-4.debian.tar.xz
+ _src_uri=http://ftp.debian.org/debian/pool/main/a/automake-1.16/automake-1.16_1.16.1-4.debian.tar.xz
+ _src_orig_pkgs+=' automake-1.16_1.16.1-4.debian.tar.xz'
+ readonly _src_orig_pkgs
+ unset _src_uri
+ for _patch_uri in '${PATCH_URI}'
+ '[' -f /mnt/./automake.patch ']'
+ _src_orig_patches+=' ./automake.patch'
+ continue
+ readonly _src_orig_patches
+ unset _patch_uri
+ declare -r cygwin_patchfile=automake.cygwin.patch
+ declare -r src_patchfile=automake.src.patch
+ pkg_name=(${PKG_NAMES:-${PN}})
+ declare -ar pkg_name
+ declare -r pkg_count=1
+ defined _CYGPORT_RESTRICT_debuginfo_
+ ((  1 != 1  ))
+ '[' -n '' ']'
+ return 1
+ for flags in '{C,CXX,F,FC,GO,OBJC,OBJCXX}FLAGS'
+ declare 'CFLAGS+= -fdebug-prefix-map=/mnt/automake.noarch/build=/usr/src/debug/automake'
+ declare 'CFLAGS+= -fdebug-prefix-map=/mnt/automake.noarch/src=/usr/src/debug/automake'
+ for flags in '{C,CXX,F,FC,GO,OBJC,OBJCXX}FLAGS'
+ declare 'CXXFLAGS+= -fdebug-prefix-map=/mnt/automake.noarch/build=/usr/src/debug/automake'
+ declare 'CXXFLAGS+= -fdebug-prefix-map=/mnt/automake.noarch/src=/usr/src/debug/automake'
+ for flags in '{C,CXX,F,FC,GO,OBJC,OBJCXX}FLAGS'
+ declare 'FFLAGS+= -fdebug-prefix-map=/mnt/automake.noarch/build=/usr/src/debug/automake'
+ declare 'FFLAGS+= -fdebug-prefix-map=/mnt/automake.noarch/src=/usr/src/debug/automake'
+ for flags in '{C,CXX,F,FC,GO,OBJC,OBJCXX}FLAGS'
+ declare 'FCFLAGS+= -fdebug-prefix-map=/mnt/automake.noarch/build=/usr/src/debug/automake'
+ declare 'FCFLAGS+= -fdebug-prefix-map=/mnt/automake.noarch/src=/usr/src/debug/automake'
+ for flags in '{C,CXX,F,FC,GO,OBJC,OBJCXX}FLAGS'
+ declare 'GOFLAGS+= -fdebug-prefix-map=/mnt/automake.noarch/build=/usr/src/debug/automake'
+ declare 'GOFLAGS+= -fdebug-prefix-map=/mnt/automake.noarch/src=/usr/src/debug/automake'
+ for flags in '{C,CXX,F,FC,GO,OBJC,OBJCXX}FLAGS'
+ declare 'OBJCFLAGS+= -fdebug-prefix-map=/mnt/automake.noarch/build=/usr/src/debug/automake'
+ declare 'OBJCFLAGS+= -fdebug-prefix-map=/mnt/automake.noarch/src=/usr/src/debug/automake'
+ for flags in '{C,CXX,F,FC,GO,OBJC,OBJCXX}FLAGS'
+ declare 'OBJCXXFLAGS+= -fdebug-prefix-map=/mnt/automake.noarch/build=/usr/src/debug/automake'
+ declare 'OBJCXXFLAGS+= -fdebug-prefix-map=/mnt/automake.noarch/src=/usr/src/debug/automake'
+ unset flags map
+ declare -i arg_n=2
+ declare _pkg_tag=
+ ((  arg_n < argc  ))
+ case ${argv[${arg_n}]} in
+ __stage Preparing
+ echo -e '\e[1;39m>>> Preparing automake.noarch\e[0;0m'
[1;39m>>> Preparing automake.noarch[0;0m
+ __src_prep
+ local sigext
+ local 'sig_exts=asc sig sign'
+ local src_orig_patch
+ local src_patch
+ local src_pkg
+ local tar_patch
+ local n=1
+ cd /mnt
+ __mkdirs
+ cd /mnt
+ mkdir -p /mnt/automake.noarch/src /mnt/automake.noarch/origsrc /mnt/automake.noarch/build /mnt/automake.noarch/inst /mnt/automake.noarch/temp /mnt/automake.noarch/config /mnt/automake.noarch/log /mnt/automake.noarch/dist /mnt/automake.noarch/patch /mnt/automake.noarch/spkg/automake.src
+ __config_set cygport_version 0.25.0-1-g80ed18a-dirty
+ echo -n 0.25.0-1-g80ed18a-dirty
+ '[' -f /mnt/automake.cygport.sig ']'
+ for src_pkg in '${_src_orig_pkgs}'
+ '[' -f /automake-1.16_1.16.1-4.dsc -a '!' -f /mnt/automake-1.16_1.16.1-4.dsc ']'
+ '[' -f /mnt/automake-1.16_1.16.1-4.dsc -a '!' -f /mnt/automake-1.16_1.16.1-4.dsc ']'
+ for sigext in '${sig_exts}'
+ '[' -f automake-1.16_1.16.1-4.dsc.asc ']'
+ for sigext in '${sig_exts}'
+ '[' -f automake-1.16_1.16.1-4.dsc.sig ']'
+ for sigext in '${sig_exts}'
+ '[' -f automake-1.16_1.16.1-4.dsc.sign ']'
+ for src_pkg in '${_src_orig_pkgs}'
+ '[' -f /automake-1.16_1.16.1.orig.tar.xz -a '!' -f /mnt/automake-1.16_1.16.1.orig.tar.xz ']'
+ '[' -f /mnt/automake-1.16_1.16.1.orig.tar.xz -a '!' -f /mnt/automake-1.16_1.16.1.orig.tar.xz ']'
+ for sigext in '${sig_exts}'
+ '[' -f automake-1.16_1.16.1.orig.tar.xz.asc ']'
+ for sigext in '${sig_exts}'
+ '[' -f automake-1.16_1.16.1.orig.tar.xz.sig ']'
+ for sigext in '${sig_exts}'
+ '[' -f automake-1.16_1.16.1.orig.tar.xz.sign ']'
+ for src_pkg in '${_src_orig_pkgs}'
+ '[' -f /automake-1.16_1.16.1-4.debian.tar.xz -a '!' -f /mnt/automake-1.16_1.16.1-4.debian.tar.xz ']'
+ '[' -f /mnt/automake-1.16_1.16.1-4.debian.tar.xz -a '!' -f /mnt/automake-1.16_1.16.1-4.debian.tar.xz ']'
+ for sigext in '${sig_exts}'
+ '[' -f automake-1.16_1.16.1-4.debian.tar.xz.asc ']'
+ for sigext in '${sig_exts}'
+ '[' -f automake-1.16_1.16.1-4.debian.tar.xz.sig ']'
+ for sigext in '${sig_exts}'
+ '[' -f automake-1.16_1.16.1-4.debian.tar.xz.sign ']'
+ for src_patch in '${_src_orig_patches}'
+ '[' -f /./automake.patch -a '!' -f /mnt/./automake.patch ']'
+ '[' -f /mnt/automake.patch -a '!' -f ./automake.patch ']'
+ for sigext in '${sig_exts}'
+ '[' -f ./automake.patch.asc ']'
+ for sigext in '${sig_exts}'
+ '[' -f ./automake.patch.sig ']'
+ for sigext in '${sig_exts}'
+ '[' -f ./automake.patch.sign ']'
+ '[' -f /mnt/automake.cygwin.patch.sig ']'
+ '[' -f /mnt/automake.src.patch.sig ']'
+ cd /mnt/automake.noarch/origsrc
+ for src_pkg in '${_src_orig_pkgs}'
+ '[' -f /automake-1.16_1.16.1-4.dsc -a '!' -f /mnt/automake-1.16_1.16.1-4.dsc ']'
+ '[' -f /mnt/automake-1.16_1.16.1-4.dsc -a '!' -f /mnt/automake-1.16_1.16.1-4.dsc ']'
+ src_pkg=/mnt/automake-1.16_1.16.1-4.dsc
+ unpack /mnt/automake-1.16_1.16.1-4.dsc
+ local unpack_cmd
+ local unpack_file_path
+ local unpack_file_name
+ local unpack_out
+ for unpack_file_path in '"$@"'
+ unpack_file_name=automake-1.16_1.16.1-4.dsc
+ '[' '!' -f /mnt/automake-1.16_1.16.1-4.dsc ']'
+ case ${unpack_file_path} in
+ unpack_cmd='cp -t .'
+ __step 'Unpacking source automake-1.16_1.16.1-4.dsc'
+ echo -e '>>> Unpacking source automake-1.16_1.16.1-4.dsc'
>>> Unpacking source automake-1.16_1.16.1-4.dsc
+ defined unpack_out
+ ((  1 != 1  ))
+ '[' -n '' ']'
+ return 1
+ cp -t . /mnt/automake-1.16_1.16.1-4.dsc
+ for src_pkg in '${_src_orig_pkgs}'
+ '[' -f /automake-1.16_1.16.1.orig.tar.xz -a '!' -f /mnt/automake-1.16_1.16.1.orig.tar.xz ']'
+ '[' -f /mnt/automake-1.16_1.16.1.orig.tar.xz -a '!' -f /mnt/automake-1.16_1.16.1.orig.tar.xz ']'
+ src_pkg=/mnt/automake-1.16_1.16.1.orig.tar.xz
+ unpack /mnt/automake-1.16_1.16.1.orig.tar.xz
+ local unpack_cmd
+ local unpack_file_path
+ local unpack_file_name
+ local unpack_out
+ for unpack_file_path in '"$@"'
+ unpack_file_name=automake-1.16_1.16.1.orig.tar.xz
+ '[' '!' -f /mnt/automake-1.16_1.16.1.orig.tar.xz ']'
+ case ${unpack_file_path} in
+ unpack_cmd='tar xf'
+ __step 'Unpacking source automake-1.16_1.16.1.orig.tar.xz'
+ echo -e '>>> Unpacking source automake-1.16_1.16.1.orig.tar.xz'
>>> Unpacking source automake-1.16_1.16.1.orig.tar.xz
+ defined unpack_out
+ ((  1 != 1  ))
+ '[' -n '' ']'
+ return 1
+ tar xf /mnt/automake-1.16_1.16.1.orig.tar.xz
+ for src_pkg in '${_src_orig_pkgs}'
+ '[' -f /automake-1.16_1.16.1-4.debian.tar.xz -a '!' -f /mnt/automake-1.16_1.16.1-4.debian.tar.xz ']'
+ '[' -f /mnt/automake-1.16_1.16.1-4.debian.tar.xz -a '!' -f /mnt/automake-1.16_1.16.1-4.debian.tar.xz ']'
+ src_pkg=/mnt/automake-1.16_1.16.1-4.debian.tar.xz
+ unpack /mnt/automake-1.16_1.16.1-4.debian.tar.xz
+ local unpack_cmd
+ local unpack_file_path
+ local unpack_file_name
+ local unpack_out
+ for unpack_file_path in '"$@"'
+ unpack_file_name=automake-1.16_1.16.1-4.debian.tar.xz
+ '[' '!' -f /mnt/automake-1.16_1.16.1-4.debian.tar.xz ']'
+ case ${unpack_file_path} in
+ unpack_cmd='tar xf'
+ __step 'Unpacking source automake-1.16_1.16.1-4.debian.tar.xz'
+ echo -e '>>> Unpacking source automake-1.16_1.16.1-4.debian.tar.xz'
>>> Unpacking source automake-1.16_1.16.1-4.debian.tar.xz
+ defined unpack_out
+ ((  1 != 1  ))
+ '[' -n '' ']'
+ return 1
+ tar xf /mnt/automake-1.16_1.16.1-4.debian.tar.xz
+ '[' '!' -d /mnt/automake.noarch/origsrc/. ']'
+ chmod +x /mnt/automake.noarch/origsrc/.
+ cd /mnt/automake.noarch/origsrc/.
+ defined DISTCLEANFILES
+ ((  1 != 1  ))
+ '[' -n '' ']'
+ return 1
+ __check_function src_unpack_hook
+ ((  1 < 1  ))
+ declare -F src_unpack_hook
+ return 0
+ __check_unstable src_unpack_hook
+ local unstable_var=CYGPORT_USE_UNSTABLE_API
+ defined CYGPORT_USE_UNSTABLE_API
+ ((  1 != 1  ))
+ '[' -n 1 ']'
+ return 0
+ src_unpack_hook
+ mv debian automake-1.16.1
+ return 0
+ cd /mnt/automake.noarch/origsrc/.
+ for src_patch in '${_src_orig_patches}'
+ '[' -f /./automake.patch -a '!' -f /mnt/./automake.patch ']'
+ '[' -f /mnt/automake.patch -a '!' -f /mnt/./automake.patch ']'
+ src_patch=/mnt/./automake.patch
+ case ${src_patch} in
+ cygpatch /mnt/./automake.patch
+ local patchfile_name
+ local patchfile_path
+ local -i patchlevel
+ local -i max_patchlevel=5
+ local srcdir_depth
+ for patchfile_path in '"$@"'
+ patchfile_name=automake.patch
+ '[' '!' -e /mnt/./automake.patch ']'
+ patchlevel=0
+ case ${patchfile_name} in
+ ((  patchlevel <= max_patchlevel  ))
+ patch -N -s --dry-run -p0 -i /mnt/./automake.patch
+ inform 'applying patch automake.patch (-p0):'
+ echo -e '\e[1;32m*** Info:\e[0;0m applying patch automake.patch (-p0):'
[1;32m*** Info:[0;0m applying patch automake.patch (-p0):
+ patch -N -p0 --no-backup-if-mismatch -i /mnt/./automake.patch
patching file automake-1.16.1/debian/rules
+ break
+ __check_function src_patch_hook
+ ((  1 < 1  ))
+ declare -F src_patch_hook
+ return 0
+ __check_unstable src_patch_hook
+ local unstable_var=CYGPORT_USE_UNSTABLE_API
+ defined CYGPORT_USE_UNSTABLE_API
+ ((  1 != 1  ))
+ '[' -n 1 ']'
+ return 0
+ src_patch_hook
+ :
+ return 0
+ cd /mnt/automake.noarch/origsrc/.
+ __step 'Preparing working source directory'
+ echo -e '>>> Preparing working source directory'
>>> Preparing working source directory
+ rsync -aq --delete-before /mnt/automake.noarch/origsrc/ /mnt/automake.noarch/src/
+ mkdir -p /mnt/automake.noarch/src/CYGWIN-PATCHES
+ ln -sfn /mnt/automake.noarch/src/CYGWIN-PATCHES /mnt/automake.noarch/CYGWIN-PATCHES
+ cd /mnt/automake.noarch/src
+ '[' -f /mnt/automake.cygwin.patch ']'
+ '[' -f /mnt/automake.src.patch ']'
+ __log_init /mnt/automake.noarch/log/automake-compile.log
+ local log=/mnt/automake.noarch/log/automake-compile.log
+ rm -f /mnt/automake.noarch/log/automake-compile.log
+ echo -e cygport 0.25.0-1-g80ed18a-dirty '\n'
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo PF = automake
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo S = /mnt/automake.noarch/src
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo B = /mnt/automake.noarch/build
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo D = /mnt/automake.noarch/inst
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo C = /mnt/automake.noarch/src/CYGWIN-PATCHES
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo T = /mnt/automake.noarch/temp
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo CBUILD = i686-pc-cygwin
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo CHOST = i686-pc-cygwin
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo CTARGET = i686-pc-cygwin
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo CC = gcc
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo CFLAGS = -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/automake.noarch/build=/usr/src/debug/automake -fdebug-prefix-map=/mnt/automake.noarch/src=/usr/src/debug/automake
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo CPPFLAGS =
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo CXX = g++
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo CXXFLAGS = -ggdb -O2 -pipe -fdebug-prefix-map=/mnt/automake.noarch/build=/usr/src/debug/automake -fdebug-prefix-map=/mnt/automake.noarch/src=/usr/src/debug/automake
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo F77 = gfortran
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo FFLAGS = -ggdb -O2 -pipe -fdebug-prefix-map=/mnt/automake.noarch/build=/usr/src/debug/automake -fdebug-prefix-map=/mnt/automake.noarch/src=/usr/src/debug/automake
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo FC = gfortran
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo FCFLAGS = -ggdb -O2 -pipe -fdebug-prefix-map=/mnt/automake.noarch/build=/usr/src/debug/automake -fdebug-prefix-map=/mnt/automake.noarch/src=/usr/src/debug/automake
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo GOC = gccgo
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo GOFLAGS = -ggdb -O2 -pipe -fdebug-prefix-map=/mnt/automake.noarch/build=/usr/src/debug/automake -fdebug-prefix-map=/mnt/automake.noarch/src=/usr/src/debug/automake
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo OBJC = gcc
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo OBJCFLAGS = -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/automake.noarch/build=/usr/src/debug/automake -fdebug-prefix-map=/mnt/automake.noarch/src=/usr/src/debug/automake
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo OBJCXX = g++
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo OBJCXXFLAGS = -ggdb -O2 -pipe -fdebug-prefix-map=/mnt/automake.noarch/build=/usr/src/debug/automake -fdebug-prefix-map=/mnt/automake.noarch/src=/usr/src/debug/automake
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo LDFLAGS =
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo LIBS =
+ for var in PF S B D C T CBUILD CHOST CTARGET CC CFLAGS CPPFLAGS CXX CXXFLAGS F77 FFLAGS FC FCFLAGS GOC GOFLAGS OBJC OBJCFLAGS OBJCXX OBJCXXFLAGS LDFLAGS LIBS MAKEOPTS
+ echo MAKEOPTS = -j2
+ echo -e '\n'
+ __check_depends
+ local atom failed_atoms
+ check_tool gcc
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash i686-pc-cygwin-gcc
+ return 0
+ check_tool strip
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash i686-pc-cygwin-strip
+ '[' i686-pc-cygwin = i686-pc-cygwin ']'
+ hash strip
+ :
+ return 0
+ defined DEPEND
+ ((  1 != 1  ))
+ '[' -n 'autoconf autopoint bison cscope dejagnu default-jdk emacs expect flex gettext gfortran gobjc gobjc++ help2man install-info libglib2.0-dev libtool libtool-bin lzip ncompress pkg-config python python-docutils python-virtualenv sharutils texinfo texlive unzip valac xutils-dev zip' ']'
+ return 0
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd autoconf
+ dos2unix
+ grep -q '^autoconf '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd autopoint
+ dos2unix
+ grep -q '^autopoint '
+ failed_atoms+='autopoint '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd bison
+ dos2unix
+ grep -q '^bison '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd cscope
+ dos2unix
+ grep -q '^cscope '
+ failed_atoms+='cscope '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd dejagnu
+ dos2unix
+ grep -q '^dejagnu '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd default-jdk
+ dos2unix
+ grep -q '^default-jdk '
+ failed_atoms+='default-jdk '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd emacs
+ dos2unix
+ grep -q '^emacs '
+ failed_atoms+='emacs '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd expect
+ dos2unix
+ grep -q '^expect '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd flex
+ dos2unix
+ grep -q '^flex '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd gettext
+ dos2unix
+ grep -q '^gettext '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd gfortran
+ dos2unix
+ grep -q '^gfortran '
+ failed_atoms+='gfortran '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd gobjc
+ dos2unix
+ grep -q '^gobjc '
+ failed_atoms+='gobjc '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd gobjc++
+ dos2unix
+ grep -q '^gobjc++ '
+ failed_atoms+='gobjc++ '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd help2man
+ dos2unix
+ grep -q '^help2man '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd install-info
+ dos2unix
+ grep -q '^install-info '
+ failed_atoms+='install-info '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd libglib2.0-dev
+ dos2unix
+ grep -q '^libglib2.0-dev '
+ failed_atoms+='libglib2.0-dev '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd libtool
+ dos2unix
+ grep -q '^libtool '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd libtool-bin
+ dos2unix
+ grep -q '^libtool-bin '
+ failed_atoms+='libtool-bin '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd lzip
+ dos2unix
+ grep -q '^lzip '
+ failed_atoms+='lzip '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd ncompress
+ dos2unix
+ grep -q '^ncompress '
+ failed_atoms+='ncompress '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd pkg-config
+ dos2unix
+ grep -q '^pkg-config '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd python
+ dos2unix
+ grep -q '^python '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd python-docutils
+ dos2unix
+ grep -q '^python-docutils '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd python-virtualenv
+ dos2unix
+ grep -q '^python-virtualenv '
+ failed_atoms+='python-virtualenv '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd sharutils
+ dos2unix
+ grep -q '^sharutils '
+ failed_atoms+='sharutils '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd texinfo
+ dos2unix
+ grep -q '^texinfo '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd texlive
+ dos2unix
+ grep -q '^texlive '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd unzip
+ dos2unix
+ grep -q '^unzip '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd valac
+ dos2unix
+ grep -q '^valac '
+ failed_atoms+='valac '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd xutils-dev
+ dos2unix
+ grep -q '^xutils-dev '
+ failed_atoms+='xutils-dev '
+ for atom in '${DEPEND}'
+ case ${atom} in
+ check_prog cygcheck
+ local _prog
+ ((  1 < 1  ))
+ for _prog in '"$@"'
+ hash cygcheck
+ return 0
+ cygcheck -cd zip
+ dos2unix
+ grep -q '^zip '
+ unset -f __deparenthesize
+ defined failed_atoms
+ ((  1 != 1  ))
+ '[' -n 'autopoint cscope default-jdk emacs gfortran gobjc gobjc++ install-info libglib2.0-dev libtool-bin lzip ncompress python-virtualenv sharutils valac xutils-dev ' ']'
+ return 0
+ warning 'Some build dependencies are not installed.'
+ echo -e '\e[1;33m*** Warning:\e[0;0m Some build dependencies are not installed.'
[1;33m*** Warning:[0;0m Some build dependencies are not installed.
+ warning 'This package may end up missing features, or not build at all.'
+ echo -e '\e[1;33m*** Warning:\e[0;0m This package may end up missing features, or not build at all.'
[1;33m*** Warning:[0;0m This package may end up missing features, or not build at all.
+ warning 'Consider installing these packages first before continuing:'
+ echo -e '\e[1;33m*** Warning:\e[0;0m Consider installing these packages first before continuing:'
[1;33m*** Warning:[0;0m Consider installing these packages first before continuing:
+ warning '    autopoint cscope default-jdk emacs gfortran gobjc gobjc++ install-info libglib2.0-dev libtool-bin lzip ncompress python-virtualenv sharutils valac xutils-dev '
+ echo -e '\e[1;33m*** Warning:\e[0;0m     autopoint cscope default-jdk emacs gfortran gobjc gobjc++ install-info libglib2.0-dev libtool-bin lzip ncompress python-virtualenv sharutils valac xutils-dev '
[1;33m*** Warning:[0;0m     autopoint cscope default-jdk emacs gfortran gobjc gobjc++ install-info libglib2.0-dev libtool-bin lzip ncompress python-virtualenv sharutils valac xutils-dev 
+ __stage Compiling
+ echo -e '\e[1;39m>>> Compiling automake.noarch\e[0;0m'
[1;39m>>> Compiling automake.noarch[0;0m
+ src_compile
+ tee -a /mnt/automake.noarch/log/automake-compile.log
+ rsync --archive /mnt/automake.noarch/src/. /mnt/automake.noarch/build/.
+ make -C /mnt/automake.noarch/build/automake-1.16.1 -f debian/rules binary
make: Entering directory '/mnt/automake.noarch/build/automake-1.16.1'
dh /usr/share/dpkg/default.mk --without autoreconf --no-parallel
dh: unable to set SOURCE_DATE_EPOCH: Can't locate Dpkg/Changelog/Debian.pm in @INC (you may need to install the Dpkg::Changelog::Debian module) (@INC contains: /usr/lib/perl5/site_perl/5.22/i686-cygwin-threads-64int /usr/lib/perl5/site_perl/5.22 /usr/lib/perl5/vendor_perl/5.22/i686-cygwin-threads-64int /usr/lib/perl5/vendor_perl/5.22 /usr/lib/perl5/5.22/i686-cygwin-threads-64int /usr/lib/perl5/5.22 .) at /usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Dh_Lib.pm line 2240.

dh: unable to load build flags: Can't locate Dpkg/BuildFlags.pm in @INC (you may need to install the Dpkg::BuildFlags module) (@INC contains: /usr/lib/perl5/site_perl/5.22/i686-cygwin-threads-64int /usr/lib/perl5/site_perl/5.22 /usr/lib/perl5/vendor_perl/5.22/i686-cygwin-threads-64int /usr/lib/perl5/vendor_perl/5.22 /usr/lib/perl5/5.22/i686-cygwin-threads-64int /usr/lib/perl5/5.22 .) at /usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Dh_Lib.pm line 2277.

dh: Unknown sequence /usr/share/dpkg/default.mk (choose from: binary binary-arch binary-indep build build-arch build-indep clean install install-arch install-indep)
debian/rules:3: /usr/share/dpkg/default.mk: No such file or directory
make: *** [debian/rules:11: /usr/share/dpkg/default.mk] Error 255
make: Leaving directory '/mnt/automake.noarch/build/automake-1.16.1'
+ test 2 -eq 0
+ _status=1
+ ((  _status != 0  ))
+ break
+ exit 1

Script done on Fri Mar 27 20:29:22 2020
