Script started on Thu Apr 16 20:14:18 2020
makefile:138: update target 'bash_5.0-4.dsc' due to: bash_5.0-4.cygport
cygport --32 bash_5.0-4.cygport download && touch -r bash_5.0-4.dsc bash_5.0-4.cygport
--2020-04-16 20:14:19--  http://ftp.debian.org/debian/pool/main/b/bash/bash_5.0-4.dsc
Resolving ftp.debian.org (ftp.debian.org)... 130.89.148.12
Connecting to ftp.debian.org (ftp.debian.org)|130.89.148.12|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2305 (2.3K)
Saving to: 'bash_5.0-4.dsc.tmp'

bash_5.0-4.dsc.tmp    0%[                    ]       0  --.-KB/s               bash_5.0-4.dsc.tmp  100%[===================>]   2.25K  --.-KB/s    in 0s      

2020-04-16 20:14:19 (29.5 MB/s) - 'bash_5.0-4.dsc.tmp' saved [2305/2305]

makefile:147: update target 'bash_5.0-4.i686' due to: bash_5.0-4.dsc
cygport --32 bash_5.0-4.cygport all
[1;39m>>> Preparing bash-5.0-4-1.i686[0;0m
>>> Unpacking source bash_5.0-4.dsc
>>> Unpacking source bash_5.0.orig.tar.xz
>>> Unpacking source bash_5.0-4.debian.tar.xz
gpgv: keyblock resource `/home/Administrator/.gnupg/trustedkeys.gpg': file open error
gpgv: Signature made Thu Apr 18 06:17:53 2019 CEST using RSA key ID 778FA6F5
gpgv: Can't check signature: public key not found
[1mdpkg-source: [0m[1;33mwarning[0m: failed to verify signature on /mnt/bash_5.0-4.dsc
[1mdpkg-source: [0m[32minfo[0m: extracting bash in bash
[1mdpkg-source: [0m[32minfo[0m: unpacking bash_5.0.orig.tar.xz
[1mdpkg-source: [0m[32minfo[0m: unpacking bash_5.0-4.debian.tar.xz
[1mdpkg-source: [0m[32minfo[0m: using patch list from debian/patches/series
[1mdpkg-source: [0m[32minfo[0m: applying bash50-001.diff
[1mdpkg-source: [0m[32minfo[0m: applying bash50-002.diff
[1mdpkg-source: [0m[32minfo[0m: applying bash50-003.diff
[1mdpkg-source: [0m[32minfo[0m: applying bashbug-editor.diff
[1mdpkg-source: [0m[32minfo[0m: applying deb-bash-config.diff
[1mdpkg-source: [0m[32minfo[0m: applying deb-examples.diff
[1mdpkg-source: [0m[32minfo[0m: applying man-arithmetic.diff
[1mdpkg-source: [0m[32minfo[0m: applying man-fignore.diff
[1mdpkg-source: [0m[32minfo[0m: applying man-bashrc.diff
[1mdpkg-source: [0m[32minfo[0m: applying man-bashlogout.diff
[1mdpkg-source: [0m[32minfo[0m: applying man-nocaseglob.diff
[1mdpkg-source: [0m[32minfo[0m: applying man-test.diff
[1mdpkg-source: [0m[32minfo[0m: applying man-test2.diff
[1mdpkg-source: [0m[32minfo[0m: applying rbash-manpage.diff
[1mdpkg-source: [0m[32minfo[0m: applying bash-default-editor.diff
[1mdpkg-source: [0m[32minfo[0m: applying input-err.diff
[1mdpkg-source: [0m[32minfo[0m: applying exec-redirections-doc.diff
[1mdpkg-source: [0m[32minfo[0m: applying bash-aliases-repeat.diff
[1mdpkg-source: [0m[32minfo[0m: applying use-system-texi2html.diff
[1mdpkg-source: [0m[32minfo[0m: applying bzero.diff
[1mdpkg-source: [0m[32minfo[0m: applying man-macro-warnings.diff
[1mdpkg-source: [0m[32minfo[0m: applying po-de-fix.diff
[1mdpkg-source: [0m[32minfo[0m: applying man-vx-opts.diff
[1mdpkg-source: [0m[32minfo[0m: applying wait-builtin-avoid-hanging-on-inherited-children.diff
>>> Preparing working source directory
[1;33m*** Warning:[0;0m Some build dependencies are not installed.
[1;33m*** Warning:[0;0m This package may end up missing features, or not build at all.
[1;33m*** Warning:[0;0m Consider installing these packages first before continuing:
[1;33m*** Warning:[0;0m     texlive-latex-base texlive-fonts-recommended man2html-base 
[1;39m>>> Compiling bash-5.0-4-1.i686[0;0m
dpkg-buildpackage: info: source package bash
dpkg-buildpackage: info: source version 5.0-4
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Matthias Klose <doko@debian.org>
dpkg-architecture: warning: default GNU system type i686-linux-gnu for Debian arch i386 does not match specified GNU system type i686-pc-cygwin
 dpkg-source --auto-commit --before-build .
dpkg-buildpackage: info: host architecture i386
 debian/rules clean
make[1]: Entering directory '/mnt/bash-5.0-4-1.i686/build/bash'
debian/rules:167: target 'clean' does not exist
dh_testdir
dh_testroot
rm -rf stamps build-*
rm -f debian/bash.preinst debian/*.o
rm -f debian/README.Debian
rm -rf locales
rm -f clear_console
dh_autotools-dev_restoreconfig
dh_autotools-dev_restoreconfig: dh_autotools-dev_restoreconfig is deprecated; please see dh_autotools-dev_restoreconfig(1) for a replacement
dh_autotools-dev_restoreconfig: This feature will be removed in compat 12.
dh_clean
make[1]: Leaving directory '/mnt/bash-5.0-4-1.i686/build/bash'
 dpkg-source --auto-commit -b .
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building bash using existing ./bash_5.0.orig.tar.xz
dpkg-source: info: using patch list from debian/patches/series
dpkg-source: info: building bash in bash_5.0-4.debian.tar.xz
dpkg-source: info: building bash in bash_5.0-4.dsc
 debian/rules binary
make[1]: Entering directory '/mnt/bash-5.0-4-1.i686/build/bash'
debian/rules:114: target 'bash-build' does not exist
/usr/bin/make -f debian/rules do-build-bash \
    bash_src=. \
    build=bash \
    configure_args="--enable-largefile --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --without-bash-malloc --build i686-pc-cygwin"
make[2]: Entering directory '/mnt/bash-5.0-4-1.i686/build/bash'
debian/rules:405: target 'stamps/stamp-configure-bash' does not exist
dh_testdir
rm -rf build-bash
mkdir build-bash
cd build-bash && \
    CC="gcc" \
    CFLAGS="-Wall" CPPFLAGS="" LDFLAGS="" \
    YACC="bison -y" \
	.././configure --enable-largefile --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --without-bash-malloc --build i686-pc-cygwin
configure: loading site script /usr/share/config.site
checking build system type... i686-pc-cygwin
checking host system type... i686-pc-cygwin

Beginning configuration for bash-5.0-release for i686-pc-cygwin

checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for strerror in -lcposix... no
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking whether gcc needs -traditional... no
checking for a BSD-compatible install... /usr/bin/install -c
checking for ar... ar
checking for ranlib... ranlib
checking for bison... bison -y
checking whether make sets $(MAKE)... yes
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking whether byte ordering is bigendian... no
checking for preprocessor stringizing operator... yes
checking for long double with more range or precision than double... yes
checking for function prototypes... yes
checking whether char is unsigned... no
checking for working volatile... yes
checking for C/C++ restrict keyword... __restrict
checking whether NLS is requested... yes
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for off_t... yes
checking for size_t... yes
checking for working alloca.h... yes
checking for alloca... yes
checking for stdlib.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... yes
checking for sys/time.h... yes
checking for getpagesize... yes
checking for working mmap... yes
checking whether we are using the GNU C Library 2.1 or newer... no
checking whether integer division by zero raises SIGFPE... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unsigned long long... yes
checking for inttypes.h... yes
checking whether the inttypes.h PRIxNN macros are broken... no
checking for ld used by GCC... /usr/i686-pc-cygwin/bin/ld.exe
checking if the linker (/usr/i686-pc-cygwin/bin/ld.exe) is GNU ld... yes
checking for shared library run path origin... done
checking argz.h usability... yes
checking argz.h presence... yes
checking for argz.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking nl_types.h usability... no
checking nl_types.h presence... no
checking for nl_types.h... no
checking malloc.h usability... yes
checking malloc.h presence... yes
checking for malloc.h... yes
checking stddef.h usability... yes
checking stddef.h presence... yes
checking for stddef.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking for sys/param.h... (cached) yes
checking for feof_unlocked... yes
checking for fgets_unlocked... yes
checking for getc_unlocked... yes
checking for getcwd... yes
checking for getegid... yes
checking for geteuid... yes
checking for getgid... yes
checking for getuid... yes
checking for mempcpy... yes
checking for munmap... yes
checking for putenv... yes
checking for setenv... yes
checking for setlocale... yes
checking for localeconv... yes
checking for stpcpy... yes
checking for strcasecmp... yes
checking for strdup... yes
checking for strtoul... yes
checking for tsearch... yes
checking for __argz_count... yes
checking for __argz_stringify... yes
checking for __argz_next... yes
checking for __fsetlocking... yes
checking for iconv... yes
checking how to link with libiconv... /usr/lib/libiconv.a
checking for iconv declaration... 
         extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
checking for nl_langinfo and CODESET... yes
checking for LC_MESSAGES... yes
checking for bison... bison
checking version of bison... 3.0.4, ok
checking whether NLS is requested... yes
checking whether included gettext is requested... no
checking for GNU gettext in libc... no
checking for GNU gettext in libintl... yes
checking whether to use NLS... yes
checking where the gettext function comes from... external libintl
checking how to link with libintl... /usr/lib/libintl.a /usr/lib/libiconv.a
checking for dirent.h that defines DIR... yes
checking for library containing opendir... none required
checking whether time.h and sys/time.h may both be included... yes
checking for inttypes.h... (cached) yes
checking for unistd.h... (cached) yes
checking for stdlib.h... (cached) yes
checking stdarg.h usability... yes
checking stdarg.h presence... yes
checking for stdarg.h... yes
checking varargs.h usability... no
checking varargs.h presence... no
checking for varargs.h... no
checking for limits.h... (cached) yes
checking for string.h... (cached) yes
checking for memory.h... (cached) yes
checking for locale.h... (cached) yes
checking termcap.h usability... yes
checking termcap.h presence... yes
checking for termcap.h... yes
checking termio.h usability... yes
checking termio.h presence... yes
checking for termio.h... yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking stdbool.h usability... yes
checking stdbool.h presence... yes
checking for stdbool.h... yes
checking for stddef.h... (cached) yes
checking for stdint.h... (cached) yes
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes
checking pwd.h usability... yes
checking pwd.h presence... yes
checking for pwd.h... yes
checking grp.h usability... yes
checking grp.h presence... yes
checking for grp.h... yes
checking for strings.h... (cached) yes
checking regex.h usability... yes
checking regex.h presence... yes
checking for regex.h... yes
checking syslog.h usability... yes
checking syslog.h presence... yes
checking for syslog.h... yes
checking ulimit.h usability... no
checking ulimit.h presence... no
checking for ulimit.h... no
checking sys/pte.h usability... no
checking sys/pte.h presence... no
checking for sys/pte.h... no
checking sys/stream.h usability... no
checking sys/stream.h presence... no
checking for sys/stream.h... no
checking sys/select.h usability... yes
checking sys/select.h presence... yes
checking for sys/select.h... yes
checking sys/file.h usability... yes
checking sys/file.h presence... yes
checking for sys/file.h... yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking for sys/param.h... (cached) yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking for sys/stat.h... (cached) yes
checking for sys/time.h... (cached) yes
checking sys/times.h usability... yes
checking sys/times.h presence... yes
checking for sys/times.h... yes
checking for sys/types.h... (cached) yes
checking sys/wait.h usability... yes
checking sys/wait.h presence... yes
checking for sys/wait.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking for sys/ptem.h... no
checking for sys/resource.h... yes
checking for working alloca.h... (cached) yes
checking for alloca... (cached) yes
checking for uid_t in sys/types.h... yes
checking for unistd.h... (cached) yes
checking for working chown... yes
checking whether getpgrp requires zero arguments... yes
checking for vprintf... yes
checking for _doprnt... no
checking for working strcoll... yes
checking return type of signal handlers... void
checking for __setostype... no
checking for wait3... yes
checking for mkfifo... yes
checking for dup2... yes
checking for eaccess... yes
checking for fcntl... yes
checking for getdtablesize... yes
checking for getgroups... yes
checking for gethostname... yes
checking for getpagesize... (cached) yes
checking for getpeername... yes
checking for getrlimit... yes
checking for getrusage... yes
checking for gettimeofday... yes
checking for kill... yes
checking for killpg... yes
checking for lstat... yes
checking for pselect... yes
checking for readlink... yes
checking for select... yes
checking for setdtablesize... yes
checking for setitimer... yes
checking for tcgetpgrp... yes
checking for uname... yes
checking for ulimit... no
checking for waitpid... yes
checking for rename... yes
checking for bcopy... yes
checking for bzero... yes
checking for confstr... yes
checking for faccessat... yes
checking for fnmatch... yes
checking for getaddrinfo... yes
checking for gethostbyname... yes
checking for getservbyname... yes
checking for getservent... yes
checking for inet_aton... yes
checking for imaxdiv... yes
checking for memmove... yes
checking for pathconf... yes
checking for putenv... (cached) yes
checking for raise... yes
checking for random... yes
checking for regcomp... yes
checking for regexec... yes
checking for setenv... (cached) yes
checking for setlinebuf... yes
checking for setlocale... (cached) yes
checking for setvbuf... yes
checking for siginterrupt... yes
checking for strchr... yes
checking for sysconf... yes
checking for syslog... yes
checking for tcgetattr... yes
checking for times... yes
checking for ttyname... yes
checking for tzset... yes
checking for unsetenv... yes
checking for vasprintf... yes
checking for asprintf... yes
checking for isascii... yes
checking for isblank... yes
checking for isgraph... yes
checking for isprint... yes
checking for isspace... yes
checking for isxdigit... yes
checking for getpwent... yes
checking for getpwnam... yes
checking for getpwuid... yes
checking for mkstemp... yes
checking for getcwd... (cached) yes
checking for memset... yes
checking for strcasecmp... (cached) yes
checking for strcasestr... yes
checking for strerror... yes
checking for strftime... yes
checking for strnlen... yes
checking for strpbrk... yes
checking for strstr... yes
checking for strtod... yes
checking for strtol... yes
checking for strtoul... (cached) yes
checking for strtoll... yes
checking for strtoull... yes
checking for strtoimax... yes
checking for strtoumax... yes
checking for dprintf... yes
checking for strchrnul... yes
checking for strdup... (cached) yes
checking libaudit.h usability... no
checking libaudit.h presence... no
checking for libaudit.h... no
checking whether AUDIT_USER_TTY is declared... no
checking whether confstr is declared... yes
checking whether printf is declared... yes
checking whether sbrk is declared... yes
checking whether setregid is declared... yes
checking whether strcpy is declared... yes
checking whether strsignal is declared... yes
checking whether strtold is declared... yes
checking for broken strtold... no
checking for declaration of strtoimax... yes
checking for declaration of strtol... yes
checking for declaration of strtoll... yes
checking for declaration of strtoul... yes
checking for declaration of strtoull... yes
checking for declaration of strtoumax... yes
checking for alarm... yes
checking for sbrk... yes
checking for fpurge... yes
checking for __fpurge... yes
checking for snprintf... yes
checking for vsnprintf... yes
checking for working mktime... yes
checking for argz.h... (cached) yes
checking errno.h usability... yes
checking errno.h presence... yes
checking for errno.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking for malloc.h... (cached) yes
checking stdio_ext.h usability... yes
checking stdio_ext.h presence... yes
checking for stdio_ext.h... yes
checking for getpagesize... (cached) yes
checking for working mmap... (cached) yes
checking for __argz_count... (cached) yes
checking for __argz_next... (cached) yes
checking for __argz_stringify... (cached) yes
checking for dcgettext... no
checking for mempcpy... (cached) yes
checking for munmap... (cached) yes
checking for mremap... no
checking for stpcpy... (cached) yes
checking for strcspn... yes
checking wctype.h usability... yes
checking wctype.h presence... yes
checking for wctype.h... yes
checking wchar.h usability... yes
checking wchar.h presence... yes
checking for wchar.h... yes
checking langinfo.h usability... yes
checking langinfo.h presence... yes
checking for langinfo.h... yes
checking mbstr.h usability... no
checking mbstr.h presence... no
checking for mbstr.h... no
checking for mbrlen... yes
checking for mbscasecmp... no
checking for mbscmp... no
checking for mbsnrtowcs... yes
checking for mbsrtowcs... yes
checking for mbschr... no
checking for wcrtomb... yes
checking for wcscoll... yes
checking for wcsdup... yes
checking for wcwidth... yes
checking for wctype... yes
checking for wcswidth... yes
checking whether mbrtowc and mbstate_t are properly declared... yes
checking for iswlower... yes
checking for iswupper... yes
checking for towlower... yes
checking for towupper... yes
checking for iswctype... yes
checking for nl_langinfo and CODESET... yes
checking for wchar_t in wchar.h... yes
checking for wctype_t in wctype.h... yes
checking for wint_t in wctype.h... yes
checking for wcwidth broken with unicode combining characters... no
checking for locale_charset... yes
checking size of wchar_t... 2
checking for dlopen in -ldl... yes
checking for dlopen... yes
checking for dlclose... yes
checking for dlsym... yes
checking whether sys_siglist is declared... yes
checking type of array argument to getgroups... gid_t
checking for off_t... (cached) yes
checking for mode_t... yes
checking for uid_t in sys/types.h... (cached) yes
checking for pid_t... yes
checking for size_t... (cached) yes
checking for uintptr_t... yes
checking for ssize_t... yes
checking for time_t... yes
checking for long long... long long
checking for unsigned long long... unsigned long long
checking return type of signal handlers... (cached) void
checking for sig_atomic_t in signal.h... yes
checking size of char... 1
checking size of short... 2
checking size of int... 4
checking size of long... 4
checking size of char *... 4
checking size of double... 8
checking size of long long... 8
checking for u_int... yes
checking for u_long... yes
checking for bits16_t... no
checking for u_bits16_t... no
checking for bits32_t... no
checking for u_bits32_t... no
checking for bits64_t... no
checking for ptrdiff_t... yes
checking whether stat file-mode macros are broken... no
checking whether #! works in shell scripts... yes
checking whether the ctype macros accept non-ascii characters... yes
checking if dup2 fails to clear the close-on-exec flag... no
checking whether pgrps need synchronization... no
checking for type of signal functions... posix
checking for sys_errlist and sys_nerr... no
checking for sys_siglist in system C library... yes
checking for _sys_siglist in signal.h or unistd.h... no
checking for _sys_siglist in system C library... no
checking whether signal handlers are of type void... yes
checking for clock_t... yes
checking for sigset_t... yes
checking for sig_atomic_t... yes
checking for quad_t... no
checking for intmax_t... yes
checking for uintmax_t... yes
checking for socklen_t... yes
checking for size and type of struct rlimit fields... rlim_t
checking size of intmax_t... 8
checking for struct termios.c_line... yes
checking for struct termio.c_line... yes
checking for struct dirent.d_ino... yes
checking for struct dirent.d_fileno... yes
checking for struct dirent.d_namlen... no
checking for struct winsize in sys/ioctl.h and termios.h... sys/ioctl.h
checking for struct timeval in sys/time.h and time.h... yes
checking for struct stat.st_blocks... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for struct tm.tm_zone... yes
checking for struct timezone in sys/time.h and time.h... yes
checking for offset of exit status in return status from wait... 8
checking for struct timespec in <time.h>... yes
checking for struct stat.st_atim.tv_nsec... yes
checking whether struct stat.st_atim is of type struct timespec... yes
checking for working sbrk... yes
checking for the existence of strsignal... yes
checking if opendir() opens non-directories... no
checking whether ulimit can substitute for getdtablesize... no
checking whether fpurge is declared... yes
checking to see if getenv can be redefined... yes
checking if getcwd() will dynamically allocate memory with 0 size... yes
checking for presence of POSIX-style sigsetjmp/siglongjmp... present
checking whether or not strcoll and strcmp differ... no
checking for standard-conformant snprintf... yes
checking for standard-conformant vsnprintf... yes
checking for standard-conformant putenv declaration... yes
checking for standard-conformant unsetenv declaration... yes
checking for printf floating point output in hex notation... yes
checking whether fnmatch can be used to check bracket equivalence classes... no
checking if signal handlers must be reinstalled when invoked... no
checking for presence of necessary job control definitions... present
checking for presence of named pipes... present
checking whether termios.h defines TIOCGWINSZ... yes
checking for TIOCSTAT in sys/ioctl.h... no
checking for FIONREAD in sys/ioctl.h... no
checking whether WCONTINUED flag to waitpid is unavailable or available but broken... no
checking for speed_t in sys/types.h... no
checking whether getpw functions are declared in pwd.h... yes
checking for unusable real-time signals due to large values... no
checking for tgetent... no
checking for tgetent in -ltermcap... no
checking for tgetent in -ltinfo... no
checking for tgetent in -lcurses... yes
checking which library has the termcap functions... using libcurses
checking whether /dev/fd is available... standard
checking whether /dev/stdin stdout stderr are available... present
checking for default mail directory... /var/spool/mail
checking shared object configuration for loadable builtins... supported
configure: creating ./config.status
config.status: creating Makefile
config.status: creating builtins/Makefile
config.status: creating lib/readline/Makefile
config.status: creating lib/glob/Makefile
config.status: creating lib/intl/Makefile
config.status: creating lib/malloc/Makefile
config.status: creating lib/sh/Makefile
config.status: creating lib/termcap/Makefile
config.status: creating lib/tilde/Makefile
config.status: creating doc/Makefile
config.status: creating support/Makefile
config.status: creating po/Makefile.in
config.status: creating examples/loadables/Makefile
config.status: creating examples/loadables/Makefile.inc
config.status: creating examples/loadables/perl/Makefile
config.status: creating support/bash.pc
config.status: creating support/bashbug.sh
config.status: creating config.h
config.status: executing default-1 commands
config.status: creating po/POTFILES
config.status: creating po/Makefile
config.status: executing default commands
if ! grep -q '#define HAVE_DEV_STDIN 1' build-bash/config.h; then \
  echo "HAVE_DEV_STDIN not defined, abortig build"; \
  exit 1; \
fi
touch stamps/stamp-configure-bash
touch: cannot touch 'stamps/stamp-configure-bash': No such file or directory
make[2]: *** [debian/rules:410: stamps/stamp-configure-bash] Error 1
make[2]: Leaving directory '/mnt/bash-5.0-4-1.i686/build/bash'
make[1]: *** [debian/rules:114: bash-build] Error 2
make[1]: Leaving directory '/mnt/bash-5.0-4-1.i686/build/bash'
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make: *** [makefile:147: bash_5.0-4.i686] Error 1
rm bash_5.0-4.dsc

Script done on Thu Apr 16 20:39:51 2020
