Script started on Tue Apr 14 20:25:28 2020
cygport --32 calm.cygport all
]0;/mnt
[32mAdministrator@- [33m/mnt[0m
$ cygport --32 calm.cygport all
[1;39m>>> Preparing calm-20160730-1.noarch[0;0m
>>> Unpacking source calm-20160730.tar.bz2
>>> Preparing working source directory
[1;39m>>> Compiling calm-20160730-1.noarch[0;0m
running build
running build_py
creating build
creating build/lib
creating build/lib/calm
copying calm/package.py -> build/lib/calm
copying calm/buffering_smtp_handler.py -> build/lib/calm
copying calm/uploads.py -> build/lib/calm
copying calm/maintainers.py -> build/lib/calm
copying calm/mksetupini.py -> build/lib/calm
copying calm/fix-missing-cygwin-dep.py -> build/lib/calm
copying calm/spelling.py -> build/lib/calm
copying calm/past_mistakes.py -> build/lib/calm
copying calm/common_constants.py -> build/lib/calm
copying calm/queue.py -> build/lib/calm
copying calm/hint.py -> build/lib/calm
copying calm/setup_exe.py -> build/lib/calm
copying calm/calm.py -> build/lib/calm
copying calm/version.py -> build/lib/calm
copying calm/pkg2html.py -> build/lib/calm
copying calm/abeyance_handler.py -> build/lib/calm
copying calm/__init__.py -> build/lib/calm
[1;39m>>> Installing calm-20160730-1.noarch[0;0m
running install
running build
running build_py
running install_lib
creating /mnt/calm-20160730-1.noarch/inst/usr
creating /mnt/calm-20160730-1.noarch/inst/usr/lib
creating /mnt/calm-20160730-1.noarch/inst/usr/lib/python3.4
creating /mnt/calm-20160730-1.noarch/inst/usr/lib/python3.4/site-packages
creating /mnt/calm-20160730-1.noarch/inst/usr/lib/python3.4/site-packages/calm
copying build/lib/calm/package.py -> /mnt/calm-20160730-1.noarch/inst/usr/lib/python3.4/site-packages/calm
copying build/lib/calm/buffering_smtp_handler.py -> /mnt/calm-20160730-1.noarch/inst/usr/lib/python3.4/site-packages/calm
copying build/lib/calm/uploads.py -> /mnt/calm-20160730-1.noarch/inst/usr/lib/python3.4/site-packages/calm
copying build/lib/calm/maintainers.py -> /mnt/calm-20160730-1.noarch/inst/usr/lib/python3.4/site-packages/calm
copying build/lib/calm/mksetupini.py -> /mnt/calm-20160730-1.noarch/inst/usr/lib/python3.4/site-packages/calm
copying build/lib/calm/fix-missing-cygwin-dep.py -> /mnt/calm-20160730-1.noarch/inst/usr/lib/python3.4/site-packages/calm
copying build/lib/calm/spelling.py -> /mnt/calm-20160730-1.noarch/inst/usr/lib/python3.4/site-packages/calm
copying build/lib/calm/past_mistakes.py -> /mnt/calm-20160730-1.noarch/inst/usr/lib/python3.4/site-packages/calm
copying build/lib/calm/common_constants.py -> /mnt/calm-20160730-1.noarch/inst/usr/lib/python3.4/site-packages/calm
copying build/lib/calm/queue.py -> /mnt/calm-20160730-1.noarch/inst/usr/lib/python3.4/site-packages/calm
copying build/lib/calm/hint.py -> /mnt/calm-20160730-1.noarch/inst/usr/lib/python3.4/site-packages/calm
copying build/lib/calm/setup_exe.py -> /mnt/calm-20160730-1.noarch/inst/usr/lib/python3.4/site-packages/calm
copying build/lib/calm/calm.py -> /mnt/calm-20160730-1.noarch/inst/usr/lib/python3.4/site-packages/calm
copying build/lib/calm/version.py -> /mnt/calm-20160730-1.noarch/inst/usr/lib/python3.4/site-packages/calm
copying build/lib/calm/pkg2html.py -> /mnt/calm-20160730-1.noarch/inst/usr/lib/python3.4/site-packages/calm
copying build/lib/calm/abeyance_handler.py -> /mnt/calm-20160730-1.noarch/inst/usr/lib/python3.4/site-packages/calm
copying build/lib/calm/__init__.py -> /mnt/calm-20160730-1.noarch/inst/usr/lib/python3.4/site-packages/calm
running install_egg_info
running egg_info
creating calm.egg-info
writing dependency_links to calm.egg-info/dependency_links.txt
writing top-level names to calm.egg-info/top_level.txt
writing entry points to calm.egg-info/entry_points.txt
writing calm.egg-info/PKG-INFO
writing manifest file 'calm.egg-info/SOURCES.txt'
reading manifest file 'calm.egg-info/SOURCES.txt'
writing manifest file 'calm.egg-info/SOURCES.txt'
Copying calm.egg-info to /mnt/calm-20160730-1.noarch/inst/usr/lib/python3.4/site-packages/calm-20160512-py3.4.egg-info
running install_scripts
Installing mksetupini script to /mnt/calm-20160730-1.noarch/inst/usr/bin
Installing calm script to /mnt/calm-20160730-1.noarch/inst/usr/bin
/usr/bin/install -m0644 README.md /mnt/calm-20160730-1.noarch/inst/usr/share/doc/calm/README.md
/usr/bin/install -m0644 TODO /mnt/calm-20160730-1.noarch/inst/usr/share/doc/calm/TODO
Fixing symlinks:
[1;32m*** Info:[0;0m Byte-compiling /usr/lib/python3.4...
Stripping executables:
Preparing debuginfo source files:

[1;39m>>> Packaging calm-20160730-1.noarch[0;0m
>>> Creating binary package(s)
>>> calm-20160730-1.tar.xz
usr/
usr/lib/
usr/lib/python3.4/
usr/lib/python3.4/site-packages/
usr/lib/python3.4/site-packages/calm/
usr/lib/python3.4/site-packages/calm/package.py
usr/lib/python3.4/site-packages/calm/buffering_smtp_handler.py
usr/lib/python3.4/site-packages/calm/uploads.py
usr/lib/python3.4/site-packages/calm/maintainers.py
usr/lib/python3.4/site-packages/calm/mksetupini.py
usr/lib/python3.4/site-packages/calm/fix-missing-cygwin-dep.py
usr/lib/python3.4/site-packages/calm/spelling.py
usr/lib/python3.4/site-packages/calm/past_mistakes.py
usr/lib/python3.4/site-packages/calm/common_constants.py
usr/lib/python3.4/site-packages/calm/queue.py
usr/lib/python3.4/site-packages/calm/__pycache__/
usr/lib/python3.4/site-packages/calm/__pycache__/package.cpython-34.pyo
usr/lib/python3.4/site-packages/calm/__pycache__/pkg2html.cpython-34.pyc
usr/lib/python3.4/site-packages/calm/__pycache__/spelling.cpython-34.pyc
usr/lib/python3.4/site-packages/calm/__pycache__/fix-missing-cygwin-dep.cpython-34.pyc
usr/lib/python3.4/site-packages/calm/__pycache__/common_constants.cpython-34.pyo
usr/lib/python3.4/site-packages/calm/__pycache__/uploads.cpython-34.pyc
usr/lib/python3.4/site-packages/calm/__pycache__/setup_exe.cpython-34.pyc
usr/lib/python3.4/site-packages/calm/__pycache__/maintainers.cpython-34.pyc
usr/lib/python3.4/site-packages/calm/__pycache__/calm.cpython-34.pyc
usr/lib/python3.4/site-packages/calm/__pycache__/buffering_smtp_handler.cpython-34.pyc
usr/lib/python3.4/site-packages/calm/__pycache__/uploads.cpython-34.pyo
usr/lib/python3.4/site-packages/calm/__pycache__/fix-missing-cygwin-dep.cpython-34.pyo
usr/lib/python3.4/site-packages/calm/__pycache__/version.cpython-34.pyo
usr/lib/python3.4/site-packages/calm/__pycache__/queue.cpython-34.pyo
usr/lib/python3.4/site-packages/calm/__pycache__/queue.cpython-34.pyc
usr/lib/python3.4/site-packages/calm/__pycache__/version.cpython-34.pyc
usr/lib/python3.4/site-packages/calm/__pycache__/calm.cpython-34.pyo
usr/lib/python3.4/site-packages/calm/__pycache__/setup_exe.cpython-34.pyo
usr/lib/python3.4/site-packages/calm/__pycache__/mksetupini.cpython-34.pyc
usr/lib/python3.4/site-packages/calm/__pycache__/spelling.cpython-34.pyo
usr/lib/python3.4/site-packages/calm/__pycache__/past_mistakes.cpython-34.pyc
usr/lib/python3.4/site-packages/calm/__pycache__/abeyance_handler.cpython-34.pyc
usr/lib/python3.4/site-packages/calm/__pycache__/hint.cpython-34.pyo
usr/lib/python3.4/site-packages/calm/__pycache__/pkg2html.cpython-34.pyo
usr/lib/python3.4/site-packages/calm/__pycache__/__init__.cpython-34.pyo
usr/lib/python3.4/site-packages/calm/__pycache__/__init__.cpython-34.pyc
usr/lib/python3.4/site-packages/calm/__pycache__/abeyance_handler.cpython-34.pyo
usr/lib/python3.4/site-packages/calm/__pycache__/package.cpython-34.pyc
usr/lib/python3.4/site-packages/calm/__pycache__/maintainers.cpython-34.pyo
usr/lib/python3.4/site-packages/calm/__pycache__/buffering_smtp_handler.cpython-34.pyo
usr/lib/python3.4/site-packages/calm/__pycache__/hint.cpython-34.pyc
usr/lib/python3.4/site-packages/calm/__pycache__/past_mistakes.cpython-34.pyo
usr/lib/python3.4/site-packages/calm/__pycache__/common_constants.cpython-34.pyc
usr/lib/python3.4/site-packages/calm/__pycache__/mksetupini.cpython-34.pyo
usr/lib/python3.4/site-packages/calm/hint.py
usr/lib/python3.4/site-packages/calm/setup_exe.py
usr/lib/python3.4/site-packages/calm/calm.py
usr/lib/python3.4/site-packages/calm/version.py
usr/lib/python3.4/site-packages/calm/pkg2html.py
usr/lib/python3.4/site-packages/calm/abeyance_handler.py
usr/lib/python3.4/site-packages/calm/__init__.py
usr/lib/python3.4/site-packages/calm-20160512-py3.4.egg-info/
usr/lib/python3.4/site-packages/calm-20160512-py3.4.egg-info/top_level.txt
usr/lib/python3.4/site-packages/calm-20160512-py3.4.egg-info/SOURCES.txt
usr/lib/python3.4/site-packages/calm-20160512-py3.4.egg-info/dependency_links.txt
usr/lib/python3.4/site-packages/calm-20160512-py3.4.egg-info/entry_points.txt
usr/lib/python3.4/site-packages/calm-20160512-py3.4.egg-info/PKG-INFO
usr/share/
usr/share/doc/
usr/share/doc/calm/
usr/share/doc/calm/README.md
usr/share/doc/calm/TODO
usr/bin/
usr/bin/calm
usr/bin/mksetupini

[1;32m*** Info:[0;0m No debug files, skipping debuginfo subpackage

>>> Checking packages for missing or duplicate files

>>> Creating source patches
 0 files changed
>>> Creating source package
calm-20160730-1.src/
calm-20160730-1.src/calm-20160730.tar.bz2
calm-20160730-1.src/calm.cygport

>>> calm requires: python python3 python3-setuptools 
]0;/mnt
[32mAdministrator@- [33m/mnt[0m
$ exit

Script done on Tue Apr 14 20:28:58 2020
