Script started on Wed Apr 15 23:25:54 2020
makefile:143: update target 'dctrl-tools_2.24-3.i686' due to: dctrl-tools_2.24-3.dsc
cygport --32 dctrl-tools_2.24-3.cygport all
[1;39m>>> Preparing dctrl-tools-2.24-3-1.i686[0;0m
>>> Unpacking source dctrl-tools_2.24-3.dsc
>>> Unpacking source dctrl-tools_2.24.orig.tar.gz
>>> Unpacking source dctrl-tools_2.24-3.debian.tar.xz
gpgv: keyblock resource `/home/Administrator/.gnupg/trustedkeys.gpg': file open error
gpgv: Signature made Thu Sep 27 07:14:20 2018 CEST using RSA key ID E17EBB30
gpgv: Can't check signature: public key not found
[1mdpkg-source: [0m[1;33mwarning[0m: failed to verify signature on /mnt/dctrl-tools_2.24-3.dsc
[1mdpkg-source: [0m[32minfo[0m: extracting dctrl-tools in dctrl-tools
[1mdpkg-source: [0m[32minfo[0m: unpacking dctrl-tools_2.24.orig.tar.gz
[1mdpkg-source: [0m[32minfo[0m: unpacking dctrl-tools_2.24-3.debian.tar.xz
[1mdpkg-source: [0m[32minfo[0m: using patch list from debian/patches/series
[1mdpkg-source: [0m[32minfo[0m: applying GNUmakefile_remove---force-from-po4a-call
[1mdpkg-source: [0m[32minfo[0m: applying reproducible_build.patch
[1;32m*** Info:[0;0m applying patch dctrl-tools.patch:
patching file dctrl-tools/GNUmakefile
>>> Preparing working source directory
[1;39m>>> Compiling dctrl-tools-2.24-3-1.i686[0;0m
dpkg-buildpackage: info: source package dctrl-tools
dpkg-buildpackage: info: source version 2.24-3
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Rhonda D'Vine <rhonda@debian.org>
dpkg-architecture: warning: default GNU system type i686-linux-gnu for Debian arch i386 does not match specified GNU system type i686-pc-cygwin
 dpkg-source --auto-commit --before-build .
dpkg-buildpackage: info: host architecture i386
 debian/rules clean
make[1]: Entering directory '/mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools'
debian/rules:6: target 'clean' does not exist
dh clean
   dh_auto_clean
	make -j1 distclean
make[2]: Entering directory '/mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools'
GNUmakefile:198: target 'clean' does not exist
rm -f core grep-dctrl/grep-dctrl sort-dctrl/sort-dctrl tbl-dctrl/tbl-dctrl join-dctrl/join-dctrl man/grep-dctrl.1 grep-dctrl/grep-dctrl.o join-dctrl/join-dctrl.o lib/atom.o lib/fieldtrie.o lib/fnutil.o lib/fsaf.o lib/ifile.o lib/misc.o lib/msg.o lib/para_bundle.o lib/para_pool.o lib/paragraph.o lib/predicate.o lib/sorter.o lib/strlist.o lib/strutil.o lib/util.o lib/version.o sort-dctrl/sort-dctrl.o tbl-dctrl/tbl-dctrl.o so/*.o libdctrl.a libdctrl.so
rm -f po/*.mo TAGS *.d */*.d
rm -f sync-available/sync-available
rm -f -r man/translated
make[2]: Leaving directory '/mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools'
   dh_clean
make[1]: Leaving directory '/mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools'
 dpkg-source --auto-commit -b .
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building dctrl-tools using existing ./dctrl-tools_2.24.orig.tar.gz
dpkg-source: info: using patch list from debian/patches/series
dpkg-source: warning: newly created empty file 'man/po4a/po/dctrl-tools-man.pot' will not be represented in diff
dpkg-source: info: local changes detected, the modified files are:
 dctrl-tools/GNUmakefile
 dctrl-tools/po/dctrl-tools.pot
dpkg-source: info: local changes have been recorded in a new patch: dctrl-tools/debian/patches/debian-changes-2.24-3
dpkg-source: info: building dctrl-tools in dctrl-tools_2.24-3.debian.tar.xz
dpkg-source: info: building dctrl-tools in dctrl-tools_2.24-3.dsc
 debian/rules binary
make[1]: Entering directory '/mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools'
debian/rules:6: target 'binary' does not exist
dh binary
   dh_update_autotools_config
   dh_autoreconf
   dh_auto_configure
   debian/rules override_dh_auto_build
make[2]: Entering directory '/mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools'
debian/rules:17: target 'override_dh_auto_build' does not exist
dh_auto_build -- prefix=/usr sysconfdir=/etc 
	make -j1 prefix=/usr sysconfdir=/etc
make[3]: Entering directory '/mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools'
GNUmakefile:157: update target 'sync-available/sync-available' due to: sync-available/sync-available.cp
sed 's*VERSION*2.24*' sync-available/sync-available.cp > sync-available/sync-available
chmod 755 sync-available/sync-available
GNUmakefile:154: update target 'man/grep-dctrl.1' due to: man/grep-dctrl.1.cp
sed 's*SYSCONF*/etc*' man/grep-dctrl.1.cp > man/grep-dctrl.1
GNUmakefile:136: update target 'grep-dctrl/grep-dctrl.o' due to: grep-dctrl/grep-dctrl.c
gcc   -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/build=/usr/src/debug/dctrl-tools-2.24-3-1 -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/src=/usr/src/debug/dctrl-tools-2.24-3-1 -std=gnu99 -Ilib -DENABLE_L_DEBUG -D_GNU_SOURCE -DSYSCONF=\"/etc\" -DHAVE_GETTEXT -DPACKAGE=\"dctrl-tools\" -DLOCALEDIR=\"/usr/share/locale\"  -DVERSION=\"2.24\" -DMAINTAINER='"Antti-Juhani Kaijanaho <antti-juhani@kaijanaho.fi>"' -MD -MF grep-dctrl/grep-dctrl.d -c -o grep-dctrl/grep-dctrl.o grep-dctrl/grep-dctrl.c
GNUmakefile:136: update target 'lib/atom.o' due to: lib/atom.c
gcc   -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/build=/usr/src/debug/dctrl-tools-2.24-3-1 -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/src=/usr/src/debug/dctrl-tools-2.24-3-1 -std=gnu99 -Ilib -DENABLE_L_DEBUG -D_GNU_SOURCE -DSYSCONF=\"/etc\" -DHAVE_GETTEXT -DPACKAGE=\"dctrl-tools\" -DLOCALEDIR=\"/usr/share/locale\"  -DVERSION=\"2.24\" -DMAINTAINER='"Antti-Juhani Kaijanaho <antti-juhani@kaijanaho.fi>"' -MD -MF lib/atom.d -c -o lib/atom.o lib/atom.c
GNUmakefile:136: update target 'lib/fieldtrie.o' due to: lib/fieldtrie.c
gcc   -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/build=/usr/src/debug/dctrl-tools-2.24-3-1 -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/src=/usr/src/debug/dctrl-tools-2.24-3-1 -std=gnu99 -Ilib -DENABLE_L_DEBUG -D_GNU_SOURCE -DSYSCONF=\"/etc\" -DHAVE_GETTEXT -DPACKAGE=\"dctrl-tools\" -DLOCALEDIR=\"/usr/share/locale\"  -DVERSION=\"2.24\" -DMAINTAINER='"Antti-Juhani Kaijanaho <antti-juhani@kaijanaho.fi>"' -MD -MF lib/fieldtrie.d -c -o lib/fieldtrie.o lib/fieldtrie.c
GNUmakefile:136: update target 'lib/fnutil.o' due to: lib/fnutil.c
gcc   -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/build=/usr/src/debug/dctrl-tools-2.24-3-1 -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/src=/usr/src/debug/dctrl-tools-2.24-3-1 -std=gnu99 -Ilib -DENABLE_L_DEBUG -D_GNU_SOURCE -DSYSCONF=\"/etc\" -DHAVE_GETTEXT -DPACKAGE=\"dctrl-tools\" -DLOCALEDIR=\"/usr/share/locale\"  -DVERSION=\"2.24\" -DMAINTAINER='"Antti-Juhani Kaijanaho <antti-juhani@kaijanaho.fi>"' -MD -MF lib/fnutil.d -c -o lib/fnutil.o lib/fnutil.c
GNUmakefile:136: update target 'lib/fsaf.o' due to: lib/fsaf.c
gcc   -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/build=/usr/src/debug/dctrl-tools-2.24-3-1 -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/src=/usr/src/debug/dctrl-tools-2.24-3-1 -std=gnu99 -Ilib -DENABLE_L_DEBUG -D_GNU_SOURCE -DSYSCONF=\"/etc\" -DHAVE_GETTEXT -DPACKAGE=\"dctrl-tools\" -DLOCALEDIR=\"/usr/share/locale\"  -DVERSION=\"2.24\" -DMAINTAINER='"Antti-Juhani Kaijanaho <antti-juhani@kaijanaho.fi>"' -MD -MF lib/fsaf.d -c -o lib/fsaf.o lib/fsaf.c
GNUmakefile:136: update target 'lib/ifile.o' due to: lib/ifile.c
gcc   -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/build=/usr/src/debug/dctrl-tools-2.24-3-1 -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/src=/usr/src/debug/dctrl-tools-2.24-3-1 -std=gnu99 -Ilib -DENABLE_L_DEBUG -D_GNU_SOURCE -DSYSCONF=\"/etc\" -DHAVE_GETTEXT -DPACKAGE=\"dctrl-tools\" -DLOCALEDIR=\"/usr/share/locale\"  -DVERSION=\"2.24\" -DMAINTAINER='"Antti-Juhani Kaijanaho <antti-juhani@kaijanaho.fi>"' -MD -MF lib/ifile.d -c -o lib/ifile.o lib/ifile.c
GNUmakefile:136: update target 'lib/misc.o' due to: lib/misc.c
gcc   -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/build=/usr/src/debug/dctrl-tools-2.24-3-1 -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/src=/usr/src/debug/dctrl-tools-2.24-3-1 -std=gnu99 -Ilib -DENABLE_L_DEBUG -D_GNU_SOURCE -DSYSCONF=\"/etc\" -DHAVE_GETTEXT -DPACKAGE=\"dctrl-tools\" -DLOCALEDIR=\"/usr/share/locale\"  -DVERSION=\"2.24\" -DMAINTAINER='"Antti-Juhani Kaijanaho <antti-juhani@kaijanaho.fi>"' -MD -MF lib/misc.d -c -o lib/misc.o lib/misc.c
GNUmakefile:136: update target 'lib/msg.o' due to: lib/msg.c
gcc   -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/build=/usr/src/debug/dctrl-tools-2.24-3-1 -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/src=/usr/src/debug/dctrl-tools-2.24-3-1 -std=gnu99 -Ilib -DENABLE_L_DEBUG -D_GNU_SOURCE -DSYSCONF=\"/etc\" -DHAVE_GETTEXT -DPACKAGE=\"dctrl-tools\" -DLOCALEDIR=\"/usr/share/locale\"  -DVERSION=\"2.24\" -DMAINTAINER='"Antti-Juhani Kaijanaho <antti-juhani@kaijanaho.fi>"' -MD -MF lib/msg.d -c -o lib/msg.o lib/msg.c
GNUmakefile:136: update target 'lib/para_bundle.o' due to: lib/para_bundle.c
gcc   -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/build=/usr/src/debug/dctrl-tools-2.24-3-1 -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/src=/usr/src/debug/dctrl-tools-2.24-3-1 -std=gnu99 -Ilib -DENABLE_L_DEBUG -D_GNU_SOURCE -DSYSCONF=\"/etc\" -DHAVE_GETTEXT -DPACKAGE=\"dctrl-tools\" -DLOCALEDIR=\"/usr/share/locale\"  -DVERSION=\"2.24\" -DMAINTAINER='"Antti-Juhani Kaijanaho <antti-juhani@kaijanaho.fi>"' -MD -MF lib/para_bundle.d -c -o lib/para_bundle.o lib/para_bundle.c
GNUmakefile:136: update target 'lib/para_pool.o' due to: lib/para_pool.c
gcc   -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/build=/usr/src/debug/dctrl-tools-2.24-3-1 -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/src=/usr/src/debug/dctrl-tools-2.24-3-1 -std=gnu99 -Ilib -DENABLE_L_DEBUG -D_GNU_SOURCE -DSYSCONF=\"/etc\" -DHAVE_GETTEXT -DPACKAGE=\"dctrl-tools\" -DLOCALEDIR=\"/usr/share/locale\"  -DVERSION=\"2.24\" -DMAINTAINER='"Antti-Juhani Kaijanaho <antti-juhani@kaijanaho.fi>"' -MD -MF lib/para_pool.d -c -o lib/para_pool.o lib/para_pool.c
GNUmakefile:136: update target 'lib/paragraph.o' due to: lib/paragraph.c
gcc   -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/build=/usr/src/debug/dctrl-tools-2.24-3-1 -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/src=/usr/src/debug/dctrl-tools-2.24-3-1 -std=gnu99 -Ilib -DENABLE_L_DEBUG -D_GNU_SOURCE -DSYSCONF=\"/etc\" -DHAVE_GETTEXT -DPACKAGE=\"dctrl-tools\" -DLOCALEDIR=\"/usr/share/locale\"  -DVERSION=\"2.24\" -DMAINTAINER='"Antti-Juhani Kaijanaho <antti-juhani@kaijanaho.fi>"' -MD -MF lib/paragraph.d -c -o lib/paragraph.o lib/paragraph.c
GNUmakefile:136: update target 'lib/predicate.o' due to: lib/predicate.c
gcc   -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/build=/usr/src/debug/dctrl-tools-2.24-3-1 -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/src=/usr/src/debug/dctrl-tools-2.24-3-1 -std=gnu99 -Ilib -DENABLE_L_DEBUG -D_GNU_SOURCE -DSYSCONF=\"/etc\" -DHAVE_GETTEXT -DPACKAGE=\"dctrl-tools\" -DLOCALEDIR=\"/usr/share/locale\"  -DVERSION=\"2.24\" -DMAINTAINER='"Antti-Juhani Kaijanaho <antti-juhani@kaijanaho.fi>"' -MD -MF lib/predicate.d -c -o lib/predicate.o lib/predicate.c
GNUmakefile:136: update target 'lib/sorter.o' due to: lib/sorter.c
gcc   -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/build=/usr/src/debug/dctrl-tools-2.24-3-1 -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/src=/usr/src/debug/dctrl-tools-2.24-3-1 -std=gnu99 -Ilib -DENABLE_L_DEBUG -D_GNU_SOURCE -DSYSCONF=\"/etc\" -DHAVE_GETTEXT -DPACKAGE=\"dctrl-tools\" -DLOCALEDIR=\"/usr/share/locale\"  -DVERSION=\"2.24\" -DMAINTAINER='"Antti-Juhani Kaijanaho <antti-juhani@kaijanaho.fi>"' -MD -MF lib/sorter.d -c -o lib/sorter.o lib/sorter.c
GNUmakefile:136: update target 'lib/strlist.o' due to: lib/strlist.c
gcc   -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/build=/usr/src/debug/dctrl-tools-2.24-3-1 -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/src=/usr/src/debug/dctrl-tools-2.24-3-1 -std=gnu99 -Ilib -DENABLE_L_DEBUG -D_GNU_SOURCE -DSYSCONF=\"/etc\" -DHAVE_GETTEXT -DPACKAGE=\"dctrl-tools\" -DLOCALEDIR=\"/usr/share/locale\"  -DVERSION=\"2.24\" -DMAINTAINER='"Antti-Juhani Kaijanaho <antti-juhani@kaijanaho.fi>"' -MD -MF lib/strlist.d -c -o lib/strlist.o lib/strlist.c
GNUmakefile:136: update target 'lib/strutil.o' due to: lib/strutil.c
gcc   -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/build=/usr/src/debug/dctrl-tools-2.24-3-1 -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/src=/usr/src/debug/dctrl-tools-2.24-3-1 -std=gnu99 -Ilib -DENABLE_L_DEBUG -D_GNU_SOURCE -DSYSCONF=\"/etc\" -DHAVE_GETTEXT -DPACKAGE=\"dctrl-tools\" -DLOCALEDIR=\"/usr/share/locale\"  -DVERSION=\"2.24\" -DMAINTAINER='"Antti-Juhani Kaijanaho <antti-juhani@kaijanaho.fi>"' -MD -MF lib/strutil.d -c -o lib/strutil.o lib/strutil.c
GNUmakefile:136: update target 'lib/util.o' due to: lib/util.c
gcc   -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/build=/usr/src/debug/dctrl-tools-2.24-3-1 -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/src=/usr/src/debug/dctrl-tools-2.24-3-1 -std=gnu99 -Ilib -DENABLE_L_DEBUG -D_GNU_SOURCE -DSYSCONF=\"/etc\" -DHAVE_GETTEXT -DPACKAGE=\"dctrl-tools\" -DLOCALEDIR=\"/usr/share/locale\"  -DVERSION=\"2.24\" -DMAINTAINER='"Antti-Juhani Kaijanaho <antti-juhani@kaijanaho.fi>"' -MD -MF lib/util.d -c -o lib/util.o lib/util.c
GNUmakefile:136: update target 'lib/version.o' due to: lib/version.c
gcc   -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/build=/usr/src/debug/dctrl-tools-2.24-3-1 -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/src=/usr/src/debug/dctrl-tools-2.24-3-1 -std=gnu99 -Ilib -DENABLE_L_DEBUG -D_GNU_SOURCE -DSYSCONF=\"/etc\" -DHAVE_GETTEXT -DPACKAGE=\"dctrl-tools\" -DLOCALEDIR=\"/usr/share/locale\"  -DVERSION=\"2.24\" -DMAINTAINER='"Antti-Juhani Kaijanaho <antti-juhani@kaijanaho.fi>"' -MD -MF lib/version.d -c -o lib/version.o lib/version.c
GNUmakefile:139: update target 'libdctrl.a' due to: lib/atom.o lib/fieldtrie.o lib/fnutil.o lib/fsaf.o lib/ifile.o lib/misc.o lib/msg.o lib/para_bundle.o lib/para_pool.o lib/paragraph.o lib/predicate.o lib/sorter.o lib/strlist.o lib/strutil.o lib/util.o lib/version.o
ar cr libdctrl.a lib/atom.o lib/fieldtrie.o lib/fnutil.o lib/fsaf.o lib/ifile.o lib/misc.o lib/msg.o lib/para_bundle.o lib/para_pool.o lib/paragraph.o lib/predicate.o lib/sorter.o lib/strlist.o lib/strutil.o lib/util.o lib/version.o
ranlib libdctrl.a
GNUmakefile:133: update target 'grep-dctrl/grep-dctrl' due to: grep-dctrl/grep-dctrl.o libdctrl.a
gcc   -o grep-dctrl/grep-dctrl grep-dctrl/grep-dctrl.o libdctrl.a -L. -ldctrl -lintl -largp
GNUmakefile:136: update target 'sort-dctrl/sort-dctrl.o' due to: sort-dctrl/sort-dctrl.c
gcc   -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/build=/usr/src/debug/dctrl-tools-2.24-3-1 -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/src=/usr/src/debug/dctrl-tools-2.24-3-1 -std=gnu99 -Ilib -DENABLE_L_DEBUG -D_GNU_SOURCE -DSYSCONF=\"/etc\" -DHAVE_GETTEXT -DPACKAGE=\"dctrl-tools\" -DLOCALEDIR=\"/usr/share/locale\"  -DVERSION=\"2.24\" -DMAINTAINER='"Antti-Juhani Kaijanaho <antti-juhani@kaijanaho.fi>"' -MD -MF sort-dctrl/sort-dctrl.d -c -o sort-dctrl/sort-dctrl.o sort-dctrl/sort-dctrl.c
GNUmakefile:133: update target 'sort-dctrl/sort-dctrl' due to: sort-dctrl/sort-dctrl.o libdctrl.a
gcc   -o sort-dctrl/sort-dctrl sort-dctrl/sort-dctrl.o libdctrl.a -L. -ldctrl -lintl -largp
GNUmakefile:136: update target 'tbl-dctrl/tbl-dctrl.o' due to: tbl-dctrl/tbl-dctrl.c
gcc   -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/build=/usr/src/debug/dctrl-tools-2.24-3-1 -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/src=/usr/src/debug/dctrl-tools-2.24-3-1 -std=gnu99 -Ilib -DENABLE_L_DEBUG -D_GNU_SOURCE -DSYSCONF=\"/etc\" -DHAVE_GETTEXT -DPACKAGE=\"dctrl-tools\" -DLOCALEDIR=\"/usr/share/locale\"  -DVERSION=\"2.24\" -DMAINTAINER='"Antti-Juhani Kaijanaho <antti-juhani@kaijanaho.fi>"' -MD -MF tbl-dctrl/tbl-dctrl.d -c -o tbl-dctrl/tbl-dctrl.o tbl-dctrl/tbl-dctrl.c
GNUmakefile:133: update target 'tbl-dctrl/tbl-dctrl' due to: tbl-dctrl/tbl-dctrl.o libdctrl.a
gcc   -o tbl-dctrl/tbl-dctrl tbl-dctrl/tbl-dctrl.o libdctrl.a -L. -ldctrl -lintl -largp
GNUmakefile:136: update target 'join-dctrl/join-dctrl.o' due to: join-dctrl/join-dctrl.c
gcc   -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/build=/usr/src/debug/dctrl-tools-2.24-3-1 -fdebug-prefix-map=/mnt/dctrl-tools-2.24-3-1.i686/src=/usr/src/debug/dctrl-tools-2.24-3-1 -std=gnu99 -Ilib -DENABLE_L_DEBUG -D_GNU_SOURCE -DSYSCONF=\"/etc\" -DHAVE_GETTEXT -DPACKAGE=\"dctrl-tools\" -DLOCALEDIR=\"/usr/share/locale\"  -DVERSION=\"2.24\" -DMAINTAINER='"Antti-Juhani Kaijanaho <antti-juhani@kaijanaho.fi>"' -MD -MF join-dctrl/join-dctrl.d -c -o join-dctrl/join-dctrl.o join-dctrl/join-dctrl.c
GNUmakefile:133: update target 'join-dctrl/join-dctrl' due to: join-dctrl/join-dctrl.o libdctrl.a
gcc   -o join-dctrl/join-dctrl join-dctrl/join-dctrl.o libdctrl.a -L. -ldctrl -lintl -largp
GNUmakefile:164: update target 'po/ca.po' due to: po/dctrl-tools.pot
msgmerge --previous -q -U --backup=existing po/ca.po po/dctrl-tools.pot
GNUmakefile:167: update target 'po/ca.mo' due to: po/ca.po
msgfmt -c --statistics -o po/ca.mo po/ca.po 
100 translated messages, 2 fuzzy translations, 5 untranslated messages.
GNUmakefile:164: update target 'po/cs.po' due to: po/dctrl-tools.pot
msgmerge --previous -q -U --backup=existing po/cs.po po/dctrl-tools.pot
GNUmakefile:167: update target 'po/cs.mo' due to: po/cs.po
msgfmt -c --statistics -o po/cs.mo po/cs.po 
100 translated messages, 2 fuzzy translations, 5 untranslated messages.
GNUmakefile:164: update target 'po/da.po' due to: po/dctrl-tools.pot
msgmerge --previous -q -U --backup=existing po/da.po po/dctrl-tools.pot
GNUmakefile:167: update target 'po/da.mo' due to: po/da.po
msgfmt -c --statistics -o po/da.mo po/da.po 
100 translated messages, 2 fuzzy translations, 5 untranslated messages.
GNUmakefile:164: update target 'po/de.po' due to: po/dctrl-tools.pot
msgmerge --previous -q -U --backup=existing po/de.po po/dctrl-tools.pot
GNUmakefile:167: update target 'po/de.mo' due to: po/de.po
msgfmt -c --statistics -o po/de.mo po/de.po 
100 translated messages, 2 fuzzy translations, 5 untranslated messages.
GNUmakefile:164: update target 'po/es.po' due to: po/dctrl-tools.pot
msgmerge --previous -q -U --backup=existing po/es.po po/dctrl-tools.pot
GNUmakefile:167: update target 'po/es.mo' due to: po/es.po
msgfmt -c --statistics -o po/es.mo po/es.po 
100 translated messages, 2 fuzzy translations, 5 untranslated messages.
GNUmakefile:164: update target 'po/fi.po' due to: po/dctrl-tools.pot
msgmerge --previous -q -U --backup=existing po/fi.po po/dctrl-tools.pot
GNUmakefile:167: update target 'po/fi.mo' due to: po/fi.po
msgfmt -c --statistics -o po/fi.mo po/fi.po 
100 translated messages, 2 fuzzy translations, 5 untranslated messages.
GNUmakefile:164: update target 'po/fr.po' due to: po/dctrl-tools.pot
msgmerge --previous -q -U --backup=existing po/fr.po po/dctrl-tools.pot
GNUmakefile:167: update target 'po/fr.mo' due to: po/fr.po
msgfmt -c --statistics -o po/fr.mo po/fr.po 
100 translated messages, 2 fuzzy translations, 5 untranslated messages.
GNUmakefile:164: update target 'po/id.po' due to: po/dctrl-tools.pot
msgmerge --previous -q -U --backup=existing po/id.po po/dctrl-tools.pot
GNUmakefile:167: update target 'po/id.mo' due to: po/id.po
msgfmt -c --statistics -o po/id.mo po/id.po 
100 translated messages, 2 fuzzy translations, 5 untranslated messages.
GNUmakefile:164: update target 'po/it.po' due to: po/dctrl-tools.pot
msgmerge --previous -q -U --backup=existing po/it.po po/dctrl-tools.pot
GNUmakefile:167: update target 'po/it.mo' due to: po/it.po
msgfmt -c --statistics -o po/it.mo po/it.po 
35 translated messages, 23 fuzzy translations, 49 untranslated messages.
GNUmakefile:164: update target 'po/ja.po' due to: po/dctrl-tools.pot
msgmerge --previous -q -U --backup=existing po/ja.po po/dctrl-tools.pot
GNUmakefile:167: update target 'po/ja.mo' due to: po/ja.po
msgfmt -c --statistics -o po/ja.mo po/ja.po 
100 translated messages, 2 fuzzy translations, 5 untranslated messages.
GNUmakefile:164: update target 'po/pl.po' due to: po/dctrl-tools.pot
msgmerge --previous -q -U --backup=existing po/pl.po po/dctrl-tools.pot
GNUmakefile:167: update target 'po/pl.mo' due to: po/pl.po
msgfmt -c --statistics -o po/pl.mo po/pl.po 
msgfmt: po/pl.po: warning: PO file header fuzzy
                  warning: older versions of msgfmt will give an error on this
29 translated messages, 16 fuzzy translations, 62 untranslated messages.
GNUmakefile:164: update target 'po/pt.po' due to: po/dctrl-tools.pot
msgmerge --previous -q -U --backup=existing po/pt.po po/dctrl-tools.pot
GNUmakefile:167: update target 'po/pt.mo' due to: po/pt.po
msgfmt -c --statistics -o po/pt.mo po/pt.po 
100 translated messages, 2 fuzzy translations, 5 untranslated messages.
GNUmakefile:164: update target 'po/pt_BR.po' due to: po/dctrl-tools.pot
msgmerge --previous -q -U --backup=existing po/pt_BR.po po/dctrl-tools.pot
GNUmakefile:167: update target 'po/pt_BR.mo' due to: po/pt_BR.po
msgfmt -c --statistics -o po/pt_BR.mo po/pt_BR.po 
77 translated messages, 19 fuzzy translations, 11 untranslated messages.
GNUmakefile:164: update target 'po/ru.po' due to: po/dctrl-tools.pot
msgmerge --previous -q -U --backup=existing po/ru.po po/dctrl-tools.pot
GNUmakefile:167: update target 'po/ru.mo' due to: po/ru.po
msgfmt -c --statistics -o po/ru.mo po/ru.po 
100 translated messages, 2 fuzzy translations, 5 untranslated messages.
GNUmakefile:164: update target 'po/sv.po' due to: po/dctrl-tools.pot
msgmerge --previous -q -U --backup=existing po/sv.po po/dctrl-tools.pot
GNUmakefile:167: update target 'po/sv.mo' due to: po/sv.po
msgfmt -c --statistics -o po/sv.mo po/sv.po 
100 translated messages, 2 fuzzy translations, 5 untranslated messages.
GNUmakefile:164: update target 'po/vi.po' due to: po/dctrl-tools.pot
msgmerge --previous -q -U --backup=existing po/vi.po po/dctrl-tools.pot
GNUmakefile:167: update target 'po/vi.mo' due to: po/vi.po
msgfmt -c --statistics -o po/vi.mo po/vi.po 
100 translated messages, 2 fuzzy translations, 5 untranslated messages.
GNUmakefile:180: target 'po4a' does not exist
touch man/po4a/po/dctrl-tools-man.pot
po4a --no-backups man/po4a/po4a.cfg
Discard man/translated/de/grep-dctrl.1.cp (0 of 173 strings; only 0% translated; need 80%).
Discard man/translated/de/join-dctrl.1 (0 of 79 strings; only 0% translated; need 80%).
Discard man/translated/de/sort-dctrl.1 (0 of 55 strings; only 0% translated; need 80%).
Discard man/translated/de/sync-available.8 (0 of 27 strings; only 0% translated; need 80%).
Discard man/translated/de/tbl-dctrl.1 (0 of 75 strings; only 0% translated; need 80%).
Discard man/translated/fr/grep-dctrl.1.cp (0 of 173 strings; only 0% translated; need 80%).
Discard man/translated/fr/join-dctrl.1 (0 of 79 strings; only 0% translated; need 80%).
Discard man/translated/fr/sort-dctrl.1 (0 of 55 strings; only 0% translated; need 80%).
Discard man/translated/fr/sync-available.8 (0 of 27 strings; only 0% translated; need 80%).
Discard man/translated/fr/tbl-dctrl.1 (0 of 75 strings; only 0% translated; need 80%).
GNUmakefile:185: update target 'translated-man' due to: po4a
set -e ; for d in man/translated/*; do \
	if [ -e $d/grep-dctrl.1.cp ]; then \
		sed 's*SYSCONF*/etc*' \
		$d/grep-dctrl.1.cp > $d/grep-dctrl.1; \
	fi; \
       done
make[3]: Leaving directory '/mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools'
make[2]: Leaving directory '/mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools'
   dh_auto_test
   create-stamp debian/debhelper-build-stamp
   dh_testroot
   dh_prep
   debian/rules override_dh_auto_install
make[2]: Entering directory '/mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools'
debian/rules:19: target 'override_dh_auto_install' does not exist
dh_auto_install -- prefix=/usr sysconfdir=/etc
	make -j1 install DESTDIR=/mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools AM_UPDATE_INFO_DIR=no prefix=/usr sysconfdir=/etc
make[3]: Entering directory '/mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools'
GNUmakefile:62: target 'install' does not exist
install -d /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/sbin
install -d /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/bin
install -d /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/doc/dctrl-tools
install -d /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/man1
install -d /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/man8
install sync-available/sync-available /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/sbin
install join-dctrl/join-dctrl /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/bin
install tbl-dctrl/tbl-dctrl /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/bin
install sort-dctrl/sort-dctrl /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/bin
install grep-dctrl/grep-dctrl /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/bin
set -e ; for dest in grep-status grep-available grep-aptavail grep-debtags ; do \
	ln -s grep-dctrl /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/bin/$dest ; \
 done
install -m644 man/sync-available.8 /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/man8/
gzip -9 /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/man8/sync-available.8
install -m644 man/sort-dctrl.1 /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/man1/
gzip -9 /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/man1/sort-dctrl.1
install -m644 man/tbl-dctrl.1 /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/man1/
gzip -9 /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/man1/tbl-dctrl.1
install -m644 man/join-dctrl.1 /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/man1/
gzip -9 /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/man1/join-dctrl.1
install -m644 man/grep-dctrl.1 /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/man1/
gzip -9 /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/man1/grep-dctrl.1
set -e ; for dest in grep-status grep-available grep-aptavail grep-debtags ; do \
	ln -s grep-dctrl.1.gz /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/man1/$dest.1.gz ; \
done
set -e ; for d in man/translated/*; do \
	lang=`echo $d | cut -c16-`; \
	if [ -e $d/sync-available.8 ]; then \
		install -d /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/$lang/man8; \
		install -m644 $d/sync-available.8 /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/$lang/man8/; \
		gzip -9 /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/$lang/man8/sync-available.8; \
	fi; \
	for file in sort-dctrl.1 tbl-dctrl.1 join-dctrl.1 grep-dctrl.1; do \
		if [ -e $d/$file ]; then \
			if ! [ -d /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/$lang/man1 ]; then \
				install -d /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/$lang/man1; \
			fi; \
			install -m644 $d/$file /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/$lang/man1/; \
			gzip -9 /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/$lang/man1/$file; \
		fi; \
	done; \
	if [ -e /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/$lang/man1/grep-dctrl.1.gz ]; then \
		for dest in grep-status grep-available grep-aptavail grep-debtags ; do \
			ln -s grep-dctrl.1.gz /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/man/$lang/man1/$dest.1.gz ; \
		done; \
	fi; \
done;
install -m644 TODO README /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/doc/dctrl-tools
set -e ; for lang in ca cs da de es fi fr id it ja pl pt pt_BR ru sv vi ; do \
	install -d /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/locale/$lang/LC_MESSAGES ; \
	install -m644 po/$lang.mo \
	  /mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools/debian/dctrl-tools/usr/share/locale/$lang/LC_MESSAGES/dctrl-tools.mo ; \
done
make[3]: Leaving directory '/mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools'
make[2]: Leaving directory '/mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools'
   dh_installdocs
   dh_installchangelogs
   dh_installman
man: unrecognized option '--version'
Try 'man --help' or 'man --usage' for more information.
   dh_perl
   dh_link
   dh_strip_nondeterminism
   dh_compress
   dh_fixperms
   dh_missing
   dh_strip
   dh_makeshlibs
   dh_shlibdeps
   dh_installdeb
   dh_gencontrol
dpkg-gencontrol: warning: Depends field of package dctrl-tools: substitution variable ${shlibs:Depends} used, but is not defined
dpkg-gencontrol: warning: File::FcntlLock not available; using flock which is not NFS-safe
   dh_md5sums
   dh_builddeb
dpkg-deb: building package 'dctrl-tools' in '../dctrl-tools_2.24-3_i386.deb'.
make[1]: Leaving directory '/mnt/dctrl-tools-2.24-3-1.i686/build/dctrl-tools'
 dpkg-genbuildinfo
dpkg-genbuildinfo: warning: cannot open /var/lib/dpkg/status
readline() on closed filehandle $status_fh at /usr/bin/dpkg-genbuildinfo line 96.
dpkg-genbuildinfo: warning: File::FcntlLock not available; using flock which is not NFS-safe
 dpkg-genchanges  >../dctrl-tools_2.24-3_i386.changes
dpkg-genchanges: info: not including original source code in upload
 dpkg-source --auto-commit --after-build .
dpkg-buildpackage: info: binary and diff upload (original source NOT included)
[1;39m>>> Installing dctrl-tools-2.24-3-1.i686[0;0m
Fixing symlinks:
Compressing man pages:
        grep-debtags.1
        grep-status.1
        grep-available.1
        grep-aptavail.1
Stripping executables:
        usr/bin/grep-dctrl.exe
        usr/bin/join-dctrl.exe
        usr/bin/sort-dctrl.exe
        usr/bin/tbl-dctrl.exe
Preparing debuginfo source files:
	1 files	2 files	3 files	4 files	5 files	6 files	7 files	8 files	9 files	10 files	11 files	12 files	13 files	14 files	15 files	16 files	17 files	18 files	19 files	20 files
[1;39m>>> Packaging dctrl-tools-2.24-3-1.i686[0;0m
>>> Creating binary package(s)
>>> dctrl-tools-2.24-3-1.tar.xz
usr/
usr/lib/
usr/sbin/
usr/sbin/sync-available
usr/share/
usr/share/locale/
usr/share/locale/vi/
usr/share/locale/vi/LC_MESSAGES/
usr/share/locale/vi/LC_MESSAGES/dctrl-tools.mo
usr/share/locale/es/
usr/share/locale/es/LC_MESSAGES/
usr/share/locale/es/LC_MESSAGES/dctrl-tools.mo
usr/share/locale/de/
usr/share/locale/de/LC_MESSAGES/
usr/share/locale/de/LC_MESSAGES/dctrl-tools.mo
usr/share/locale/it/
usr/share/locale/it/LC_MESSAGES/
usr/share/locale/it/LC_MESSAGES/dctrl-tools.mo
usr/share/locale/fi/
usr/share/locale/fi/LC_MESSAGES/
usr/share/locale/fi/LC_MESSAGES/dctrl-tools.mo
usr/share/locale/pt_BR/
usr/share/locale/pt_BR/LC_MESSAGES/
usr/share/locale/pt_BR/LC_MESSAGES/dctrl-tools.mo
usr/share/locale/pl/
usr/share/locale/pl/LC_MESSAGES/
usr/share/locale/pl/LC_MESSAGES/dctrl-tools.mo
usr/share/locale/ja/
usr/share/locale/ja/LC_MESSAGES/
usr/share/locale/ja/LC_MESSAGES/dctrl-tools.mo
usr/share/locale/id/
usr/share/locale/id/LC_MESSAGES/
usr/share/locale/id/LC_MESSAGES/dctrl-tools.mo
usr/share/locale/ru/
usr/share/locale/ru/LC_MESSAGES/
usr/share/locale/ru/LC_MESSAGES/dctrl-tools.mo
usr/share/locale/cs/
usr/share/locale/cs/LC_MESSAGES/
usr/share/locale/cs/LC_MESSAGES/dctrl-tools.mo
usr/share/locale/sv/
usr/share/locale/sv/LC_MESSAGES/
usr/share/locale/sv/LC_MESSAGES/dctrl-tools.mo
usr/share/locale/ca/
usr/share/locale/ca/LC_MESSAGES/
usr/share/locale/ca/LC_MESSAGES/dctrl-tools.mo
usr/share/locale/da/
usr/share/locale/da/LC_MESSAGES/
usr/share/locale/da/LC_MESSAGES/dctrl-tools.mo
usr/share/locale/pt/
usr/share/locale/pt/LC_MESSAGES/
usr/share/locale/pt/LC_MESSAGES/dctrl-tools.mo
usr/share/locale/fr/
usr/share/locale/fr/LC_MESSAGES/
usr/share/locale/fr/LC_MESSAGES/dctrl-tools.mo
usr/share/doc/
usr/share/doc/dctrl-tools/
usr/share/doc/dctrl-tools/TODO
usr/share/doc/dctrl-tools/README
usr/share/doc/dctrl-tools/copyright
usr/share/doc/dctrl-tools/NEWS.Debian.gz
usr/share/doc/dctrl-tools/changelog.Debian.gz
usr/share/man/
usr/share/man/man1/
usr/share/man/man1/grep-aptavail.1.gz
usr/share/man/man1/grep-dctrl.1.gz
usr/share/man/man1/sort-dctrl.1.gz
usr/share/man/man1/grep-debtags.1.gz
usr/share/man/man1/join-dctrl.1.gz
usr/share/man/man1/tbl-dctrl.1.gz
usr/share/man/man1/grep-status.1.gz
usr/share/man/man1/grep-available.1.gz
usr/share/man/man8/
usr/share/man/man8/sync-available.8.gz
usr/bin/
usr/bin/grep-dctrl.exe
usr/bin/grep-aptavail
usr/bin/grep-status
usr/bin/grep-debtags
usr/bin/join-dctrl.exe
usr/bin/sort-dctrl.exe
usr/bin/tbl-dctrl.exe
usr/bin/grep-available

>>> dctrl-tools-debuginfo-2.24-3-1.tar.xz
usr/lib/debug/
usr/lib/debug/usr/
usr/lib/debug/usr/bin/
usr/lib/debug/usr/bin/tbl-dctrl.exe.dbg
usr/lib/debug/usr/bin/sort-dctrl.exe.dbg
usr/lib/debug/usr/bin/join-dctrl.exe.dbg
usr/lib/debug/usr/bin/grep-dctrl.exe.dbg
usr/src/debug/
usr/src/debug/dctrl-tools-2.24-3-1/
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/lib/
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/lib/predicate.c
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/lib/fsaf.h
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/lib/para_bundle.c
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/lib/strlist.c
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/lib/sorter.c
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/lib/atom.c
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/lib/util.c
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/lib/ifile.c
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/lib/version.c
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/lib/msg.h
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/lib/fsaf.c
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/lib/fnutil.c
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/lib/paragraph.c
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/lib/misc.c
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/lib/fieldtrie.c
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/lib/msg.c
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/sort-dctrl/
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/sort-dctrl/sort-dctrl.c
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/grep-dctrl/
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/grep-dctrl/grep-dctrl.c
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/tbl-dctrl/
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/tbl-dctrl/tbl-dctrl.c
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/join-dctrl/
usr/src/debug/dctrl-tools-2.24-3-1/dctrl-tools/join-dctrl/join-dctrl.c

>>> Checking packages for missing or duplicate files

>>> Creating source patches
 0 files changed
>>> Creating source package
dctrl-tools-2.24-3-1.src/
dctrl-tools-2.24-3-1.src/dctrl-tools_2.24-3.cygport
dctrl-tools-2.24-3-1.src/dctrl-tools.patch
dctrl-tools-2.24-3-1.src/dctrl-tools_2.24.orig.tar.gz
dctrl-tools-2.24-3-1.src/dctrl-tools_2.24-3.debian.tar.xz
dctrl-tools-2.24-3-1.src/dctrl-tools_2.24-3.dsc

which: no KERNEL32.dll in (/mnt/dctrl-tools-2.24-3-1.i686/inst/usr/bin:/usr/local/bin:/usr/bin:/bin:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/usr/lib/lapack:/cygdrive/c/WINDOWS/system32)
>>> dctrl-tools requires: bash cygwin libargp libintl8 libc6

Script done on Wed Apr 15 23:37:12 2020
