Script started on Thu Apr  9 03:21:19 2020
cygport --32 debhelper all
]0;/mnt
[32mAdministrator@- [33m/mnt[0m
$ cygport --32 debhelper all
[1;39m>>> Preparing debhelper.noarch[0;0m
>>> Unpacking source debhelper_12.1.1.dsc
>>> Unpacking source debhelper_12.1.1.tar.xz
[1;32m*** Info:[0;0m applying patch debhelper.patch (-p0):
patching file debhelper/dh_testroot
patching file debhelper/lib/Debian/Debhelper/Buildsystem.pm
Hunk #3 succeeded at 132 (offset -7 lines).
Hunk #4 succeeded at 153 (offset -7 lines).
patching file debhelper/lib/Debian/Debhelper/Dh_Lib.pm
Hunk #1 succeeded at 1474 (offset -2 lines).
Hunk #2 succeeded at 1490 (offset -2 lines).
patching file debhelper/t/buildsystems/03-bs-auto-buildable.t
patching file debhelper/t/buildsystems/buildsystem_tests.t
>>> Preparing working source directory
[1;39m>>> Compiling debhelper.noarch[0;0m
make: Entering directory '/mnt/debhelper.noarch/build/debhelper'
printf "package Debian::Debhelper::Dh_Version;\n\$version='12.1.1';\n1" > \
	lib/Debian/Debhelper/Dh_Version.pm
pod2man --utf8 -c Debhelper -r "12.1.1" dh_testroot dh_testroot.1
make: Leaving directory '/mnt/debhelper.noarch/build/debhelper'
[1;39m>>> Installing debhelper.noarch[0;0m
make: Entering directory '/mnt/debhelper.noarch/build/debhelper'
install -d /mnt/debhelper.noarch/inst/usr/bin \
	/mnt/debhelper.noarch/inst/usr/share/debhelper/autoscripts \
	/mnt/debhelper.noarch/inst/usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Sequence \
	/mnt/debhelper.noarch/inst/usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Buildsystem
install dh dh_auto_build dh_auto_clean dh_auto_configure dh_auto_install dh_auto_test dh_bugfiles dh_builddeb dh_clean dh_compress dh_dwz dh_fixperms dh_gconf dh_gencontrol dh_icons dh_install dh_installcatalogs dh_installchangelogs dh_installcron dh_installdeb dh_installdebconf dh_installdirs dh_installdocs dh_installemacsen dh_installexamples dh_installgsettings dh_installifupdown dh_installinfo dh_installinit dh_installinitramfs dh_installlogcheck dh_installlogrotate dh_installman dh_installmanpages dh_installmenu dh_installmime dh_installmodules dh_installpam dh_installppp dh_installsystemd dh_installsystemduser dh_installudev dh_installwm dh_installxfonts dh_link dh_lintian dh_listpackages dh_makeshlibs dh_md5sums dh_missing dh_movefiles dh_perl dh_prep dh_shlibdeps dh_strip dh_systemd_enable dh_systemd_start dh_testdir dh_testroot dh_ucf dh_update_autotools_config dh_usrlocal /mnt/debhelper.noarch/inst/usr/bin
install -m 0644 autoscripts/* /mnt/debhelper.noarch/inst/usr/share/debhelper/autoscripts
install -m 0644 lib/Debian/Debhelper/*.pm /mnt/debhelper.noarch/inst/usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper
[ "/usr" = /usr ] || \
	sed -i '/$prefix=/s@/usr@/usr@g' /mnt/debhelper.noarch/inst/usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Dh_Lib.pm
install -m 0644 lib/Debian/Debhelper/Sequence/*.pm /mnt/debhelper.noarch/inst/usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Sequence
install -m 0644 lib/Debian/Debhelper/Buildsystem/*.pm /mnt/debhelper.noarch/inst/usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Buildsystem
make: Leaving directory '/mnt/debhelper.noarch/build/debhelper'
Fixing symlinks:
Stripping executables:
Preparing debuginfo source files:

[1;32m*** Info:[0;0m Removing empty directory: /usr/share/doc/debhelper
[1;32m*** Info:[0;0m Removing empty directory: /usr/share/doc
[1;39m>>> Packaging debhelper.noarch[0;0m
>>> Creating binary package(s)
>>> debhelper-debhelper-debhelper.tar.xz
usr/
usr/lib/
usr/lib/perl5/
usr/lib/perl5/vendor_perl/
usr/lib/perl5/vendor_perl/5.22/
usr/lib/perl5/vendor_perl/5.22/Debian/
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Buildsystem.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Dh_Buildsystems.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Dh_Lib.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Dh_Getopt.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Buildsystem/
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Buildsystem/qmake.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Buildsystem/python_distutils.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Buildsystem/makefile.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Buildsystem/autoconf.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Buildsystem/cmake.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Buildsystem/meson.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Buildsystem/qmake_qt4.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Buildsystem/perl_makemaker.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Buildsystem/ninja.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Buildsystem/ant.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Buildsystem/perl_build.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Dh_Version.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Sequence/
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Sequence/python_support.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Sequence/systemd.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Sequence/installinitramfs.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Sequence/build_stamp.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/Sequence/dwz.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Debhelper/SequencerUtil.pm
usr/share/
usr/share/debhelper/
usr/share/debhelper/autoscripts/
usr/share/debhelper/autoscripts/postinst-usrlocal
usr/share/debhelper/autoscripts/postinst-init-restart
usr/share/debhelper/autoscripts/postrm-systemd
usr/share/debhelper/autoscripts/prerm-init
usr/share/debhelper/autoscripts/postinst-init
usr/share/debhelper/autoscripts/prerm-systemd-restart
usr/share/debhelper/autoscripts/postinst-systemd-user-dont-enable
usr/share/debhelper/autoscripts/postrm-systemd-reload-only
usr/share/debhelper/autoscripts/postinst-wm
usr/share/debhelper/autoscripts/postrm-init
usr/share/debhelper/autoscripts/prerm-emacsen
usr/share/debhelper/autoscripts/postinst-systemd-restartnostart
usr/share/debhelper/autoscripts/postinst-init-nostart
usr/share/debhelper/autoscripts/postrm-icons
usr/share/debhelper/autoscripts/postrm-sgmlcatalog
usr/share/debhelper/autoscripts/postinst-wm-noman
usr/share/debhelper/autoscripts/postinst-icons
usr/share/debhelper/autoscripts/postrm-systemd-user
usr/share/debhelper/autoscripts/postrm-menu-method
usr/share/debhelper/autoscripts/postrm-xfonts
usr/share/debhelper/autoscripts/postinst-init-tmpfiles
usr/share/debhelper/autoscripts/postinst-systemd-start
usr/share/debhelper/autoscripts/postrm-menu
usr/share/debhelper/autoscripts/postrm-debconf
usr/share/debhelper/autoscripts/prerm-wm
usr/share/debhelper/autoscripts/postinst-systemd-enable
usr/share/debhelper/autoscripts/postinst-ucf
usr/share/debhelper/autoscripts/postinst-initramfs-hook
usr/share/debhelper/autoscripts/postinst-systemd-user-enable
usr/share/debhelper/autoscripts/maintscript-helper
usr/share/debhelper/autoscripts/postinst-xfonts
usr/share/debhelper/autoscripts/postinst-menu-method
usr/share/debhelper/autoscripts/postinst-systemd-dont-enable
usr/share/debhelper/autoscripts/postinst-systemd-restart
usr/share/debhelper/autoscripts/preinst-emacsen
usr/share/debhelper/autoscripts/postrm-ucf
usr/share/debhelper/autoscripts/postinst-modules
usr/share/debhelper/autoscripts/postrm-initramfs-hook
usr/share/debhelper/autoscripts/postinst-emacsen
usr/share/debhelper/autoscripts/postrm-modules
usr/share/debhelper/autoscripts/prerm-usrlocal
usr/share/debhelper/autoscripts/prerm-systemd
usr/share/debhelper/autoscripts/prerm-init-norestart
usr/share/debhelper/autoscripts/postinst-menu
usr/bin/
usr/bin/dh_md5sums
usr/bin/dh_installdirs
usr/bin/dh_installexamples
usr/bin/dh_installlogrotate
usr/bin/dh_testroot
usr/bin/dh_installmanpages
usr/bin/dh_dwz
usr/bin/dh_testdir
usr/bin/dh_installgsettings
usr/bin/dh_auto_clean
usr/bin/dh_installmime
usr/bin/dh_clean
usr/bin/dh_installchangelogs
usr/bin/dh_installcron
usr/bin/dh_installwm
usr/bin/dh_icons
usr/bin/dh_usrlocal
usr/bin/dh_installmenu
usr/bin/dh_installlogcheck
usr/bin/dh_auto_build
usr/bin/dh_installppp
usr/bin/dh_update_autotools_config
usr/bin/dh_installinit
usr/bin/dh_link
usr/bin/dh_perl
usr/bin/dh_auto_install
usr/bin/dh_systemd_start
usr/bin/dh_fixperms
usr/bin/dh_installpam
usr/bin/dh_installmodules
usr/bin/dh_systemd_enable
usr/bin/dh_movefiles
usr/bin/dh
usr/bin/dh_ucf
usr/bin/dh_gconf
usr/bin/dh_bugfiles
usr/bin/dh_auto_configure
usr/bin/dh_prep
usr/bin/dh_compress
usr/bin/dh_installdeb
usr/bin/dh_installudev
usr/bin/dh_installman
usr/bin/dh_listpackages
usr/bin/dh_install
usr/bin/dh_missing
usr/bin/dh_installcatalogs
usr/bin/dh_installdocs
usr/bin/dh_installemacsen
usr/bin/dh_makeshlibs
usr/bin/dh_installinfo
usr/bin/dh_installinitramfs
usr/bin/dh_lintian
usr/bin/dh_shlibdeps
usr/bin/dh_strip
usr/bin/dh_installdebconf
usr/bin/dh_builddeb
usr/bin/dh_installsystemd
usr/bin/dh_installsystemduser
usr/bin/dh_auto_test
usr/bin/dh_installifupdown
usr/bin/dh_gencontrol
usr/bin/dh_installxfonts

[1;32m*** Info:[0;0m No debug files, skipping debuginfo subpackage

>>> Checking packages for missing or duplicate files

>>> Creating source patches
 0 files changed
>>> Creating source package
debhelper.src/
debhelper.src/debhelper.patch
debhelper.src/debhelper.cygport
debhelper.src/debhelper_12.1.1.dsc
debhelper.src/debhelper_12.1.1.tar.xz

>>> debhelper requires: debhelper-debhelper-debhelper perl-Carp perl-Digest-SHA perl_base autotools-dev dh-autoreconf dh-strip-nondeterminism dpkg dpkg-dev dwz file libdpkg-perl man-db po-debconf perl
]0;/mnt
[32mAdministrator@- [33m/mnt[0m
$ exit

Script done on Thu Apr  9 03:23:59 2020
