Script started on Thu Apr  9 13:37:37 2020
cygport --32 doc-base all
]0;/mnt
[32mAdministrator@- [33m/mnt[0m
$ cygport --32 doc-base all
[1;39m>>> Preparing doc-base.noarch[0;0m
>>> Unpacking source doc-base_0.10.8.dsc
>>> Unpacking source doc-base_0.10.8.tar.xz
gpgv: keyblock resource `/home/Administrator/.gnupg/trustedkeys.gpg': file open error
gpgv: Signature made Sun Feb 11 20:52:56 2018 CET using RSA key ID 3BE8AFD4
gpgv: Can't check signature: public key not found
[1mdpkg-source: [0m[1;33mwarning[0m: failed to verify signature on /mnt/doc-base_0.10.8.dsc
[1mdpkg-source: [0m[32minfo[0m: extracting doc-base in doc-base
[1mdpkg-source: [0m[32minfo[0m: unpacking doc-base_0.10.8.tar.xz
[1;32m*** Info:[0;0m applying patch doc-base.patch (-p0):
patching file doc-base/common.mk
patching file doc-base/perl/Debian/DocBase/DB.pm
patching file doc-base/perl/Debian/DocBase/DocBaseFile.pm
patching file doc-base/perl/Debian/DocBase/DocBaseFile.pm
patching file doc-base/perl/Debian/DocBase/InstallDocs.pm
>>> Preparing working source directory
[1;33m*** Warning:[0;0m Some build dependencies are not installed.
[1;33m*** Warning:[0;0m This package may end up missing features, or not build at all.
[1;33m*** Warning:[0;0m Consider installing these packages first before continuing:
[1;33m*** Warning:[0;0m     docbook-xml libxml2-utils xsltproc libuuid-perl libyaml-tiny-perl 
[1;39m>>> Compiling doc-base.noarch[0;0m
dpkg-buildpackage: info: source package doc-base
dpkg-buildpackage: info: source version 0.10.8
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Robert Luberda <robert@debian.org>
dpkg-architecture: warning: default GNU system type i686-linux-gnu for Debian arch i386 does not match specified GNU system type i686-pc-cygwin
 dpkg-source --auto-commit --before-build .
dpkg-buildpackage: info: host architecture i386
dpkg-source: warning: --auto-commit is not a valid option for Dpkg::Source::Package::V3::Native
dpkg-source: info: using options from doc-base/debian/source/options: --diff-ignore --tar-ignore
 debian/rules clean
dh clean
   dh_auto_clean
	make -j1 clean
make[1]: Entering directory '/mnt/doc-base.noarch/build/doc-base'
** Cleaning . ...
*** Cleaning ./doc ...
**** Cleaning ./po/bin ...
**** Cleaning ./po/pod ...
make[1]: Leaving directory '/mnt/doc-base.noarch/build/doc-base'
   dh_clean
 dpkg-source --auto-commit -b .
dpkg-source: warning: --auto-commit is not a valid option for Dpkg::Source::Package::V3::Native
dpkg-source: info: using options from doc-base/debian/source/options: --diff-ignore --tar-ignore
dpkg-source: info: using source format '3.0 (native)'
dpkg-source: info: building doc-base in doc-base_0.10.8.tar.xz
dpkg-source: info: building doc-base in doc-base_0.10.8.dsc
 debian/rules binary
dh binary
   debian/rules build
make[1]: Entering directory '/mnt/doc-base.noarch/build/doc-base'
dh build
   debian/rules build-arch
make[2]: Entering directory '/mnt/doc-base.noarch/build/doc-base'
make[2]: Nothing to be done for 'build-arch'.
make[2]: Leaving directory '/mnt/doc-base.noarch/build/doc-base'
   debian/rules build-indep
make[2]: Entering directory '/mnt/doc-base.noarch/build/doc-base'
dh build-indep
   dh_update_autotools_config -i
   dh_autoreconf -i
   dh_auto_configure -i
   dh_auto_build -i
	make -j1 "INSTALL=install --strip-program=true"
make[3]: Entering directory '/mnt/doc-base.noarch/build/doc-base'
**** Making ./_build ...
**** Making ./_build/install-docs ...
**** Making ./_build/man/man8/install-docs.8 ...
**** Making ./_build/install-docs.html ...
***** Making ./doc/_build ...
***** Making ./doc/_build/doc-base.xml ...
***** Making ./doc/_build/version.ent ...
***** Making ./doc/_build/check-stamp ...
***** Making ./doc/_build/doc-base.txt ...
***** Making ./doc/_build/doc-base.html/index.html ...
Writing doc-base.html/about.html for chapter(about)
Writing doc-base.html/interface.html for chapter(interface)
Writing doc-base.html/informations.html for chapter(informations)
Writing doc-base.html/todo.html for chapter(todo)
Writing doc-base.html/index.html for book
***** Making ./doc/_build/section.list ...
4b2897f1576349ed4029dd0347afb931295a9172 *_build/section.list
****** Making ./po/bin/doc-base.pot ...
****** Making ./po/bin/de.po ...
........... done.
****** Making ./po/bin/_build/de.mo ...
****** Making ./po/bin/es.po ...
........... done.
****** Making ./po/bin/_build/es.mo ...
****** Making ./po/bin/fr.po ...
........... done.
****** Making ./po/bin/_build/fr.mo ...
****** Making ./po/bin/ja.po ...
........... done.
****** Making ./po/bin/_build/ja.mo ...
****** Making ./po/bin/pl.po ...
........... done.
****** Making ./po/bin/_build/pl.mo ...
****** Making ./po/bin/sv.po ...
........... done.
****** Making ./po/bin/_build/sv.mo ...
****** Making ./po/pod/_build/stamp-po4a ...
Updating ../../po/pod/doc-base.pot:
 (74 entries)
Updating ../../po/pod/de.po: 
........ done.
../../po/pod/de.po: 74 translated messages.
Updating ../../po/pod/es.po: 
........ done.
../../po/pod/es.po: 74 translated messages.
Updating ../../po/pod/fr.po: 
........ done.
../../po/pod/fr.po: 74 translated messages.
Updating ../../po/pod/ja.po: 
........ done.
../../po/pod/ja.po: 74 translated messages.
Updating ../../po/pod/pl.po: 
........ done.
../../po/pod/pl.po: 74 translated messages.
_build/de/man8/install-docs.8.pod is 100% translated (77 strings).
_build/es/man8/install-docs.8.pod is 100% translated (77 strings).
_build/fr/man8/install-docs.8.pod is 100% translated (77 strings).
_build/ja/man8/install-docs.8.pod is 100% translated (77 strings).
_build/pl/man8/install-docs.8.pod is 100% translated (77 strings).
make[3]: Leaving directory '/mnt/doc-base.noarch/build/doc-base'
   dh_auto_test -i
   create-stamp debian/debhelper-build-stamp
make[2]: Leaving directory '/mnt/doc-base.noarch/build/doc-base'
make[1]: Leaving directory '/mnt/doc-base.noarch/build/doc-base'
   debian/rules binary-arch
make[1]: Entering directory '/mnt/doc-base.noarch/build/doc-base'
make[1]: Nothing to be done for 'binary-arch'.
make[1]: Leaving directory '/mnt/doc-base.noarch/build/doc-base'
   debian/rules binary-indep
make[1]: Entering directory '/mnt/doc-base.noarch/build/doc-base'
dh binary-indep
   dh_testroot -i
   dh_prep -i
   dh_installdirs -i
   dh_auto_install -i
	make -j1 install DESTDIR=/mnt/doc-base.noarch/build/doc-base/debian/doc-base AM_UPDATE_INFO_DIR=no "INSTALL=install --strip-program=true"
make[2]: Entering directory '/mnt/doc-base.noarch/build/doc-base'
*** Installing files from . ...
***   (DESTDIR=/mnt/doc-base.noarch/build/doc-base/debian/doc-base)
    installing script DESTDIR/usr/sbin/install-docs
    installing dir    DESTDIR/usr/share/omf
    installing dir    DESTDIR/var/lib/doc-base/omf
    installing dir    DESTDIR/var/lib/doc-base/info
    installing link   DESTDIR/usr/share/omf/doc-base
    installing file   DESTDIR/usr/share/man/man8/install-docs.8
    compressing file  DESTDIR/usr/share/man/man8/install-docs.8
    installing file   DESTDIR/usr/share/doc/doc-base/install-docs.html
**** Making ./doc/_build/doc-base.txt ...
**** Making ./doc/_build/doc-base.html/index.html ...
Writing doc-base.html/about.html for chapter(about)
Writing doc-base.html/interface.html for chapter(interface)
Writing doc-base.html/informations.html for chapter(informations)
Writing doc-base.html/todo.html for chapter(todo)
Writing doc-base.html/index.html for book
**** Installing files from ./doc ...
****   (DESTDIR=/mnt/doc-base.noarch/build/doc-base/debian/doc-base)
     installing file   DESTDIR/usr/share/doc/doc-base/version.ent
     installing file   DESTDIR/usr/share/doc/doc-base/doc-base.html/about.html
     installing file   DESTDIR/usr/share/doc/doc-base/doc-base.html/index.html
     installing file   DESTDIR/usr/share/doc/doc-base/doc-base.html/informations.html
     installing file   DESTDIR/usr/share/doc/doc-base/doc-base.html/interface.html
     installing file   DESTDIR/usr/share/doc/doc-base/doc-base.html/todo.html
     installing file   DESTDIR/usr/share/doc/doc-base/doc-base.xml
     compressing file  DESTDIR/usr/share/doc/doc-base/doc-base.xml
     installing file   DESTDIR/usr/share/doc/doc-base/doc-base.txt
     compressing file  DESTDIR/usr/share/doc/doc-base/doc-base.txt
     installing file   DESTDIR/usr/share/doc-base/data/section.list
**** Installing files from ./data ...
****   (DESTDIR=/mnt/doc-base.noarch/build/doc-base/debian/doc-base)
     installing file   DESTDIR/usr/share/doc-base/doc-base
     installing file   DESTDIR/usr/share/doc-base/install-docs-man
     installing file   DESTDIR/usr/share/doc-base/data/scrollkeeper.map
     installing file   DESTDIR/usr/share/doc-base/data/doc-base.map
     installing file   DESTDIR/etc/doc-base/documents/README
****** Installing files from ./perl/Debian/DocBase ...
******   (DESTDIR=/mnt/doc-base.noarch/build/doc-base/debian/doc-base)
       installing file   DESTDIR/usr/lib/perl5/site_perl/5.22//Debian/DocBase/Common.pm
       installing file   DESTDIR/usr/lib/perl5/site_perl/5.22//Debian/DocBase/DB.pm
       installing file   DESTDIR/usr/lib/perl5/site_perl/5.22//Debian/DocBase/DocBaseFile.pm
       installing file   DESTDIR/usr/lib/perl5/site_perl/5.22//Debian/DocBase/Document.pm
       installing file   DESTDIR/usr/lib/perl5/site_perl/5.22//Debian/DocBase/Gettext.pm
       installing file   DESTDIR/usr/lib/perl5/site_perl/5.22//Debian/DocBase/InstallDocs.pm
       installing file   DESTDIR/usr/lib/perl5/site_perl/5.22//Debian/DocBase/Utils.pm
******* Installing files from ./perl/Debian/DocBase/Programs ...
*******   (DESTDIR=/mnt/doc-base.noarch/build/doc-base/debian/doc-base)
        installing file   DESTDIR/usr/lib/perl5/site_perl/5.22//Debian/DocBase/Programs/Dhelp.pm
        installing file   DESTDIR/usr/lib/perl5/site_perl/5.22//Debian/DocBase/Programs/Dwww.pm
        installing file   DESTDIR/usr/lib/perl5/site_perl/5.22//Debian/DocBase/Programs/Scrollkeeper.pm
***** Making ./po/bin/_build/de.mo ...
***** Making ./po/bin/_build/es.mo ...
***** Making ./po/bin/_build/fr.mo ...
***** Making ./po/bin/_build/ja.mo ...
***** Making ./po/bin/_build/pl.mo ...
***** Making ./po/bin/_build/sv.mo ...
***** Installing files from ./po/bin ...
*****   (DESTDIR=/mnt/doc-base.noarch/build/doc-base/debian/doc-base)
      installing file   DESTDIR/usr/share/locale/de/LC_MESSAGES/doc-base.mo
      installing file   DESTDIR/usr/share/locale/es/LC_MESSAGES/doc-base.mo
      installing file   DESTDIR/usr/share/locale/fr/LC_MESSAGES/doc-base.mo
      installing file   DESTDIR/usr/share/locale/ja/LC_MESSAGES/doc-base.mo
      installing file   DESTDIR/usr/share/locale/pl/LC_MESSAGES/doc-base.mo
      installing file   DESTDIR/usr/share/locale/sv/LC_MESSAGES/doc-base.mo
***** Installing files from ./po/pod ...
*****   (DESTDIR=/mnt/doc-base.noarch/build/doc-base/debian/doc-base)
      installing file   DESTDIR/usr/share/man/de/man8/install-docs.8
      compressing file  DESTDIR/usr/share/man/de/man8/install-docs.8
      installing file   DESTDIR/usr/share/man/es/man8/install-docs.8
      compressing file  DESTDIR/usr/share/man/es/man8/install-docs.8
      installing file   DESTDIR/usr/share/man/fr/man8/install-docs.8
      compressing file  DESTDIR/usr/share/man/fr/man8/install-docs.8
      installing file   DESTDIR/usr/share/man/ja/man8/install-docs.8
      compressing file  DESTDIR/usr/share/man/ja/man8/install-docs.8
      installing file   DESTDIR/usr/share/man/pl/man8/install-docs.8
      compressing file  DESTDIR/usr/share/man/pl/man8/install-docs.8
make[2]: Leaving directory '/mnt/doc-base.noarch/build/doc-base'
   debian/rules override_dh_installdocs
make[2]: Entering directory '/mnt/doc-base.noarch/build/doc-base'
dh_installdocs -X doc-base.debhelper.log -X doc-base.substvars -X doc-base
make[2]: Leaving directory '/mnt/doc-base.noarch/build/doc-base'
   dh_installchangelogs -i
   dh_installman -i
man: unrecognized option '--version'
Try 'man --help' or 'man --usage' for more information.
   dh_lintian -i
   debian/rules override_dh_perl
make[2]: Entering directory '/mnt/doc-base.noarch/build/doc-base'
dh_perl -d
make[2]: Leaving directory '/mnt/doc-base.noarch/build/doc-base'
   dh_link -i
   dh_strip_nondeterminism -i
   dh_compress -i
   dh_fixperms -i
   dh_missing -i
   dh_installdeb -i
   dh_gencontrol -i
dpkg-gencontrol: warning: Depends field of package doc-base: substitution variable ${perl:Depends} used, but is not defined
dpkg-gencontrol: warning: File::FcntlLock not available; using flock which is not NFS-safe
   dh_md5sums -i
   dh_builddeb -i
dpkg-deb: building package 'doc-base' in '../doc-base_0.10.8_all.deb'.
make[1]: Leaving directory '/mnt/doc-base.noarch/build/doc-base'
 dpkg-genbuildinfo
dpkg-genbuildinfo: warning: cannot open /var/lib/dpkg/status
readline() on closed filehandle $status_fh at /usr/bin/dpkg-genbuildinfo line 96.
dpkg-genbuildinfo: warning: File::FcntlLock not available; using flock which is not NFS-safe
Use of uninitialized value $value in pattern match (m//) at /usr/share/perl5/Dpkg/Control/HashCore.pm line 358.
 dpkg-genchanges  >../doc-base_0.10.8_i386.changes
dpkg-genchanges: info: including full source code in upload
 dpkg-source --auto-commit --after-build .
dpkg-source: warning: --auto-commit is not a valid option for Dpkg::Source::Package::V3::Native
dpkg-source: info: using options from doc-base/debian/source/options: --diff-ignore --tar-ignore
dpkg-buildpackage: info: full upload; Debian-native package (full source is included)
[1;39m>>> Installing doc-base.noarch[0;0m
Fixing symlinks:
Compressing man pages:
[1;33m*** Warning:[0;0m vendor_perl should be used instead of site_perl; fixing
Stripping executables:
Preparing debuginfo source files:

[1;32m*** Info:[0;0m Removing empty directory: /var/lib/doc-base/omf
[1;32m*** Info:[0;0m Removing empty directory: /var/lib/doc-base/documents
[1;32m*** Info:[0;0m Removing empty directory: /var/lib/doc-base/info
[1;32m*** Info:[0;0m Removing empty directory: /var/lib/doc-base
[1;32m*** Info:[0;0m Removing empty directory: /var/lib
[1;32m*** Info:[0;0m Removing empty directory: /var
[1;39m>>> Packaging doc-base.noarch[0;0m
>>> Creating binary package(s)
>>> doc-base-doc-base-base.tar.xz
etc/
etc/doc-base/
etc/doc-base/documents/
etc/doc-base/documents/README
usr/
usr/lib/
usr/lib/perl5/
usr/lib/perl5/vendor_perl/
usr/lib/perl5/vendor_perl/5.22/
usr/lib/perl5/vendor_perl/5.22/Debian/
usr/lib/perl5/vendor_perl/5.22/Debian/DocBase/
usr/lib/perl5/vendor_perl/5.22/Debian/DocBase/Gettext.pm
usr/lib/perl5/vendor_perl/5.22/Debian/DocBase/DB.pm
usr/lib/perl5/vendor_perl/5.22/Debian/DocBase/Common.pm
usr/lib/perl5/vendor_perl/5.22/Debian/DocBase/InstallDocs.pm
usr/lib/perl5/vendor_perl/5.22/Debian/DocBase/Programs/
usr/lib/perl5/vendor_perl/5.22/Debian/DocBase/Programs/Dwww.pm
usr/lib/perl5/vendor_perl/5.22/Debian/DocBase/Programs/Scrollkeeper.pm
usr/lib/perl5/vendor_perl/5.22/Debian/DocBase/Programs/Dhelp.pm
usr/lib/perl5/vendor_perl/5.22/Debian/DocBase/Utils.pm
usr/lib/perl5/vendor_perl/5.22/Debian/DocBase/Document.pm
usr/lib/perl5/vendor_perl/5.22/Debian/DocBase/DocBaseFile.pm
usr/sbin/
usr/sbin/install-docs
usr/share/
usr/share/omf/
usr/share/omf/doc-base
usr/share/doc-base/
usr/share/doc-base/install-docs-man
usr/share/doc-base/doc-base
usr/share/doc-base/data/
usr/share/doc-base/data/doc-base.map
usr/share/doc-base/data/section.list
usr/share/doc-base/data/scrollkeeper.map
usr/share/locale/
usr/share/locale/es/
usr/share/locale/es/LC_MESSAGES/
usr/share/locale/es/LC_MESSAGES/doc-base.mo
usr/share/locale/de/
usr/share/locale/de/LC_MESSAGES/
usr/share/locale/de/LC_MESSAGES/doc-base.mo
usr/share/locale/pl/
usr/share/locale/pl/LC_MESSAGES/
usr/share/locale/pl/LC_MESSAGES/doc-base.mo
usr/share/locale/ja/
usr/share/locale/ja/LC_MESSAGES/
usr/share/locale/ja/LC_MESSAGES/doc-base.mo
usr/share/locale/sv/
usr/share/locale/sv/LC_MESSAGES/
usr/share/locale/sv/LC_MESSAGES/doc-base.mo
usr/share/locale/fr/
usr/share/locale/fr/LC_MESSAGES/
usr/share/locale/fr/LC_MESSAGES/doc-base.mo
usr/share/doc/
usr/share/doc/doc-base/
usr/share/doc/doc-base/changelog.gz
usr/share/doc/doc-base/install-docs.html
usr/share/doc/doc-base/doc-base.xml.gz
usr/share/doc/doc-base/version.ent
usr/share/doc/doc-base/doc-base.html/
usr/share/doc/doc-base/doc-base.html/informations.html
usr/share/doc/doc-base/doc-base.html/interface.html
usr/share/doc/doc-base/doc-base.html/todo.html
usr/share/doc/doc-base/doc-base.html/index.html
usr/share/doc/doc-base/doc-base.html/about.html
usr/share/doc/doc-base/copyright
usr/share/doc/doc-base/doc-base.txt.gz
usr/share/man/
usr/share/man/es/
usr/share/man/es/man8/
usr/share/man/es/man8/install-docs.8.gz
usr/share/man/de/
usr/share/man/de/man8/
usr/share/man/de/man8/install-docs.8.gz
usr/share/man/pl/
usr/share/man/pl/man8/
usr/share/man/pl/man8/install-docs.8.gz
usr/share/man/man8/
usr/share/man/man8/install-docs.8.gz
usr/share/man/ja/
usr/share/man/ja/man8/
usr/share/man/ja/man8/install-docs.8.gz
usr/share/man/fr/
usr/share/man/fr/man8/
usr/share/man/fr/man8/install-docs.8.gz
usr/share/lintian/
usr/share/lintian/overrides/
usr/share/lintian/overrides/doc-base

[1;32m*** Info:[0;0m No debug files, skipping debuginfo subpackage

>>> Checking packages for missing or duplicate files

>>> Creating source patches
 0 files changed
>>> Creating source package
doc-base.src/
doc-base.src/doc-base_0.10.8.tar.xz
doc-base.src/doc-base.cygport
doc-base.src/doc-base_0.10.8.dsc
doc-base.src/doc-base.patch

>>> doc-base requires: doc-base-doc-base-base perl-gettext perl-Scalar-List-Utils perl_base libuuid-perl libyaml-tiny-perl
]0;/mnt
[32mAdministrator@- [33m/mnt[0m
$ exit

Script done on Thu Apr  9 20:42:30 2020
