Script started on Tue Apr 14 21:00:46 2020
cygport --32 docx2txt all
]0;/mnt
[32mAdministrator@- [33m/mnt[0m
$ cygport --32 docx2txt all
[1;39m>>> Preparing docx2txt.noarch[0;0m
>>> Unpacking source docx2txt_1.4-1.dsc
>>> Unpacking source docx2txt_1.4.orig.tar.gz
>>> Unpacking source docx2txt_1.4-1.debian.tar.xz
gpgv: keyblock resource `/home/Administrator/.gnupg/trustedkeys.gpg': file open error
gpgv: Signature made Mon Oct  9 13:37:02 2017 CEST using RSA key ID 5E190D18
gpgv: Can't check signature: public key not found
[1mdpkg-source: [0m[1;33mwarning[0m: failed to verify signature on /mnt/docx2txt_1.4-1.dsc
[1mdpkg-source: [0m[32minfo[0m: extracting docx2txt in docx2txt
[1mdpkg-source: [0m[32minfo[0m: unpacking docx2txt_1.4.orig.tar.gz
[1mdpkg-source: [0m[32minfo[0m: unpacking docx2txt_1.4-1.debian.tar.xz
>>> Preparing working source directory
[1;39m>>> Compiling docx2txt.noarch[0;0m
dpkg-buildpackage: info: source package docx2txt
dpkg-buildpackage: info: source version 1.4-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Barak A. Pearlmutter <bap@debian.org>
dpkg-architecture: warning: default GNU system type i686-linux-gnu for Debian arch i386 does not match specified GNU system type i686-pc-cygwin
 dpkg-source --auto-commit --before-build .
dpkg-buildpackage: info: host architecture i386
 debian/rules clean
dh  clean
   dh_auto_clean
   dh_clean
	rm -f debian/debhelper-build-stamp
	rm -rf debian/.debhelper/
	rm -f -- debian/docx2txt.substvars debian/files
	rm -fr -- debian/docx2txt/ debian/tmp/
	find .  \( \( \
		\( -path .\*/.git -o -path .\*/.svn -o -path .\*/.bzr -o -path .\*/.hg -o -path .\*/CVS -o -path .\*/.pc -o -path .\*/_darcs \) -prune -o -type f -a \
	        \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
		 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
		 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
		 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
		\) -exec rm -f {} + \) -o \
		\( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \)
 dpkg-source --auto-commit -b .
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building docx2txt using existing ./docx2txt_1.4.orig.tar.gz
dpkg-source: info: building docx2txt in docx2txt_1.4-1.debian.tar.xz
dpkg-source: info: building docx2txt in docx2txt_1.4-1.dsc
 debian/rules binary
dh  binary
   dh_update_autotools_config
   dh_autoreconf
   dh_auto_configure
   dh_auto_test
   create-stamp debian/debhelper-build-stamp
   dh_testroot
   dh_prep
	rm -f -- debian/docx2txt.substvars
	rm -fr -- debian/.debhelper/generated/docx2txt/ debian/docx2txt/ debian/tmp/
   dh_installdirs
	install -d debian/docx2txt
	install -d debian/docx2txt/usr/bin
   debian/rules override_dh_auto_install
make[1]: Entering directory '/mnt/docx2txt.noarch/build/docx2txt'
cp /mnt/docx2txt.noarch/build/docx2txt/docx2txt.pl /mnt/docx2txt.noarch/build/docx2txt/debian/docx2txt/usr/bin/docx2txt
make[1]: Leaving directory '/mnt/docx2txt.noarch/build/docx2txt'
   dh_installdocs
	install -d debian/docx2txt/usr/share/doc/docx2txt
	install -d debian/.debhelper/generated/docx2txt
	cp --reflink=auto -a ./README debian/docx2txt/usr/share/doc/docx2txt
	cp --reflink=auto -a ./ToDo debian/docx2txt/usr/share/doc/docx2txt
	chmod -R u\+rw,go=rX debian/docx2txt/usr/share/doc
	install -p -m0644 debian/copyright debian/docx2txt/usr/share/doc/docx2txt/copyright
   dh_installchangelogs
	install -p -m0644 debian/changelog debian/docx2txt/usr/share/doc/docx2txt/changelog.Debian
	install -p -m0644 ./ChangeLog debian/docx2txt/usr/share/doc/docx2txt/changelog
   dh_installman
	install -d debian/docx2txt/usr/share/man/man1/
	install -p -m0644 ./debian/docx2txt.1 debian/docx2txt/usr/share/man/man1/docx2txt.1
man: unrecognized option '--version'
Try 'man --help' or 'man --usage' for more information.
	man -l --recode UTF-8 ./debian/docx2txt/usr/share/man/man1/docx2txt.1 > debian/docx2txt/usr/share/man/man1/docx2txt.1.dh-new
	mv debian/docx2txt/usr/share/man/man1/docx2txt.1.dh-new debian/docx2txt/usr/share/man/man1/docx2txt.1
	chmod 0644 -- debian/docx2txt/usr/share/man/man1/docx2txt.1
   dh_installmime
	install -d debian/docx2txt/usr/lib/mime/packages
	install -p -m0644 debian/docx2txt.mime debian/docx2txt/usr/lib/mime/packages/docx2txt
   dh_perl
	(grep -a -s -v perl:Depends debian/docx2txt.substvars; echo perl:Depends=perl:any) > debian/docx2txt.substvars.new
	mv debian/docx2txt.substvars.new debian/docx2txt.substvars
   dh_link
   dh_strip_nondeterminism
   dh_compress
	cd debian/docx2txt
	chmod a-x usr/share/doc/docx2txt/README usr/share/doc/docx2txt/changelog usr/share/doc/docx2txt/changelog.Debian usr/share/man/man1/docx2txt.1
	gzip -9nf usr/share/doc/docx2txt/README usr/share/doc/docx2txt/changelog usr/share/doc/docx2txt/changelog.Debian usr/share/man/man1/docx2txt.1
	cd '/mnt/docx2txt.noarch/build/docx2txt'
   dh_fixperms
	find debian/docx2txt ! -type l -a -true -a -true -print0 2>/dev/null | xargs -0r chmod go=rX,u+rw,a-s
	find debian/docx2txt/usr/share/doc -type f -a -true -a ! -regex 'debian/docx2txt/usr/share/doc/[^/]*/examples/.*' -print0 2>/dev/null | xargs -0r chmod 0644
	find debian/docx2txt/usr/share/doc -type d -a -true -a -true -print0 2>/dev/null | xargs -0r chmod 0755
	find debian/docx2txt/usr/share/man -type f -a -true -a -true -print0 2>/dev/null | xargs -0r chmod 0644
	find debian/docx2txt -type f \( -name '*.so.*' -o -name '*.so' -o -name '*.la' -o -name '*.a' -o -name '*.js' -o -name '*.css' -o -name '*.scss' -o -name '*.sass' -o -name '*.jpeg' -o -name '*.jpg' -o -name '*.png' -o -name '*.gif' -o -name '*.cmxs' -o -name '*.node' \) -a -true -a -true -print0 2>/dev/null | xargs -0r chmod 0644
	find debian/docx2txt/usr/bin -type f -a -true -a -true -print0 2>/dev/null | xargs -0r chmod a+x
	find debian/docx2txt/usr/lib -type f -name '*.ali' -a -true -a -true -print0 2>/dev/null | xargs -0r chmod uga-w
   dh_missing
   dh_installdeb
	install -d debian/docx2txt/DEBIAN
   dh_gencontrol
	echo misc:Depends= >> debian/docx2txt.substvars
	echo misc:Pre-Depends= >> debian/docx2txt.substvars
	dpkg-gencontrol -pdocx2txt -ldebian/changelog -Tdebian/docx2txt.substvars -Pdebian/docx2txt
dpkg-gencontrol: warning: Depends field of package docx2txt: substitution variable ${shlibs:Depends} used, but is not defined
dpkg-gencontrol: warning: File::FcntlLock not available; using flock which is not NFS-safe
dpkg-gencontrol: warning: package docx2txt: substitution variable ${perl:Depends} unused, but is defined
	chmod 0644 -- debian/docx2txt/DEBIAN/control
   dh_md5sums
	cd debian/docx2txt >/dev/null && xargs -r0 md5sum | perl -pe 'if (s@^\\@@) { s/\\\\/\\/g; }' > DEBIAN/md5sums
	chmod 0644 -- debian/docx2txt/DEBIAN/md5sums
   dh_builddeb
	dpkg-deb --root-owner-group --build debian/docx2txt ..
dpkg-deb: building package 'docx2txt' in '../docx2txt_1.4-1_all.deb'.
 dpkg-genbuildinfo
dpkg-genbuildinfo: warning: cannot open /var/lib/dpkg/status
readline() on closed filehandle $status_fh at /usr/bin/dpkg-genbuildinfo line 96.
dpkg-genbuildinfo: warning: File::FcntlLock not available; using flock which is not NFS-safe
 dpkg-genchanges  >../docx2txt_1.4-1_i386.changes
dpkg-genchanges: info: not including original source code in upload
 dpkg-source --auto-commit --after-build .
dpkg-buildpackage: info: binary and diff upload (original source NOT included)
[1;39m>>> Installing docx2txt.noarch[0;0m
Fixing symlinks:
Compressing man pages:
Stripping executables:
Preparing debuginfo source files:

[1;39m>>> Packaging docx2txt.noarch[0;0m
>>> Creating binary package(s)
>>> docx2txt-docx2txt-docx2txt.tar.xz
usr/
usr/lib/
usr/lib/mime/
usr/lib/mime/packages/
usr/lib/mime/packages/docx2txt
usr/share/
usr/share/doc/
usr/share/doc/docx2txt/
usr/share/doc/docx2txt/changelog.gz
usr/share/doc/docx2txt/README.gz
usr/share/doc/docx2txt/copyright
usr/share/doc/docx2txt/changelog.Debian.gz
usr/share/doc/docx2txt/ToDo
usr/share/man/
usr/share/man/man1/
usr/share/man/man1/docx2txt.1.gz
usr/bin/
usr/bin/docx2txt

[1;32m*** Info:[0;0m No debug files, skipping debuginfo subpackage

>>> Checking packages for missing or duplicate files

>>> Creating source patches
 0 files changed
>>> Creating source package
docx2txt.src/
docx2txt.src/docx2txt.cygport
docx2txt.src/docx2txt_1.4-1.debian.tar.xz
docx2txt.src/docx2txt_1.4.orig.tar.gz
docx2txt.src/docx2txt_1.4-1.dsc

>>> docx2txt requires: perl_base unzip
]0;/mnt
[32mAdministrator@- [33m/mnt[0m
$ exit

Script done on Tue Apr 14 21:03:07 2020
