Script started on Mon Apr 13 04:35:00 2020
cygport --32 dwww all
]0;/mnt
[32mAdministrator@- [33m/mnt[0m
$ cygport --32 dwww all
[1;39m>>> Preparing dwww.i686[0;0m
>>> Unpacking source dwww_1.13.4+nmu3.dsc
>>> Unpacking source dwww_1.13.4+nmu3.tar.xz
gpgv: keyblock resource `/home/Administrator/.gnupg/trustedkeys.gpg': file open error
gpgv: Signature made Mon Mar 25 16:49:30 2019 CET using RSA key ID 1DD8D791
gpgv: Can't check signature: public key not found
[1mdpkg-source: [0m[1;33mwarning[0m: failed to verify signature on /mnt/dwww_1.13.4+nmu3.dsc
[1mdpkg-source: [0m[32minfo[0m: extracting dwww in dwww
[1mdpkg-source: [0m[32minfo[0m: unpacking dwww_1.13.4+nmu3.tar.xz
[1;32m*** Info:[0;0m applying patch dwww.patch (-p0):
patching file dwww/common.mk
patching file dwww/data/Makefile
patching file dwww/data/apache.conf
patching file dwww/data/dwww.css.in
patching file dwww/data/img/Makefile
patching file dwww/data/img/default.svg
patching file dwww/data/swish++.conf
patching file dwww/data/templates/dwww.template
patching file dwww/debian/rules
patching file dwww/perl/Debian/Dwww/Common.pm
patching file dwww/perl/Debian/Dwww/Utils.pm
patching file dwww/scripts/dwww-build
patching file dwww/scripts/dwww-build-menu
patching file dwww/scripts/dwww-find
patching file dwww/scripts/dwww-index++
patching file dwww/scripts/dwww.cgi
patching file dwww/src/dwww-txt2html.c
>>> Preparing working source directory
[1;39m>>> Compiling dwww.i686[0;0m
dpkg-buildpackage: info: source package dwww
dpkg-buildpackage: info: source version 1.13.4+nmu3
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Osamu Aoki <osamu@debian.org>
dpkg-architecture: warning: default GNU system type i686-linux-gnu for Debian arch i386 does not match specified GNU system type i686-pc-cygwin
 dpkg-source --auto-commit --before-build .
dpkg-buildpackage: info: host architecture i386
dpkg-source: warning: --auto-commit is not a valid option for Dpkg::Source::Package::V3::Native
dpkg-source: info: using options from dwww/debian/source/options: --diff-ignore --tar-ignore
 debian/rules clean
dh "clean"
   dh_auto_clean
	make -j1 clean
make[1]: Entering directory '/mnt/dwww.i686/build/dwww'
getconf: Unrecognized variable `LFS_CFLAGS'
removing /mnt/dwww.i686/build/dwww/data/_build
removing /mnt/dwww.i686/build/dwww/perl/Debian/Dwww/_build
removing /mnt/dwww.i686/build/dwww/scripts/_build
removing /mnt/dwww.i686/build/dwww/src/_build
make[1]: Leaving directory '/mnt/dwww.i686/build/dwww'
   dh_clean
	rm -f debian/debhelper-build-stamp
	rm -rf debian/.debhelper/
	rm -f -- debian/dwww.substvars debian/files
	rm -fr -- debian/dwww/ debian/tmp/
	find .  \( \( \
		\( -path .\*/.git -o -path .\*/.svn -o -path .\*/.bzr -o -path .\*/.hg -o -path .\*/CVS -o -path .\*/.pc -o -path .\*/_darcs \) -prune -o -type f -a \
	        \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
		 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
		 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
		 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
		\) -exec rm -f {} + \) -o \
		\( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \)
 dpkg-source --auto-commit -b .
dpkg-source: warning: --auto-commit is not a valid option for Dpkg::Source::Package::V3::Native
dpkg-source: info: using options from dwww/debian/source/options: --diff-ignore --tar-ignore
dpkg-source: info: using source format '3.0 (native)'
dpkg-source: info: building dwww in dwww_1.13.4+nmu3.tar.xz
dpkg-source: info: building dwww in dwww_1.13.4+nmu3.dsc
 debian/rules binary
dh "binary"
   dh_update_autotools_config
   dh_autoreconf
   dh_auto_configure
   dh_auto_build
	make -j1
make[1]: Entering directory '/mnt/dwww.i686/build/dwww'
getconf: Unrecognized variable `LFS_CFLAGS'
creating /mnt/dwww.i686/build/dwww/data/_build/dwww.css
creating /mnt/dwww.i686/build/dwww/perl/Debian/Dwww/_build/Version.pm
creating /mnt/dwww.i686/build/dwww/scripts/_build/functions.sh
gcc -c  -DVERSION='"1.13.4+nmu3"' -DMAXINT=INT_MAX -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dwww.i686/build=/usr/src/debug/dwww -fdebug-prefix-map=/mnt/dwww.i686/src=/usr/src/debug/dwww -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -Werror -g  -o _build/dwww-cache.o dwww-cache.c
gcc -c  -DVERSION='"1.13.4+nmu3"' -DMAXINT=INT_MAX -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dwww.i686/build=/usr/src/debug/dwww -fdebug-prefix-map=/mnt/dwww.i686/src=/usr/src/debug/dwww -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -Werror -g  -o _build/utils.o utils.c
gcc  -L /usr/lib/i386-linux-gnu -o _build/dwww-cache _build/dwww-cache.o _build/utils.o  -lpub
gcc -c  -DVERSION='"1.13.4+nmu3"' -DMAXINT=INT_MAX -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dwww.i686/build=/usr/src/debug/dwww -fdebug-prefix-map=/mnt/dwww.i686/src=/usr/src/debug/dwww -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -Werror -g  -o _build/dwww-quickfind.o dwww-quickfind.c
gcc  -L /usr/lib/i386-linux-gnu -o _build/dwww-quickfind _build/dwww-quickfind.o _build/utils.o  -lpub
gcc -c  -DVERSION='"1.13.4+nmu3"' -DMAXINT=INT_MAX -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/dwww.i686/build=/usr/src/debug/dwww -fdebug-prefix-map=/mnt/dwww.i686/src=/usr/src/debug/dwww -Wall -Wextra -Wstrict-prototypes -Wmissing-prototypes -Werror -g  -o _build/dwww-txt2html.o dwww-txt2html.c
gcc  -L /usr/lib/i386-linux-gnu -o _build/dwww-txt2html _build/dwww-txt2html.o _build/utils.o  -lpub
make[1]: Leaving directory '/mnt/dwww.i686/build/dwww'
   dh_auto_test
   create-stamp debian/debhelper-build-stamp
   dh_testroot
   dh_prep
	rm -f -- debian/dwww.substvars
	rm -fr -- debian/.debhelper/generated/dwww/ debian/dwww/ debian/tmp/
   dh_installdirs
	install -d debian/dwww
	install -d debian/dwww/etc/dwww debian/dwww/var/cache/dwww/db debian/dwww/var/lib/dwww/
   dh_auto_install
	make -j1 install DESTDIR=/mnt/dwww.i686/build/dwww/debian/dwww AM_UPDATE_INFO_DIR=no
make[1]: Entering directory '/mnt/dwww.i686/build/dwww'
getconf: Unrecognized variable `LFS_CFLAGS'
installing file   [DESTDIR]/usr/share/doc/dwww/README
installing file   [DESTDIR]/usr/share/doc/dwww/TODO
installing dir    [DESTDIR]/var/lib/dwww
installing dir    [DESTDIR]/srv/www/htdocs
installing dir    [DESTDIR]/var/cache/dwww
getconf: Unrecognized variable `LFS_CFLAGS'
installing file   [DESTDIR]/usr/share/dwww/dwww.css
installing file   [DESTDIR]/usr/share/dwww/swish++.conf
installing file   [DESTDIR]/etc/httpd/conf.d/dwww.conf
installing file   [DESTDIR]/usr/share/applications/dwww.desktop
convert default.svg default.png
installing file   [DESTDIR]/usr/share/dwww/default.png
installing file   [DESTDIR]/usr/share/pixmaps/dwww-gnome-touristinfo.png
installing file   [DESTDIR]/usr/share/firefox-esr/distribution/searchplugins/common/dwww.xml
installing file   [DESTDIR]/usr/share/firefox/distribution/searchplugins/common/dwww.xml
installing file   [DESTDIR]/usr/share/dwww/templates/dwww-convert.dir.start
installing file   [DESTDIR]/usr/share/dwww/templates/dwww-convert.start
installing file   [DESTDIR]/usr/share/dwww/templates/dwww-find.start
installing file   [DESTDIR]/usr/share/dwww/templates/dwww.end
installing file   [DESTDIR]/usr/share/dwww/templates/dwww.template
installing file   [DESTDIR]/usr/share/dwww/templates/man-begins-with.end
installing file   [DESTDIR]/usr/share/dwww/templates/man-begins-with.start
installing file   [DESTDIR]/usr/share/dwww/templates/man-in-section.end
installing file   [DESTDIR]/usr/share/dwww/templates/man-in-section.start
installing file   [DESTDIR]/usr/share/dwww/templates/man-index.end
installing file   [DESTDIR]/usr/share/dwww/templates/man-index.start
installing file   [DESTDIR]/usr/share/dwww/templates/menu.all.start
installing file   [DESTDIR]/usr/share/dwww/templates/menu.end
installing file   [DESTDIR]/usr/share/dwww/templates/menu.errors.end
installing file   [DESTDIR]/usr/share/dwww/templates/menu.errors.start
installing file   [DESTDIR]/usr/share/dwww/templates/menu.nosections
installing file   [DESTDIR]/usr/share/dwww/templates/menu.single.start
installing link   [DESTDIR]/usr/share/dwww/templates/dwww-convert.dir.end
installing link   [DESTDIR]/usr/share/dwww/templates/dwww-convert.end
installing link   [DESTDIR]/usr/share/dwww/templates/dwww-find.end
installing file   [DESTDIR]/usr/share/man/man1/dwww.1
compressing file  [DESTDIR]/usr/share/man/man1/dwww.1
installing file   [DESTDIR]/usr/share/man/man7/dwww.7
compressing file  [DESTDIR]/usr/share/man/man7/dwww.7
installing file   [DESTDIR]/usr/share/man/man8/dwww-build-menu.8
compressing file  [DESTDIR]/usr/share/man/man8/dwww-build-menu.8
installing file   [DESTDIR]/usr/share/man/man8/dwww-build.8
compressing file  [DESTDIR]/usr/share/man/man8/dwww-build.8
installing file   [DESTDIR]/usr/share/man/man8/dwww-cache.8
compressing file  [DESTDIR]/usr/share/man/man8/dwww-cache.8
installing file   [DESTDIR]/usr/share/man/man8/dwww-convert.8
compressing file  [DESTDIR]/usr/share/man/man8/dwww-convert.8
installing file   [DESTDIR]/usr/share/man/man8/dwww-find.8
compressing file  [DESTDIR]/usr/share/man/man8/dwww-find.8
installing file   [DESTDIR]/usr/share/man/man8/dwww-format-man.8
compressing file  [DESTDIR]/usr/share/man/man8/dwww-format-man.8
installing file   [DESTDIR]/usr/share/man/man8/dwww-index++.8
compressing file  [DESTDIR]/usr/share/man/man8/dwww-index++.8
installing file   [DESTDIR]/usr/share/man/man8/dwww-quickfind.8
compressing file  [DESTDIR]/usr/share/man/man8/dwww-quickfind.8
installing file   [DESTDIR]/usr/share/man/man8/dwww-refresh-cache.8
compressing file  [DESTDIR]/usr/share/man/man8/dwww-refresh-cache.8
installing file   [DESTDIR]/usr/share/man/man8/dwww-txt2html.8
compressing file  [DESTDIR]/usr/share/man/man8/dwww-txt2html.8
installing link   [DESTDIR]/usr/share/man/man5/dwww.conf.5.gz
installing file   [DESTDIR]/usr/lib/perl5/site_perl/5.22//Debian/Dwww/Common.pm
installing file   [DESTDIR]/usr/lib/perl5/site_perl/5.22//Debian/Dwww/ConfigFile.pm
installing file   [DESTDIR]/usr/lib/perl5/site_perl/5.22//Debian/Dwww/DocBase.pm
installing file   [DESTDIR]/usr/lib/perl5/site_perl/5.22//Debian/Dwww/Initialize.pm
installing file   [DESTDIR]/usr/lib/perl5/site_perl/5.22//Debian/Dwww/Utils.pm
installing file   [DESTDIR]/usr/lib/perl5/site_perl/5.22//Debian/Dwww/Version.pm
installing script [DESTDIR]/usr/sbin/dwww-build
installing script [DESTDIR]/usr/sbin/dwww-build-menu
installing script [DESTDIR]/usr/sbin/dwww-convert
installing script [DESTDIR]/usr/sbin/dwww-find
installing script [DESTDIR]/usr/sbin/dwww-format-man
installing script [DESTDIR]/usr/sbin/dwww-index++
installing script [DESTDIR]/usr/sbin/dwww-refresh-cache
installing script [DESTDIR]/usr/bin/dwww
installing script [DESTDIR]/srv/www/cgi-bin/dwww
installing file   [DESTDIR]/usr/share/dwww/functions.sh
installing script [DESTDIR]/usr/sbin/dwww-cache
installing script [DESTDIR]/usr/sbin/dwww-quickfind
installing script [DESTDIR]/usr/sbin/dwww-txt2html
make[1]: Leaving directory '/mnt/dwww.i686/build/dwww'
   dh_installdocs
	install -d debian/.debhelper/generated/dwww
	install -p -m0644 debian/copyright debian/dwww/usr/share/doc/dwww/copyright
   dh_installchangelogs
	install -p -m0644 debian/changelog debian/dwww/usr/share/doc/dwww/changelog
	install -p -m0644 debian/NEWS debian/dwww/usr/share/doc/dwww/NEWS.Debian
   dh_installman
man: unrecognized option '--version'
Try 'man --help' or 'man --usage' for more information.
	man -l --recode UTF-8 ./debian/dwww/usr/share/man/man7/dwww.7.gz > debian/dwww/usr/share/man/man7/dwww.7.gz.dh-new
	rm -f debian/dwww/usr/share/man/man7/dwww.7.gz
	mv debian/dwww/usr/share/man/man7/dwww.7.gz.dh-new debian/dwww/usr/share/man/man7/dwww.7
	man -l --recode UTF-8 ./debian/dwww/usr/share/man/man1/dwww.1.gz > debian/dwww/usr/share/man/man1/dwww.1.gz.dh-new
	rm -f debian/dwww/usr/share/man/man1/dwww.1.gz
	mv debian/dwww/usr/share/man/man1/dwww.1.gz.dh-new debian/dwww/usr/share/man/man1/dwww.1
	man -l --recode UTF-8 ./debian/dwww/usr/share/man/man8/dwww-index\+\+.8.gz > debian/dwww/usr/share/man/man8/dwww-index\+\+.8.gz.dh-new
	rm -f debian/dwww/usr/share/man/man8/dwww-index\+\+.8.gz
	mv debian/dwww/usr/share/man/man8/dwww-index\+\+.8.gz.dh-new debian/dwww/usr/share/man/man8/dwww-index\+\+.8
	man -l --recode UTF-8 ./debian/dwww/usr/share/man/man8/dwww-find.8.gz > debian/dwww/usr/share/man/man8/dwww-find.8.gz.dh-new
	rm -f debian/dwww/usr/share/man/man8/dwww-find.8.gz
	mv debian/dwww/usr/share/man/man8/dwww-find.8.gz.dh-new debian/dwww/usr/share/man/man8/dwww-find.8
	man -l --recode UTF-8 ./debian/dwww/usr/share/man/man8/dwww-convert.8.gz > debian/dwww/usr/share/man/man8/dwww-convert.8.gz.dh-new
	rm -f debian/dwww/usr/share/man/man8/dwww-convert.8.gz
	mv debian/dwww/usr/share/man/man8/dwww-convert.8.gz.dh-new debian/dwww/usr/share/man/man8/dwww-convert.8
	man -l --recode UTF-8 ./debian/dwww/usr/share/man/man8/dwww-quickfind.8.gz > debian/dwww/usr/share/man/man8/dwww-quickfind.8.gz.dh-new
	rm -f debian/dwww/usr/share/man/man8/dwww-quickfind.8.gz
	mv debian/dwww/usr/share/man/man8/dwww-quickfind.8.gz.dh-new debian/dwww/usr/share/man/man8/dwww-quickfind.8
	man -l --recode UTF-8 ./debian/dwww/usr/share/man/man8/dwww-format-man.8.gz > debian/dwww/usr/share/man/man8/dwww-format-man.8.gz.dh-new
	rm -f debian/dwww/usr/share/man/man8/dwww-format-man.8.gz
	mv debian/dwww/usr/share/man/man8/dwww-format-man.8.gz.dh-new debian/dwww/usr/share/man/man8/dwww-format-man.8
	man -l --recode UTF-8 ./debian/dwww/usr/share/man/man8/dwww-build.8.gz > debian/dwww/usr/share/man/man8/dwww-build.8.gz.dh-new
	rm -f debian/dwww/usr/share/man/man8/dwww-build.8.gz
	mv debian/dwww/usr/share/man/man8/dwww-build.8.gz.dh-new debian/dwww/usr/share/man/man8/dwww-build.8
	man -l --recode UTF-8 ./debian/dwww/usr/share/man/man8/dwww-refresh-cache.8.gz > debian/dwww/usr/share/man/man8/dwww-refresh-cache.8.gz.dh-new
	rm -f debian/dwww/usr/share/man/man8/dwww-refresh-cache.8.gz
	mv debian/dwww/usr/share/man/man8/dwww-refresh-cache.8.gz.dh-new debian/dwww/usr/share/man/man8/dwww-refresh-cache.8
	man -l --recode UTF-8 ./debian/dwww/usr/share/man/man8/dwww-cache.8.gz > debian/dwww/usr/share/man/man8/dwww-cache.8.gz.dh-new
	rm -f debian/dwww/usr/share/man/man8/dwww-cache.8.gz
	mv debian/dwww/usr/share/man/man8/dwww-cache.8.gz.dh-new debian/dwww/usr/share/man/man8/dwww-cache.8
	man -l --recode UTF-8 ./debian/dwww/usr/share/man/man8/dwww-build-menu.8.gz > debian/dwww/usr/share/man/man8/dwww-build-menu.8.gz.dh-new
	rm -f debian/dwww/usr/share/man/man8/dwww-build-menu.8.gz
	mv debian/dwww/usr/share/man/man8/dwww-build-menu.8.gz.dh-new debian/dwww/usr/share/man/man8/dwww-build-menu.8
	man -l --recode UTF-8 ./debian/dwww/usr/share/man/man8/dwww-txt2html.8.gz > debian/dwww/usr/share/man/man8/dwww-txt2html.8.gz.dh-new
	rm -f debian/dwww/usr/share/man/man8/dwww-txt2html.8.gz
	mv debian/dwww/usr/share/man/man8/dwww-txt2html.8.gz.dh-new debian/dwww/usr/share/man/man8/dwww-txt2html.8
	chmod 0644 -- debian/dwww/usr/share/man/man7/dwww.7 debian/dwww/usr/share/man/man1/dwww.1 debian/dwww/usr/share/man/man8/dwww-index\+\+.8 debian/dwww/usr/share/man/man8/dwww-find.8 debian/dwww/usr/share/man/man8/dwww-convert.8 debian/dwww/usr/share/man/man8/dwww-quickfind.8 debian/dwww/usr/share/man/man8/dwww-format-man.8 debian/dwww/usr/share/man/man8/dwww-build.8 debian/dwww/usr/share/man/man8/dwww-refresh-cache.8 debian/dwww/usr/share/man/man8/dwww-cache.8 debian/dwww/usr/share/man/man8/dwww-build-menu.8 debian/dwww/usr/share/man/man8/dwww-txt2html.8
   dh_installcron
	install -d debian/dwww/etc/cron.daily
	install -p -m0755 debian/dwww.cron.daily debian/dwww/etc/cron.daily/dwww
	install -d debian/dwww/etc/cron.weekly
	install -p -m0755 debian/dwww.cron.weekly debian/dwww/etc/cron.weekly/dwww
   dh_installdebconf
	install -d debian/dwww/DEBIAN
	sed s/\#DEBHELPER\#// debian/dwww.config > debian/dwww/DEBIAN/config
	chmod 0755 -- debian/dwww/DEBIAN/config
	po2debconf  debian/dwww.templates > debian/dwww/DEBIAN/templates
	(grep -a -s -v misc:Depends debian/dwww.substvars; echo "misc:Depends=debconf (>= 0.5) | debconf-2.0") > debian/dwww.substvars.new
	mv debian/dwww.substvars.new debian/dwww.substvars
	[META] Append autosnippet "postrm-debconf" to postrm [debian/dwww.postrm.debhelper]
   dh_lintian
	install -d debian/dwww/usr/share/lintian/overrides
	install -p -m0644 debian/dwww.lintian-overrides debian/dwww/usr/share/lintian/overrides/dwww
   dh_perl
	(grep -a -s -v perl:Depends debian/dwww.substvars; echo perl:Depends=perl:any) > debian/dwww.substvars.new
	mv debian/dwww.substvars.new debian/dwww.substvars
   dh_link
	rm -f debian/dwww/usr/share/man/man5/dwww.conf.5.gz
	ln -s ../man7/dwww.7.gz debian/dwww/usr/share/man/man5/dwww.conf.5.gz
	rm -f debian/dwww/usr/share/dwww/templates/dwww-convert.end
	ln -s dwww.end debian/dwww/usr/share/dwww/templates/dwww-convert.end
	rm -f debian/dwww/usr/share/dwww/templates/dwww-convert.dir.end
	ln -s dwww.end debian/dwww/usr/share/dwww/templates/dwww-convert.dir.end
	rm -f debian/dwww/usr/share/dwww/templates/dwww-find.end
	ln -s dwww.end debian/dwww/usr/share/dwww/templates/dwww-find.end
   dh_strip_nondeterminism
	Using 1553528891 as canonical time
	Normalizing debian/dwww/usr/share/dwww/default.png using File::StripNondeterminism::handlers::png
	Normalizing debian/dwww/usr/share/pixmaps/dwww-gnome-touristinfo.png using File::StripNondeterminism::handlers::png
   dh_compress
	cd debian/dwww
	chmod a-x usr/share/doc/dwww/NEWS.Debian usr/share/doc/dwww/changelog usr/share/man/man1/dwww.1 usr/share/man/man7/dwww.7 usr/share/man/man8/dwww-build-menu.8 usr/share/man/man8/dwww-build.8 usr/share/man/man8/dwww-cache.8 usr/share/man/man8/dwww-convert.8 usr/share/man/man8/dwww-find.8 usr/share/man/man8/dwww-format-man.8 usr/share/man/man8/dwww-index\+\+.8 usr/share/man/man8/dwww-quickfind.8 usr/share/man/man8/dwww-refresh-cache.8 usr/share/man/man8/dwww-txt2html.8
	gzip -9nf usr/share/doc/dwww/NEWS.Debian usr/share/doc/dwww/changelog usr/share/man/man1/dwww.1 usr/share/man/man7/dwww.7 usr/share/man/man8/dwww-build-menu.8 usr/share/man/man8/dwww-build.8 usr/share/man/man8/dwww-cache.8 usr/share/man/man8/dwww-convert.8 usr/share/man/man8/dwww-find.8 usr/share/man/man8/dwww-format-man.8 usr/share/man/man8/dwww-index\+\+.8 usr/share/man/man8/dwww-quickfind.8 usr/share/man/man8/dwww-refresh-cache.8 usr/share/man/man8/dwww-txt2html.8
	cd '/mnt/dwww.i686/build/dwww'
   dh_fixperms
	find debian/dwww ! -type l -a -true -a -true -print0 2>/dev/null | xargs -0r chmod go=rX,u+rw,a-s
	find debian/dwww/usr/share/doc -type f -a -true -a ! -regex 'debian/dwww/usr/share/doc/[^/]*/examples/.*' -print0 2>/dev/null | xargs -0r chmod 0644
	find debian/dwww/usr/share/doc -type d -a -true -a -true -print0 2>/dev/null | xargs -0r chmod 0755
	find debian/dwww/usr/share/man debian/dwww/usr/share/applications debian/dwww/usr/share/lintian/overrides -type f -a -true -a -true -print0 2>/dev/null | xargs -0r chmod 0644
	find debian/dwww -type f \( -name '*.so.*' -o -name '*.so' -o -name '*.la' -o -name '*.a' -o -name '*.js' -o -name '*.css' -o -name '*.scss' -o -name '*.sass' -o -name '*.jpeg' -o -name '*.jpg' -o -name '*.png' -o -name '*.gif' -o -name '*.cmxs' -o -name '*.node' \) -a -true -a -true -print0 2>/dev/null | xargs -0r chmod 0644
	find debian/dwww/usr/bin debian/dwww/usr/sbin -type f -a -true -a -true -print0 2>/dev/null | xargs -0r chmod a+x
	find debian/dwww/usr/lib -type f -name '*.ali' -a -true -a -true -print0 2>/dev/null | xargs -0r chmod uga-w
   dh_missing
   dh_strip
   dh_makeshlibs
	rm -f debian/dwww/DEBIAN/shlibs
   dh_shlibdeps
   dh_installdeb
	[META] Append autosnippet "maintscript-helper" to postinst [debian/dwww.postinst.debhelper]
	[META] Append autosnippet "maintscript-helper" to preinst [debian/dwww.preinst.debhelper]
	[META] Append autosnippet "maintscript-helper" to prerm [debian/dwww.prerm.debhelper]
	[META] Prepend autosnippet "maintscript-helper" to postrm [debian/dwww.postrm.debhelper.new]
	mv debian/dwww.postrm.debhelper.new debian/dwww.postrm.debhelper
	cp -f debian/dwww.postinst debian/dwww/DEBIAN/postinst
	perl -p -i -e "s~#DEBHELPER#~qx{cat debian/dwww.postinst.debhelper}~eg" debian/dwww/DEBIAN/postinst
	chmod 0755 -- debian/dwww/DEBIAN/postinst
	cp -f debian/dwww.preinst debian/dwww/DEBIAN/preinst
	perl -p -i -e "s~#DEBHELPER#~qx{cat debian/dwww.preinst.debhelper}~eg" debian/dwww/DEBIAN/preinst
	chmod 0755 -- debian/dwww/DEBIAN/preinst
	cp -f debian/dwww.prerm debian/dwww/DEBIAN/prerm
	perl -p -i -e "s~#DEBHELPER#~qx{cat debian/dwww.prerm.debhelper}~eg" debian/dwww/DEBIAN/prerm
	chmod 0755 -- debian/dwww/DEBIAN/prerm
	cp -f debian/dwww.postrm debian/dwww/DEBIAN/postrm
	perl -p -i -e "s~#DEBHELPER#~qx{cat debian/dwww.postrm.debhelper}~eg" debian/dwww/DEBIAN/postrm
	chmod 0755 -- debian/dwww/DEBIAN/postrm
	find debian/dwww/etc -type f -printf '/etc/%P
' | LC_ALL=C sort >> debian/dwww/DEBIAN/conffiles
	chmod 0644 -- debian/dwww/DEBIAN/conffiles
   dh_gencontrol
	echo misc:Pre-Depends= >> debian/dwww.substvars
	dpkg-gencontrol -pdwww -ldebian/changelog -Tdebian/dwww.substvars -Pdebian/dwww -UMulti-Arch
dpkg-gencontrol: warning: Depends field of package dwww: substitution variable ${shlibs:Depends} used, but is not defined
dpkg-gencontrol: warning: Recommends field of package dwww: substitution variable ${misc:Recommends} used, but is not defined
dpkg-gencontrol: warning: File::FcntlLock not available; using flock which is not NFS-safe
	chmod 0644 -- debian/dwww/DEBIAN/control
   dh_md5sums
	cd debian/dwww >/dev/null && xargs -r0 md5sum | perl -pe 'if (s@^\\@@) { s/\\\\/\\/g; }' > DEBIAN/md5sums
	chmod 0644 -- debian/dwww/DEBIAN/md5sums
   dh_builddeb
	dpkg-deb --root-owner-group --build debian/dwww ..
dpkg-deb: building package 'dwww' in '../dwww_1.13.4+nmu3_i386.deb'.
 dpkg-genbuildinfo
dpkg-genbuildinfo: warning: cannot open /var/lib/dpkg/status
readline() on closed filehandle $status_fh at /usr/bin/dpkg-genbuildinfo line 96.
dpkg-genbuildinfo: warning: File::FcntlLock not available; using flock which is not NFS-safe
 dpkg-genchanges  >../dwww_1.13.4+nmu3_i386.changes
dpkg-genchanges: info: including full source code in upload
 dpkg-source --auto-commit --after-build .
dpkg-source: warning: --auto-commit is not a valid option for Dpkg::Source::Package::V3::Native
dpkg-source: info: using options from dwww/debian/source/options: --diff-ignore --tar-ignore
dpkg-buildpackage: info: full upload; Debian-native package (full source is included)
[1;39m>>> Installing dwww.i686[0;0m
Fixing symlinks:
Compressing man pages:
        dwww.conf.5
[1;33m*** Warning:[0;0m vendor_perl should be used instead of site_perl; fixing
Stripping executables:
        usr/sbin/dwww-quickfind.exe
        usr/sbin/dwww-txt2html.exe
        usr/sbin/dwww-cache.exe
Preparing debuginfo source files:
	1 files	2 files	3 files	4 files
[1;32m*** Info:[0;0m Removing empty directory: /var/cache/dwww/db
[1;32m*** Info:[0;0m Removing empty directory: /srv/www/htdocs
[1;32m*** Info:[0;0m Removing empty directory: /var/lib/dwww
[1;32m*** Info:[0;0m Removing empty directory: /var/cache/dwww
[1;32m*** Info:[0;0m Removing empty directory: /etc/dwww
[1;32m*** Info:[0;0m Removing empty directory: /var/lib
[1;32m*** Info:[0;0m Removing empty directory: /var/cache
[1;32m*** Info:[0;0m Removing empty directory: /var
[1;39m>>> Packaging dwww.i686[0;0m
>>> Creating binary package(s)
>>> dwww-dwww-dwww.tar.xz
etc/
etc/cron.daily/
etc/cron.daily/dwww
etc/httpd/
etc/httpd/conf.d/
etc/httpd/conf.d/dwww.conf
etc/cron.weekly/
etc/cron.weekly/dwww
srv/
srv/www/
srv/www/cgi-bin/
srv/www/cgi-bin/dwww
usr/
usr/lib/
usr/lib/perl5/
usr/lib/perl5/vendor_perl/
usr/lib/perl5/vendor_perl/5.22/
usr/lib/perl5/vendor_perl/5.22/Debian/
usr/lib/perl5/vendor_perl/5.22/Debian/Dwww/
usr/lib/perl5/vendor_perl/5.22/Debian/Dwww/ConfigFile.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Dwww/Common.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Dwww/Version.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Dwww/Utils.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Dwww/DocBase.pm
usr/lib/perl5/vendor_perl/5.22/Debian/Dwww/Initialize.pm
usr/sbin/
usr/sbin/dwww-index++
usr/sbin/dwww-build-menu
usr/sbin/dwww-build
usr/sbin/dwww-quickfind.exe
usr/sbin/dwww-txt2html.exe
usr/sbin/dwww-find
usr/sbin/dwww-format-man
usr/sbin/dwww-refresh-cache
usr/sbin/dwww-convert
usr/sbin/dwww-cache.exe
usr/share/
usr/share/dwww/
usr/share/dwww/dwww.css
usr/share/dwww/templates/
usr/share/dwww/templates/dwww.template
usr/share/dwww/templates/menu.end
usr/share/dwww/templates/menu.errors.end
usr/share/dwww/templates/dwww.end
usr/share/dwww/templates/dwww-find.end
usr/share/dwww/templates/dwww-convert.start
usr/share/dwww/templates/man-begins-with.end
usr/share/dwww/templates/dwww-find.start
usr/share/dwww/templates/dwww-convert.dir.start
usr/share/dwww/templates/dwww-convert.dir.end
usr/share/dwww/templates/man-index.end
usr/share/dwww/templates/menu.all.start
usr/share/dwww/templates/menu.nosections
usr/share/dwww/templates/man-in-section.end
usr/share/dwww/templates/man-index.start
usr/share/dwww/templates/menu.single.start
usr/share/dwww/templates/dwww-convert.end
usr/share/dwww/templates/menu.errors.start
usr/share/dwww/templates/man-in-section.start
usr/share/dwww/templates/man-begins-with.start
usr/share/dwww/default.png
usr/share/dwww/swish++.conf
usr/share/dwww/functions.sh
usr/share/doc/
usr/share/doc/dwww/
usr/share/doc/dwww/changelog.gz
usr/share/doc/dwww/TODO
usr/share/doc/dwww/README
usr/share/doc/dwww/copyright
usr/share/doc/dwww/NEWS.Debian.gz
usr/share/man/
usr/share/man/man7/
usr/share/man/man7/dwww.7.gz
usr/share/man/man1/
usr/share/man/man1/dwww.1.gz
usr/share/man/man8/
usr/share/man/man8/dwww-index++.8.gz
usr/share/man/man8/dwww-find.8.gz
usr/share/man/man8/dwww-convert.8.gz
usr/share/man/man8/dwww-quickfind.8.gz
usr/share/man/man8/dwww-format-man.8.gz
usr/share/man/man8/dwww-build.8.gz
usr/share/man/man8/dwww-refresh-cache.8.gz
usr/share/man/man8/dwww-cache.8.gz
usr/share/man/man8/dwww-build-menu.8.gz
usr/share/man/man8/dwww-txt2html.8.gz
usr/share/man/man5/
usr/share/man/man5/dwww.conf.5.gz
usr/share/firefox/
usr/share/firefox/distribution/
usr/share/firefox/distribution/searchplugins/
usr/share/firefox/distribution/searchplugins/common/
usr/share/firefox/distribution/searchplugins/common/dwww.xml
usr/share/applications/
usr/share/applications/dwww.desktop
usr/share/lintian/
usr/share/lintian/overrides/
usr/share/lintian/overrides/dwww
usr/share/firefox-esr/
usr/share/firefox-esr/distribution/
usr/share/firefox-esr/distribution/searchplugins/
usr/share/firefox-esr/distribution/searchplugins/common/
usr/share/firefox-esr/distribution/searchplugins/common/dwww.xml
usr/share/pixmaps/
usr/share/pixmaps/dwww-gnome-touristinfo.png
usr/bin/
usr/bin/dwww

>>> dwww-debuginfo-dwww-dwww.tar.xz
usr/lib/debug/
usr/lib/debug/usr/
usr/lib/debug/usr/sbin/
usr/lib/debug/usr/sbin/dwww-txt2html.exe.dbg
usr/lib/debug/usr/sbin/dwww-cache.exe.dbg
usr/lib/debug/usr/sbin/dwww-quickfind.exe.dbg
usr/src/debug/
usr/src/debug/dwww/
usr/src/debug/dwww/dwww/
usr/src/debug/dwww/dwww/src/
usr/src/debug/dwww/dwww/src/utils.c
usr/src/debug/dwww/dwww/src/dwww-txt2html.c
usr/src/debug/dwww/dwww/src/dwww-quickfind.c
usr/src/debug/dwww/dwww/src/dwww-cache.c

>>> Checking packages for missing or duplicate files

>>> Creating source patches
 0 files changed
>>> Creating source package
dwww.src/
dwww.src/dwww_1.13.4+nmu3.dsc
dwww.src/dwww_1.13.4+nmu3.tar.xz
dwww.src/dwww.patch
dwww.src/dwww.cygport

which: no KERNEL32.dll in (/mnt/dwww.i686/inst/usr/bin:/usr/local/bin:/usr/bin:/bin:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/usr/lib/lapack:/cygdrive/c/WINDOWS/system32)
>>> dwww requires: bash cygwin dwww-dwww-dwww perl perl-MIME-Types perl_base  debianutils doc-base file libfile-ncopy-perl libmime-types-perl man-db mime-support ucf  perl libc6
]0;/mnt
[32mAdministrator@- [33m/mnt[0m
$ exit

Script done on Mon Apr 13 04:41:54 2020
