Script started on Thu Apr  9 06:36:32 2020
cygport --32 intltool-debian all
]0;/mnt
[32mAdministrator@- [33m/mnt[0m
$ cygport --32 intltool-debian all
[1;39m>>> Preparing intltool-debian.noarch[0;0m
>>> Unpacking source intltool-debian_0.35.0+20060710.5.dsc
>>> Unpacking source intltool-debian_0.35.0+20060710.5.tar.xz
gpgv: keyblock resource `/home/Administrator/.gnupg/trustedkeys.gpg': file open error
gpgv: Signature made Tue Jan 22 19:56:32 2019 CET using RSA key ID 61825ACE
gpgv: Can't check signature: public key not found
[1mdpkg-source: [0m[1;33mwarning[0m: failed to verify signature on /mnt/intltool-debian_0.35.0+20060710.5.dsc
[1mdpkg-source: [0m[32minfo[0m: extracting intltool-debian in intltool-debian
[1mdpkg-source: [0m[32minfo[0m: unpacking intltool-debian_0.35.0+20060710.5.tar.xz
>>> Preparing working source directory
[1;39m>>> Compiling intltool-debian.noarch[0;0m
dpkg-buildpackage: info: source package intltool-debian
dpkg-buildpackage: info: source version 0.35.0+20060710.5
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Boyuan Yang <byang@debian.org>
dpkg-architecture: warning: default GNU system type i686-linux-gnu for Debian arch i386 does not match specified GNU system type i686-pc-cygwin
 dpkg-source --auto-commit --before-build .
dpkg-buildpackage: info: host architecture i386
dpkg-source: warning: --auto-commit is not a valid option for Dpkg::Source::Package::V3::Native
 debian/rules clean
dh clean
   dh_auto_clean
	make -j1 clean
   dh_clean
	rm -f debian/debhelper-build-stamp
	rm -rf debian/.debhelper/
	rm -f debian/intltool-debian.debhelper.log
	rm -f -- debian/intltool-debian.substvars debian/files
	rm -fr -- debian/intltool-debian/ debian/tmp/
	find .  \( \( \
		\( -path .\*/.git -o -path .\*/.svn -o -path .\*/.bzr -o -path .\*/.hg -o -path .\*/CVS -o -path .\*/.pc -o -path .\*/_darcs \) -prune -o -type f -a \
	        \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
		 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
		 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
		 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
		\) -exec rm -f {} + \) -o \
		\( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \)
 dpkg-source --auto-commit -b .
dpkg-source: warning: --auto-commit is not a valid option for Dpkg::Source::Package::V3::Native
dpkg-source: info: using source format '3.0 (native)'
dpkg-source: info: building intltool-debian in intltool-debian_0.35.0+20060710.5.tar.xz
dpkg-source: info: building intltool-debian in intltool-debian_0.35.0+20060710.5.dsc
 debian/rules binary
dh binary
   dh_update_autotools_config
   dh_autoreconf
   dh_auto_configure
   dh_auto_build
	make -j1 "INSTALL=install --strip-program=true"
make[1]: Entering directory '/mnt/intltool-debian.noarch/build/intltool-debian'
make[1]: Leaving directory '/mnt/intltool-debian.noarch/build/intltool-debian'
   dh_auto_test
   create-stamp debian/debhelper-build-stamp
   dh_testroot
   dh_prep
	rm -f -- debian/intltool-debian.substvars
	rm -fr -- debian/.debhelper/generated/intltool-debian/ debian/intltool-debian/ debian/tmp/
   debian/rules override_dh_auto_install
make[1]: Entering directory '/mnt/intltool-debian.noarch/build/intltool-debian'
dh_auto_install -- prefix=/usr
	install -d /mnt/intltool-debian.noarch/build/intltool-debian/debian/intltool-debian
	make -j1 install DESTDIR=/mnt/intltool-debian.noarch/build/intltool-debian/debian/intltool-debian AM_UPDATE_INFO_DIR=no "INSTALL=install --strip-program=true" prefix=/usr
make[2]: Entering directory '/mnt/intltool-debian.noarch/build/intltool-debian'
install -m 0755 intltool-bin/intltool-* /mnt/intltool-debian.noarch/build/intltool-debian/debian/intltool-debian/usr/share/intltool-debian
make[2]: Leaving directory '/mnt/intltool-debian.noarch/build/intltool-debian'
make[1]: Leaving directory '/mnt/intltool-debian.noarch/build/intltool-debian'
   dh_installdocs
	install -d debian/intltool-debian/usr/share/doc/intltool-debian
	install -d debian/.debhelper/generated/intltool-debian
	cp --reflink=auto -a ./AUTHORS debian/intltool-debian/usr/share/doc/intltool-debian
	chmod -R u\+rw,go=rX debian/intltool-debian/usr/share/doc
	install -p -m0644 debian/README.Debian debian/intltool-debian/usr/share/doc/intltool-debian/README.Debian
	install -p -m0644 debian/copyright debian/intltool-debian/usr/share/doc/intltool-debian/copyright
   dh_installchangelogs
	install -p -m0644 debian/changelog debian/intltool-debian/usr/share/doc/intltool-debian/changelog
   dh_perl
	(grep -a -s -v perl:Depends debian/intltool-debian.substvars; echo perl:Depends=perl:any) > debian/intltool-debian.substvars.new
	mv debian/intltool-debian.substvars.new debian/intltool-debian.substvars
   dh_link
   dh_strip_nondeterminism
   dh_compress
	cd debian/intltool-debian
	chmod a-x usr/share/doc/intltool-debian/changelog
	gzip -9nf usr/share/doc/intltool-debian/changelog
	cd '/mnt/intltool-debian.noarch/build/intltool-debian'
   dh_fixperms
	find debian/intltool-debian ! -type l -a -true -a -true -print0 2>/dev/null | xargs -0r chmod go=rX,u+rw,a-s
	find debian/intltool-debian/usr/share/doc -type f -a -true -a ! -regex 'debian/intltool-debian/usr/share/doc/[^/]*/examples/.*' -print0 2>/dev/null | xargs -0r chmod 0644
	find debian/intltool-debian/usr/share/doc -type d -a -true -a -true -print0 2>/dev/null | xargs -0r chmod 0755
	find debian/intltool-debian -type f \( -name '*.so.*' -o -name '*.so' -o -name '*.la' -o -name '*.a' -o -name '*.js' -o -name '*.css' -o -name '*.scss' -o -name '*.sass' -o -name '*.jpeg' -o -name '*.jpg' -o -name '*.png' -o -name '*.gif' -o -name '*.cmxs' -o -name '*.node' \) -a -true -a -true -print0 2>/dev/null | xargs -0r chmod 0644
	rm -f debian/intltool-debian.debhelper.log
   debian/rules override_dh_missing
make[1]: Entering directory '/mnt/intltool-debian.noarch/build/intltool-debian'
dh_missing --fail-missing
make[1]: Leaving directory '/mnt/intltool-debian.noarch/build/intltool-debian'
   dh_installdeb
	install -d debian/intltool-debian/DEBIAN
   dh_gencontrol
	echo misc:Depends= >> debian/intltool-debian.substvars
	echo misc:Pre-Depends= >> debian/intltool-debian.substvars
	dpkg-gencontrol -pintltool-debian -ldebian/changelog -Tdebian/intltool-debian.substvars -Pdebian/intltool-debian -UMulti-Arch
dpkg-gencontrol: warning: File::FcntlLock not available; using flock which is not NFS-safe
	chmod 0644 -- debian/intltool-debian/DEBIAN/control
   dh_md5sums
	cd debian/intltool-debian >/dev/null && xargs -r0 md5sum | perl -pe 'if (s@^\\@@) { s/\\\\/\\/g; }' > DEBIAN/md5sums
	chmod 0644 -- debian/intltool-debian/DEBIAN/md5sums
   dh_builddeb
	dpkg-deb --root-owner-group --build debian/intltool-debian ..
dpkg-deb: building package 'intltool-debian' in '../intltool-debian_0.35.0+20060710.5_all.deb'.
 dpkg-genbuildinfo
dpkg-genbuildinfo: warning: cannot open /var/lib/dpkg/status
readline() on closed filehandle $status_fh at /usr/bin/dpkg-genbuildinfo line 96.
dpkg-genbuildinfo: warning: File::FcntlLock not available; using flock which is not NFS-safe
Use of uninitialized value $value in pattern match (m//) at /usr/share/perl5/Dpkg/Control/HashCore.pm line 358.
 dpkg-genchanges  >../intltool-debian_0.35.0+20060710.5_i386.changes
dpkg-genchanges: info: including full source code in upload
 dpkg-source --auto-commit --after-build .
dpkg-source: warning: --auto-commit is not a valid option for Dpkg::Source::Package::V3::Native
dpkg-buildpackage: info: full upload; Debian-native package (full source is included)
[1;39m>>> Installing intltool-debian.noarch[0;0m
Fixing symlinks:
Stripping executables:
Preparing debuginfo source files:

[1;39m>>> Packaging intltool-debian.noarch[0;0m
>>> Creating binary package(s)
>>> intltool-debian-intltool-debian-debian.tar.xz
usr/
usr/share/
usr/share/doc/
usr/share/doc/intltool-debian/
usr/share/doc/intltool-debian/changelog.gz
usr/share/doc/intltool-debian/AUTHORS
usr/share/doc/intltool-debian/copyright
usr/share/doc/intltool-debian/README.Debian
usr/share/intltool-debian/
usr/share/intltool-debian/intltool-extract
usr/share/intltool-debian/intltool-merge
usr/share/intltool-debian/intltool-update

[1;32m*** Info:[0;0m No debug files, skipping debuginfo subpackage

>>> Checking packages for missing or duplicate files

>>> Creating source patches
 0 files changed
>>> Creating source package
intltool-debian.src/
intltool-debian.src/intltool-debian_0.35.0+20060710.5.dsc
intltool-debian.src/intltool-debian.cygport
intltool-debian.src/intltool-debian_0.35.0+20060710.5.tar.xz

>>> intltool-debian requires: perl-XML-Parser perl_base gettext perl
]0;/mnt
[32mAdministrator@- [33m/mnt[0m
$ exit

Script done on Thu Apr  9 06:38:10 2020
