DOXIE
=====

Doxie is a search engine for your office documents and emails on Windows. A
typical system has documentation in many formats (docx, pdf, email, ...). The
doxie searches all of them a web browser.

Doxie is based on dwww and other Debian packages ported to Cygwin:
"All installed on-line documentation will be served via a local HTTP
server at http://localhost/dwww/. This package runs cron scripts to
convert available resources to the HTML pages.  Executing the dwww
command starts a sensible WWW browser locally to access them."

BUILD
=====

Execute following commands to build the project.

.Building
[source,sh]
-----
# Checkout source code
git clone --recursive https://github.com/furrymcgee/doxie-search
cd doxie-search
# Execute autogen.sh and write typescript
script -c bash\ -ex < autogen.sh
----

REQUIREMENTS
============

A Cygwin installation is required before building. Please see link below how to
install required Cygwin packages with cygwin-auto-install. CPAN access is
required during build process.

- https://github.com/furrymcgee/cygwin-auto-install
