DOXYGWIN
-----

Doxygwin is a search engine for your office documents and emails on
Windows. A typical system has documentation in many formats (docx, pdf, email,
...). The Doxygwin finds all of them in a web browser.

Doxygwin is based on dwww and other Debian packages ported to Cygwin:
"All installed on-line documentation will be served via a local HTTP
server at http://localhost/dwww/. This package runs cron scripts to
convert available resources to the HTML pages.  Executing the dwww
command starts a sensible WWW browser locally to access them."

OVERVIEW
--------
Directories

- repository, Doxygwin package repository
- cygwin-auto-install, Script for download and setup
- windows, Windows XP Virtual Machine
- etc, Documents
- bin, Tools

REQUIREMENTS
------------

A Cygwin installation is used for building and installation.
The autorun.inf starts the installation. Please see
link below how to install required Cygwin packages with cygwin-auto-install.
There is a repository with all packages built for x86.

INSTALL
-------

Install doxygwin with autorun.bat.

- https://github.com/furrymcgee/doxygwin

.Installation
[source,bat]
-----
include::autorun.bat[]
-----

TOOLCHAIN
---------

The doxygwin toolchain is available as packages or can be build from source.
There is a bootstrap.sh script to build and install the toolchain from source.

.Bootstrap
[source,sh]
-----
source bootstrap.sh
-----

CYGPORT
-------

Cyport is a tool to build new packages for cygwin distribution.
The dpkg toolchain can build packages from debian sources.
There is a dpkg.cygclass file to build debian sources with cygport.
The dwww.cygport for example inherits dpkg.cygclass to build a dwww package.


SETUP
-----

The repository contains packages and a setup.ini file with checksums.
There is a autogen.sh script to create a setup.ini file.
The typescript file contains a log of the autogen.sh build script.

.Setup
[source,sh]
-----
# Checkout source code
git clone --recursive https://github.com/furrymcgee/doxygwin
# Change to submodule
cd doxygwin/cygwin-auto-install/doxygwin/Y%3a%2f
# Execute autogen.sh and write typescript
printf %q\\\n source\ ../autogen.sh | script -c bash\ -ex
-----

LINKS
-----
dwww, doc-base, swish++, apache2
