Script started on Wed Apr 15 22:57:40 2020
makefile:143: update target 'recutils_1.7-3.i686' due to: recutils_1.7-3.dsc
cygport --32 recutils_1.7-3.cygport all
[1;39m>>> Preparing recutils-1.7-3-1.i686[0;0m
[1;32m*** Info:[0;0m SOURCE 1 signature follows:
gpg: WARNING: using insecure memory!
gpg: please see http://www.gnupg.org/documentation/faqs.html for more information
gpg: Signature made Tue Mar 25 00:09:36 2014 CET using RSA key ID B304AF08
gpg: Can't check signature: public key not found
>>> Unpacking source recutils_1.7-3.dsc
>>> Unpacking source recutils_1.7.orig.tar.gz
>>> Unpacking source recutils_1.7-3.debian.tar.xz
gpgv: keyblock resource `/home/Administrator/.gnupg/trustedkeys.gpg': file open error
gpgv: Signature made Mon Dec 17 21:37:11 2018 CET using RSA key ID 8C762BAD
gpgv: Can't check signature: public key not found
[1mdpkg-source: [0m[1;33mwarning[0m: failed to verify signature on /mnt/recutils_1.7-3.dsc
[1mdpkg-source: [0m[32minfo[0m: extracting recutils in recutils
[1mdpkg-source: [0m[32minfo[0m: unpacking recutils_1.7.orig.tar.gz
[1mdpkg-source: [0m[32minfo[0m: unpacking recutils_1.7-3.debian.tar.xz
[1mdpkg-source: [0m[32minfo[0m: using patch list from debian/patches/series
[1mdpkg-source: [0m[32minfo[0m: applying man.patch
[1mdpkg-source: [0m[32minfo[0m: applying evaluation-of-sexes.patch
[1mdpkg-source: [0m[32minfo[0m: applying csv2rec-format-warning.patch
[1mdpkg-source: [0m[32minfo[0m: applying make-check.patch
[1mdpkg-source: [0m[32minfo[0m: applying enable-automake-subdirs-option.patch
[1mdpkg-source: [0m[32minfo[0m: applying fix-includes.patch
[1mdpkg-source: [0m[32minfo[0m: applying spelling-error-in-binary-csv2rec.patch
[1mdpkg-source: [0m[32minfo[0m: applying gnulibrary-glibc-detection.patch
[1mdpkg-source: [0m[32minfo[0m: applying spelling-error-in-csv2rec-manpage.patch
[1mdpkg-source: [0m[32minfo[0m: applying rec-mode.patch
>>> Preparing working source directory
[1;39m>>> Compiling recutils-1.7-3-1.i686[0;0m
dpkg-buildpackage: info: source package recutils
dpkg-buildpackage: info: source version 1.7-3
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Sven Wick <sven.wick@gmx.de>
dpkg-architecture: warning: default GNU system type i686-linux-gnu for Debian arch i386 does not match specified GNU system type i686-pc-cygwin
 dpkg-source --auto-commit --before-build .
dpkg-buildpackage: info: host architecture i386
 debian/rules clean
make[1]: Entering directory '/mnt/recutils-1.7-3-1.i686/build/recutils'
debian/rules:10: target 'clean' does not exist
dh clean
   debian/rules override_dh_auto_clean
make[2]: Entering directory '/mnt/recutils-1.7-3-1.i686/build/recutils'
debian/rules:13: target 'override_dh_auto_clean' does not exist
[ ! -f Makefile ] || make clean
make[2]: Leaving directory '/mnt/recutils-1.7-3-1.i686/build/recutils'
   dh_clean
	rm -f debian/debhelper-build-stamp
	rm -rf debian/.debhelper/
	rm -f -- debian/recutils.substvars debian/librec-dev.substvars debian/librec1.substvars debian/files
	rm -fr -- debian/recutils/ debian/tmp/ debian/librec-dev/ debian/librec1/
	find .  \( \( \
		\( -path .\*/.git -o -path .\*/.svn -o -path .\*/.bzr -o -path .\*/.hg -o -path .\*/CVS -o -path .\*/.pc -o -path .\*/_darcs \) -prune -o -type f -a \
	        \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
		 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
		 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
		 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
		\) -exec rm -f {} + \) -o \
		\( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \)
make[1]: Leaving directory '/mnt/recutils-1.7-3-1.i686/build/recutils'
 dpkg-source --auto-commit -b .
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building recutils using existing ./recutils_1.7.orig.tar.gz
dpkg-source: info: using patch list from debian/patches/series
dpkg-source: info: building recutils in recutils_1.7-3.debian.tar.xz
dpkg-source: info: building recutils in recutils_1.7-3.dsc
 debian/rules binary
make[1]: Entering directory '/mnt/recutils-1.7-3-1.i686/build/recutils'
debian/rules:10: target 'binary' does not exist
dh binary
   dh_update_autotools_config
	install -d debian/.debhelper/bucket/files
	cp -an --reflink=auto build-aux/config.guess debian/.debhelper/bucket/files/07810522e938cf9bb9ad64a2456f158c98b031659959414651f7c503d60070b4.tmp
	mv debian/.debhelper/bucket/files/07810522e938cf9bb9ad64a2456f158c98b031659959414651f7c503d60070b4.tmp debian/.debhelper/bucket/files/07810522e938cf9bb9ad64a2456f158c98b031659959414651f7c503d60070b4
	cp -f /usr/share/misc/config.guess ./build-aux/config.guess
cp: cannot stat '/usr/share/misc/config.guess': No such file or directory
dh_update_autotools_config: cp -f /usr/share/misc/config.guess ./build-aux/config.guess returned exit code 1
make[1]: *** [debian/rules:10: binary] Error 1
make[1]: Leaving directory '/mnt/recutils-1.7-3-1.i686/build/recutils'
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make: *** [makefile:143: recutils_1.7-3.i686] Error 1

Script done on Wed Apr 15 23:08:05 2020
