Script started on Tue Apr 14 20:54:21 2020
cygport --32 sensible-utils all
]0;/mnt
[32mAdministrator@- [33m/mnt[0m
$ cygport --32 sensible-utils all
[1;39m>>> Preparing sensible-utils.noarch[0;0m
>>> Unpacking source sensible-utils_0.0.12.dsc
>>> Unpacking source sensible-utils_0.0.12.tar.xz
gpgv: keyblock resource `/home/Administrator/.gnupg/trustedkeys.gpg': file open error
gpgv: Signature made Mon Mar 12 13:39:32 2018 CET using RSA key ID AA41085F
gpgv: Can't check signature: public key not found
[1mdpkg-source: [0m[1;33mwarning[0m: failed to verify signature on /mnt/sensible-utils_0.0.12.dsc
[1mdpkg-source: [0m[32minfo[0m: extracting sensible-utils in sensible-utils
[1mdpkg-source: [0m[32minfo[0m: unpacking sensible-utils_0.0.12.tar.xz
>>> Preparing working source directory
[1;33m*** Warning:[0;0m Some build dependencies are not installed.
[1;33m*** Warning:[0;0m This package may end up missing features, or not build at all.
[1;33m*** Warning:[0;0m Consider installing these packages first before continuing:
[1;33m*** Warning:[0;0m     dpkg debhelper 
[1;39m>>> Compiling sensible-utils.noarch[0;0m
dpkg-buildpackage: info: source package sensible-utils
dpkg-buildpackage: info: source version 0.0.12
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Bastien Roucariès <rouca@debian.org>
dpkg-architecture: warning: default GNU system type i686-linux-gnu for Debian arch i386 does not match specified GNU system type i686-pc-cygwin
 dpkg-source --auto-commit --before-build .
dpkg-buildpackage: info: host architecture i386
dpkg-source: warning: --auto-commit is not a valid option for Dpkg::Source::Package::V3::Native
 debian/rules clean
dh clean
   dh_clean
	rm -f debian/debhelper-build-stamp
	rm -rf debian/.debhelper/
	rm -f -- debian/sensible-utils.substvars debian/files
	rm -fr -- debian/sensible-utils/ debian/tmp/
	find .  \( \( \
		\( -path .\*/.git -o -path .\*/.svn -o -path .\*/.bzr -o -path .\*/.hg -o -path .\*/CVS -o -path .\*/.pc -o -path .\*/_darcs \) -prune -o -type f -a \
	        \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
		 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
		 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
		 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
		\) -exec rm -f {} + \) -o \
		\( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \)
 dpkg-source --auto-commit -b .
dpkg-source: warning: --auto-commit is not a valid option for Dpkg::Source::Package::V3::Native
dpkg-source: info: using source format '3.0 (native)'
dpkg-source: info: building sensible-utils in sensible-utils_0.0.12.tar.xz
dpkg-source: info: building sensible-utils in sensible-utils_0.0.12.dsc
 debian/rules binary
dh binary
   dh_update_autotools_config
   dh_autoreconf
	find ! -ipath "./debian/*" -a ! \( -path '*/.git/*' -o -path '*/.hg/*' -o -path '*/.bzr/*' -o -path '*/.svn/*' -o -path '*/CVS/*' \) -a  -type f -exec md5sum {} + -o -type l -printf "symlink  %p
" > debian/autoreconf.before
	grep -q ^XDT_ configure.ac
	autoreconf -f -i
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/bin/automake-1.15 line 3936.
	find ! -ipath "./debian/*" -a ! \( -path '*/.git/*' -o -path '*/.hg/*' -o -path '*/.bzr/*' -o -path '*/.svn/*' -o -path '*/CVS/*' \) -a  -type f -exec md5sum {} + -o -type l -printf "symlink  %p
" > debian/autoreconf.after
   dh_auto_configure
	./configure --build=i686-pc-cygwin --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=\${prefix}/lib/i386-linux-gnu --libexecdir=\${prefix}/lib/i386-linux-gnu --disable-maintainer-mode --disable-dependency-tracking
configure: WARNING: unrecognized options: --disable-maintainer-mode, --disable-dependency-tracking
configure: loading site script /usr/share/config.site
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for po4a... po4a
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating man/Makefile
configure: WARNING: unrecognized options: --disable-maintainer-mode, --disable-dependency-tracking
   dh_auto_build
	make -j1
make[1]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils'
Making all in man
make[2]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
sed -f ./utf8toman.sed -e 's/%PACKAGE%/sensible-utils/g' -e 's/%VERSION%/0.0.11/g' -e 's/%RELEASE_DATE%//g' -e 's:%CONFDIR%:/etc:g' -e 's:%LOGDIR%::g' -e 's:%ADMINDIR%::g' -e 's:%PKGDOCDIR%:/usr/share/doc/sensible-utils:g' -e 's:%PKGCONFDIR%::g' -e 's:%PKGLIBDIR%:/usr/lib/i386-linux-gnu/sensible-utils:g' -e 's:%PKGDATADIR%:/usr/share/sensible-utils:g' sensible-editor.man >sensible-editor.1
sed -f ./utf8toman.sed -e 's/%PACKAGE%/sensible-utils/g' -e 's/%VERSION%/0.0.11/g' -e 's/%RELEASE_DATE%//g' -e 's:%CONFDIR%:/etc:g' -e 's:%LOGDIR%::g' -e 's:%ADMINDIR%::g' -e 's:%PKGDOCDIR%:/usr/share/doc/sensible-utils:g' -e 's:%PKGCONFDIR%::g' -e 's:%PKGLIBDIR%:/usr/lib/i386-linux-gnu/sensible-utils:g' -e 's:%PKGDATADIR%:/usr/share/sensible-utils:g' sensible-browser.man >sensible-browser.1
sed -f ./utf8toman.sed -e 's/%PACKAGE%/sensible-utils/g' -e 's/%VERSION%/0.0.11/g' -e 's/%RELEASE_DATE%//g' -e 's:%CONFDIR%:/etc:g' -e 's:%LOGDIR%::g' -e 's:%ADMINDIR%::g' -e 's:%PKGDOCDIR%:/usr/share/doc/sensible-utils:g' -e 's:%PKGCONFDIR%::g' -e 's:%PKGLIBDIR%:/usr/lib/i386-linux-gnu/sensible-utils:g' -e 's:%PKGDATADIR%:/usr/share/sensible-utils:g' sensible-pager.man >sensible-pager.1
sed -f ./utf8toman.sed -e 's/%PACKAGE%/sensible-utils/g' -e 's/%VERSION%/0.0.11/g' -e 's/%RELEASE_DATE%//g' -e 's:%CONFDIR%:/etc:g' -e 's:%LOGDIR%::g' -e 's:%ADMINDIR%::g' -e 's:%PKGDOCDIR%:/usr/share/doc/sensible-utils:g' -e 's:%PKGCONFDIR%::g' -e 's:%PKGLIBDIR%:/usr/lib/i386-linux-gnu/sensible-utils:g' -e 's:%PKGDATADIR%:/usr/share/sensible-utils:g' select-editor.man >select-editor.1
po4a --previous --srcdir . --destdir . --no-backups --porefs noline,wrap --msgmerge-opt=--add-location=file --package-name sensible-utils  ./po4a/po4a.cfg
touch man.stamp
for lang in `sed -ne 's/^.*\[po4a_langs\] \(.*\)$/\1/p' ./po4a/po4a.cfg`; do \
  files=""; \
  for man in sensible-editor.1 sensible-browser.1 sensible-pager.1 select-editor.1; do \
            trans="${man%%.[0-9]}.man"; \
    if [ -f ./$lang/$trans ]; then \
      files="$files ./$lang/$man"; \
    elif [ -f ./$lang/$trans ]; then \
      files="$files ./$lang/$man"; \
    fi; \
  done; \
  make mandir="/usr/share/man/$lang" man_MANS="" man-once $files; \
done
make[3]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Nothing to be done for 'man-once'.
sed -f ./utf8toman.sed -e 's/%PACKAGE%/sensible-utils/g' -e 's/%VERSION%/0.0.11/g' -e 's/%RELEASE_DATE%//g' -e 's:%CONFDIR%:/etc:g' -e 's:%LOGDIR%::g' -e 's:%ADMINDIR%::g' -e 's:%PKGDOCDIR%:/usr/share/doc/sensible-utils:g' -e 's:%PKGCONFDIR%::g' -e 's:%PKGLIBDIR%:/usr/lib/i386-linux-gnu/sensible-utils:g' -e 's:%PKGDATADIR%:/usr/share/sensible-utils:g' cs/sensible-editor.man >cs/sensible-editor.1
make[3]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Nothing to be done for 'man-once'.
sed -f ./utf8toman.sed -e 's/%PACKAGE%/sensible-utils/g' -e 's/%VERSION%/0.0.11/g' -e 's/%RELEASE_DATE%//g' -e 's:%CONFDIR%:/etc:g' -e 's:%LOGDIR%::g' -e 's:%ADMINDIR%::g' -e 's:%PKGDOCDIR%:/usr/share/doc/sensible-utils:g' -e 's:%PKGCONFDIR%::g' -e 's:%PKGLIBDIR%:/usr/lib/i386-linux-gnu/sensible-utils:g' -e 's:%PKGDATADIR%:/usr/share/sensible-utils:g' de/sensible-editor.man >de/sensible-editor.1
make[3]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Nothing to be done for 'man-once'.
sed -f ./utf8toman.sed -e 's/%PACKAGE%/sensible-utils/g' -e 's/%VERSION%/0.0.11/g' -e 's/%RELEASE_DATE%//g' -e 's:%CONFDIR%:/etc:g' -e 's:%LOGDIR%::g' -e 's:%ADMINDIR%::g' -e 's:%PKGDOCDIR%:/usr/share/doc/sensible-utils:g' -e 's:%PKGCONFDIR%::g' -e 's:%PKGLIBDIR%:/usr/lib/i386-linux-gnu/sensible-utils:g' -e 's:%PKGDATADIR%:/usr/share/sensible-utils:g' es/sensible-editor.man >es/sensible-editor.1
make[3]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Nothing to be done for 'man-once'.
sed -f ./utf8toman.sed -e 's/%PACKAGE%/sensible-utils/g' -e 's/%VERSION%/0.0.11/g' -e 's/%RELEASE_DATE%//g' -e 's:%CONFDIR%:/etc:g' -e 's:%LOGDIR%::g' -e 's:%ADMINDIR%::g' -e 's:%PKGDOCDIR%:/usr/share/doc/sensible-utils:g' -e 's:%PKGCONFDIR%::g' -e 's:%PKGLIBDIR%:/usr/lib/i386-linux-gnu/sensible-utils:g' -e 's:%PKGDATADIR%:/usr/share/sensible-utils:g' fr/sensible-editor.man >fr/sensible-editor.1
make[3]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Nothing to be done for 'man-once'.
sed -f ./utf8toman.sed -e 's/%PACKAGE%/sensible-utils/g' -e 's/%VERSION%/0.0.11/g' -e 's/%RELEASE_DATE%//g' -e 's:%CONFDIR%:/etc:g' -e 's:%LOGDIR%::g' -e 's:%ADMINDIR%::g' -e 's:%PKGDOCDIR%:/usr/share/doc/sensible-utils:g' -e 's:%PKGCONFDIR%::g' -e 's:%PKGLIBDIR%:/usr/lib/i386-linux-gnu/sensible-utils:g' -e 's:%PKGDATADIR%:/usr/share/sensible-utils:g' it/sensible-editor.man >it/sensible-editor.1
make[3]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Nothing to be done for 'man-once'.
sed -f ./utf8toman.sed -e 's/%PACKAGE%/sensible-utils/g' -e 's/%VERSION%/0.0.11/g' -e 's/%RELEASE_DATE%//g' -e 's:%CONFDIR%:/etc:g' -e 's:%LOGDIR%::g' -e 's:%ADMINDIR%::g' -e 's:%PKGDOCDIR%:/usr/share/doc/sensible-utils:g' -e 's:%PKGCONFDIR%::g' -e 's:%PKGLIBDIR%:/usr/lib/i386-linux-gnu/sensible-utils:g' -e 's:%PKGDATADIR%:/usr/share/sensible-utils:g' ja/sensible-editor.man >ja/sensible-editor.1
make[3]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Nothing to be done for 'man-once'.
sed -f ./utf8toman.sed -e 's/%PACKAGE%/sensible-utils/g' -e 's/%VERSION%/0.0.11/g' -e 's/%RELEASE_DATE%//g' -e 's:%CONFDIR%:/etc:g' -e 's:%LOGDIR%::g' -e 's:%ADMINDIR%::g' -e 's:%PKGDOCDIR%:/usr/share/doc/sensible-utils:g' -e 's:%PKGCONFDIR%::g' -e 's:%PKGLIBDIR%:/usr/lib/i386-linux-gnu/sensible-utils:g' -e 's:%PKGDATADIR%:/usr/share/sensible-utils:g' pl/sensible-editor.man >pl/sensible-editor.1
make[3]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Nothing to be done for 'man-once'.
sed -f ./utf8toman.sed -e 's/%PACKAGE%/sensible-utils/g' -e 's/%VERSION%/0.0.11/g' -e 's/%RELEASE_DATE%//g' -e 's:%CONFDIR%:/etc:g' -e 's:%LOGDIR%::g' -e 's:%ADMINDIR%::g' -e 's:%PKGDOCDIR%:/usr/share/doc/sensible-utils:g' -e 's:%PKGCONFDIR%::g' -e 's:%PKGLIBDIR%:/usr/lib/i386-linux-gnu/sensible-utils:g' -e 's:%PKGDATADIR%:/usr/share/sensible-utils:g' pt/sensible-editor.man >pt/sensible-editor.1
make[3]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[2]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[2]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils'
rm -f select-editor select-editor.tmp
sed -e 's|@binpkgdatadir[@]|/usr/share/sensible-utils/bin|g' -e 's|@prefix[@]|/usr|g' './select-editor.in' >select-editor.tmp
chmod +x select-editor.tmp
chmod a-w select-editor.tmp
mv select-editor.tmp select-editor
make[2]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils'
make[1]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils'
   debian/rules override_dh_auto_test
make[1]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils'
**********************************************************
Skip test suite                                           
**********************************************************
make[1]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils'
   create-stamp debian/debhelper-build-stamp
   dh_testroot
   dh_prep
	rm -f -- debian/sensible-utils.substvars
	rm -fr -- debian/.debhelper/generated/sensible-utils/ debian/sensible-utils/ debian/tmp/
   dh_auto_install
	install -d debian/sensible-utils
	make -j1 install DESTDIR=/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils AM_UPDATE_INFO_DIR=no
make[1]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils'
Making install in man
make[2]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
for lang in `sed -ne 's/^.*\[po4a_langs\] \(.*\)$/\1/p' ./po4a/po4a.cfg`; do \
  files=""; \
  for man in sensible-editor.1 sensible-browser.1 sensible-pager.1 select-editor.1; do \
            trans="${man%%.[0-9]}.man"; \
    if [ -f ./$lang/$trans ]; then \
      files="$files ./$lang/$man"; \
    elif [ -f ./$lang/$trans ]; then \
      files="$files ./$lang/$man"; \
    fi; \
  done; \
  make mandir="/usr/share/man/$lang" man_MANS="" man-once $files; \
done
make[3]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Nothing to be done for 'man-once'.
make[3]: 'cs/sensible-editor.1' is up to date.
make[3]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Nothing to be done for 'man-once'.
make[3]: 'de/sensible-editor.1' is up to date.
make[3]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Nothing to be done for 'man-once'.
make[3]: 'es/sensible-editor.1' is up to date.
make[3]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Nothing to be done for 'man-once'.
make[3]: 'fr/sensible-editor.1' is up to date.
make[3]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Nothing to be done for 'man-once'.
make[3]: 'it/sensible-editor.1' is up to date.
make[3]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Nothing to be done for 'man-once'.
make[3]: 'ja/sensible-editor.1' is up to date.
make[3]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Nothing to be done for 'man-once'.
make[3]: 'pl/sensible-editor.1' is up to date.
make[3]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Nothing to be done for 'man-once'.
make[3]: 'pt/sensible-editor.1' is up to date.
make[3]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[3]: Nothing to be done for 'install-exec-am'.
for lang in `sed -ne 's/^.*\[po4a_langs\] \(.*\)$/\1/p' ./po4a/po4a.cfg`; do \
  files=""; \
  for man in sensible-editor.1 sensible-browser.1 sensible-pager.1 select-editor.1; do \
            trans="${man%%.[0-9]}.man"; \
    if [ -f ./$lang/$trans ]; then \
      files="$files ./$lang/$man"; \
    elif [ -f ./$lang/$trans ]; then \
      files="$files ./$lang/$man"; \
    fi; \
  done; \
  make install-man mandir="/usr/share/man/$lang" man_MANS="$files"; \
done
make[4]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
 /usr/bin/mkdir -p '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/share/man/cs/man1'
 /usr/bin/install -c -m 644 ./cs/sensible-editor.1 '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/share/man/cs/man1'
make[4]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[4]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
 /usr/bin/mkdir -p '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/share/man/de/man1'
 /usr/bin/install -c -m 644 ./de/sensible-editor.1 '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/share/man/de/man1'
make[4]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[4]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
 /usr/bin/mkdir -p '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/share/man/es/man1'
 /usr/bin/install -c -m 644 ./es/sensible-editor.1 '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/share/man/es/man1'
make[4]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[4]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
 /usr/bin/mkdir -p '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/share/man/fr/man1'
 /usr/bin/install -c -m 644 ./fr/sensible-editor.1 '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/share/man/fr/man1'
make[4]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[4]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
 /usr/bin/mkdir -p '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/share/man/it/man1'
 /usr/bin/install -c -m 644 ./it/sensible-editor.1 '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/share/man/it/man1'
make[4]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[4]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
 /usr/bin/mkdir -p '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/share/man/ja/man1'
 /usr/bin/install -c -m 644 ./ja/sensible-editor.1 '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/share/man/ja/man1'
make[4]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[4]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
 /usr/bin/mkdir -p '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/share/man/pl/man1'
 /usr/bin/install -c -m 644 ./pl/sensible-editor.1 '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/share/man/pl/man1'
make[4]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[4]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
 /usr/bin/mkdir -p '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/share/man/pt/man1'
 /usr/bin/install -c -m 644 ./pt/sensible-editor.1 '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/share/man/pt/man1'
make[4]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
 /usr/bin/mkdir -p '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/share/man/man1'
 /usr/bin/install -c -m 644 sensible-editor.1 sensible-browser.1 sensible-pager.1 select-editor.1 '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/share/man/man1'
make[3]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[2]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils/man'
make[2]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils'
make[3]: Entering directory '/mnt/sensible-utils.noarch/build/sensible-utils'
 /usr/bin/mkdir -p '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/bin'
 /usr/bin/install -c sensible-browser sensible-editor sensible-pager select-editor '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/bin'
 /usr/bin/mkdir -p '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/share/sensible-utils/bin'
 /usr/bin/install -c tools/gettext '/mnt/sensible-utils.noarch/build/sensible-utils/debian/sensible-utils/usr/share/sensible-utils/bin'
make[3]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils'
make[2]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils'
make[1]: Leaving directory '/mnt/sensible-utils.noarch/build/sensible-utils'
   dh_installdocs
	install -d debian/sensible-utils/usr/share/doc/sensible-utils
	install -d debian/.debhelper/generated/sensible-utils
	install -p -m0644 debian/copyright debian/sensible-utils/usr/share/doc/sensible-utils/copyright
   dh_installchangelogs
	install -p -m0644 debian/changelog debian/sensible-utils/usr/share/doc/sensible-utils/changelog
   dh_installman
man: unrecognized option '--version'
Try 'man --help' or 'man --usage' for more information.
	man -l --recode UTF-8 ./debian/sensible-utils/usr/share/man/es/man1/sensible-editor.1 > debian/sensible-utils/usr/share/man/es/man1/sensible-editor.1.dh-new
	mv debian/sensible-utils/usr/share/man/es/man1/sensible-editor.1.dh-new debian/sensible-utils/usr/share/man/es/man1/sensible-editor.1
	man -l --recode UTF-8 ./debian/sensible-utils/usr/share/man/de/man1/sensible-editor.1 > debian/sensible-utils/usr/share/man/de/man1/sensible-editor.1.dh-new
	mv debian/sensible-utils/usr/share/man/de/man1/sensible-editor.1.dh-new debian/sensible-utils/usr/share/man/de/man1/sensible-editor.1
	man -l --recode UTF-8 ./debian/sensible-utils/usr/share/man/it/man1/sensible-editor.1 > debian/sensible-utils/usr/share/man/it/man1/sensible-editor.1.dh-new
	mv debian/sensible-utils/usr/share/man/it/man1/sensible-editor.1.dh-new debian/sensible-utils/usr/share/man/it/man1/sensible-editor.1
	man -l --recode UTF-8 ./debian/sensible-utils/usr/share/man/man1/sensible-editor.1 > debian/sensible-utils/usr/share/man/man1/sensible-editor.1.dh-new
	mv debian/sensible-utils/usr/share/man/man1/sensible-editor.1.dh-new debian/sensible-utils/usr/share/man/man1/sensible-editor.1
	man -l --recode UTF-8 ./debian/sensible-utils/usr/share/man/man1/sensible-pager.1 > debian/sensible-utils/usr/share/man/man1/sensible-pager.1.dh-new
	mv debian/sensible-utils/usr/share/man/man1/sensible-pager.1.dh-new debian/sensible-utils/usr/share/man/man1/sensible-pager.1
	man -l --recode UTF-8 ./debian/sensible-utils/usr/share/man/man1/select-editor.1 > debian/sensible-utils/usr/share/man/man1/select-editor.1.dh-new
	mv debian/sensible-utils/usr/share/man/man1/select-editor.1.dh-new debian/sensible-utils/usr/share/man/man1/select-editor.1
	man -l --recode UTF-8 ./debian/sensible-utils/usr/share/man/man1/sensible-browser.1 > debian/sensible-utils/usr/share/man/man1/sensible-browser.1.dh-new
	mv debian/sensible-utils/usr/share/man/man1/sensible-browser.1.dh-new debian/sensible-utils/usr/share/man/man1/sensible-browser.1
	man -l --recode UTF-8 ./debian/sensible-utils/usr/share/man/pl/man1/sensible-editor.1 > debian/sensible-utils/usr/share/man/pl/man1/sensible-editor.1.dh-new
	mv debian/sensible-utils/usr/share/man/pl/man1/sensible-editor.1.dh-new debian/sensible-utils/usr/share/man/pl/man1/sensible-editor.1
	man -l --recode UTF-8 ./debian/sensible-utils/usr/share/man/ja/man1/sensible-editor.1 > debian/sensible-utils/usr/share/man/ja/man1/sensible-editor.1.dh-new
	mv debian/sensible-utils/usr/share/man/ja/man1/sensible-editor.1.dh-new debian/sensible-utils/usr/share/man/ja/man1/sensible-editor.1
	man -l --recode UTF-8 ./debian/sensible-utils/usr/share/man/cs/man1/sensible-editor.1 > debian/sensible-utils/usr/share/man/cs/man1/sensible-editor.1.dh-new
	mv debian/sensible-utils/usr/share/man/cs/man1/sensible-editor.1.dh-new debian/sensible-utils/usr/share/man/cs/man1/sensible-editor.1
	man -l --recode UTF-8 ./debian/sensible-utils/usr/share/man/pt/man1/sensible-editor.1 > debian/sensible-utils/usr/share/man/pt/man1/sensible-editor.1.dh-new
	mv debian/sensible-utils/usr/share/man/pt/man1/sensible-editor.1.dh-new debian/sensible-utils/usr/share/man/pt/man1/sensible-editor.1
	man -l --recode UTF-8 ./debian/sensible-utils/usr/share/man/fr/man1/sensible-editor.1 > debian/sensible-utils/usr/share/man/fr/man1/sensible-editor.1.dh-new
	mv debian/sensible-utils/usr/share/man/fr/man1/sensible-editor.1.dh-new debian/sensible-utils/usr/share/man/fr/man1/sensible-editor.1
	chmod 0644 -- debian/sensible-utils/usr/share/man/es/man1/sensible-editor.1 debian/sensible-utils/usr/share/man/de/man1/sensible-editor.1 debian/sensible-utils/usr/share/man/it/man1/sensible-editor.1 debian/sensible-utils/usr/share/man/man1/sensible-editor.1 debian/sensible-utils/usr/share/man/man1/sensible-pager.1 debian/sensible-utils/usr/share/man/man1/select-editor.1 debian/sensible-utils/usr/share/man/man1/sensible-browser.1 debian/sensible-utils/usr/share/man/pl/man1/sensible-editor.1 debian/sensible-utils/usr/share/man/ja/man1/sensible-editor.1 debian/sensible-utils/usr/share/man/cs/man1/sensible-editor.1 debian/sensible-utils/usr/share/man/pt/man1/sensible-editor.1 debian/sensible-utils/usr/share/man/fr/man1/sensible-editor.1
   dh_installmime
	install -d debian/sensible-utils/usr/lib/mime/packages
	install -p -m0644 debian/mime debian/sensible-utils/usr/lib/mime/packages/sensible-utils
   dh_perl
   dh_link
   dh_strip_nondeterminism
   dh_compress
	cd debian/sensible-utils
	chmod a-x usr/share/doc/sensible-utils/changelog usr/share/man/cs/man1/sensible-editor.1 usr/share/man/de/man1/sensible-editor.1 usr/share/man/es/man1/sensible-editor.1 usr/share/man/fr/man1/sensible-editor.1 usr/share/man/it/man1/sensible-editor.1 usr/share/man/ja/man1/sensible-editor.1 usr/share/man/man1/select-editor.1 usr/share/man/man1/sensible-browser.1 usr/share/man/man1/sensible-editor.1 usr/share/man/man1/sensible-pager.1 usr/share/man/pl/man1/sensible-editor.1 usr/share/man/pt/man1/sensible-editor.1
	gzip -9nf usr/share/doc/sensible-utils/changelog usr/share/man/cs/man1/sensible-editor.1 usr/share/man/de/man1/sensible-editor.1 usr/share/man/es/man1/sensible-editor.1 usr/share/man/fr/man1/sensible-editor.1 usr/share/man/it/man1/sensible-editor.1 usr/share/man/ja/man1/sensible-editor.1 usr/share/man/man1/select-editor.1 usr/share/man/man1/sensible-browser.1 usr/share/man/man1/sensible-editor.1 usr/share/man/man1/sensible-pager.1 usr/share/man/pl/man1/sensible-editor.1 usr/share/man/pt/man1/sensible-editor.1
	cd '/mnt/sensible-utils.noarch/build/sensible-utils'
   dh_fixperms
	find debian/sensible-utils ! -type l -a -true -a -true -print0 2>/dev/null | xargs -0r chmod go=rX,u+rw,a-s
	find debian/sensible-utils/usr/share/doc -type f -a -true -a ! -regex 'debian/sensible-utils/usr/share/doc/[^/]*/examples/.*' -print0 2>/dev/null | xargs -0r chmod 0644
	find debian/sensible-utils/usr/share/doc -type d -a -true -a -true -print0 2>/dev/null | xargs -0r chmod 0755
	find debian/sensible-utils/usr/share/man -type f -a -true -a -true -print0 2>/dev/null | xargs -0r chmod 0644
	find debian/sensible-utils -type f \( -name '*.so.*' -o -name '*.so' -o -name '*.la' -o -name '*.a' -o -name '*.js' -o -name '*.css' -o -name '*.scss' -o -name '*.sass' -o -name '*.jpeg' -o -name '*.jpg' -o -name '*.png' -o -name '*.gif' -o -name '*.cmxs' -o -name '*.node' \) -a -true -a -true -print0 2>/dev/null | xargs -0r chmod 0644
	find debian/sensible-utils/usr/bin -type f -a -true -a -true -print0 2>/dev/null | xargs -0r chmod a+x
	find debian/sensible-utils/usr/lib -type f -name '*.ali' -a -true -a -true -print0 2>/dev/null | xargs -0r chmod uga-w
   dh_missing
   dh_installdeb
	install -d debian/sensible-utils/DEBIAN
   dh_gencontrol
	echo misc:Depends= >> debian/sensible-utils.substvars
	echo misc:Pre-Depends= >> debian/sensible-utils.substvars
	dpkg-gencontrol -psensible-utils -ldebian/changelog -Tdebian/sensible-utils.substvars -Pdebian/sensible-utils
dpkg-gencontrol: warning: File::FcntlLock not available; using flock which is not NFS-safe
	chmod 0644 -- debian/sensible-utils/DEBIAN/control
   dh_md5sums
	cd debian/sensible-utils >/dev/null && xargs -r0 md5sum | perl -pe 'if (s@^\\@@) { s/\\\\/\\/g; }' > DEBIAN/md5sums
	chmod 0644 -- debian/sensible-utils/DEBIAN/md5sums
   dh_builddeb
	dpkg-deb --root-owner-group --build debian/sensible-utils ..
dpkg-deb: building package 'sensible-utils' in '../sensible-utils_0.0.12_all.deb'.
 dpkg-genbuildinfo
dpkg-genbuildinfo: warning: cannot open /var/lib/dpkg/status
readline() on closed filehandle $status_fh at /usr/bin/dpkg-genbuildinfo line 96.
dpkg-genbuildinfo: warning: File::FcntlLock not available; using flock which is not NFS-safe
 dpkg-genchanges  >../sensible-utils_0.0.12_i386.changes
dpkg-genchanges: info: including full source code in upload
 dpkg-source --auto-commit --after-build .
dpkg-source: warning: --auto-commit is not a valid option for Dpkg::Source::Package::V3::Native
dpkg-buildpackage: info: full upload; Debian-native package (full source is included)
[1;39m>>> Installing sensible-utils.noarch[0;0m
Fixing symlinks:
Compressing man pages:
Stripping executables:
Preparing debuginfo source files:

[1;39m>>> Packaging sensible-utils.noarch[0;0m
>>> Creating binary package(s)
>>> sensible-utils-sensible-utils-utils.tar.xz
usr/
usr/lib/
usr/lib/mime/
usr/lib/mime/packages/
usr/lib/mime/packages/sensible-utils
usr/share/
usr/share/doc/
usr/share/doc/sensible-utils/
usr/share/doc/sensible-utils/changelog.gz
usr/share/doc/sensible-utils/copyright
usr/share/man/
usr/share/man/es/
usr/share/man/es/man1/
usr/share/man/es/man1/sensible-editor.1.gz
usr/share/man/de/
usr/share/man/de/man1/
usr/share/man/de/man1/sensible-editor.1.gz
usr/share/man/it/
usr/share/man/it/man1/
usr/share/man/it/man1/sensible-editor.1.gz
usr/share/man/man1/
usr/share/man/man1/sensible-editor.1.gz
usr/share/man/man1/sensible-pager.1.gz
usr/share/man/man1/sensible-browser.1.gz
usr/share/man/man1/select-editor.1.gz
usr/share/man/pl/
usr/share/man/pl/man1/
usr/share/man/pl/man1/sensible-editor.1.gz
usr/share/man/ja/
usr/share/man/ja/man1/
usr/share/man/ja/man1/sensible-editor.1.gz
usr/share/man/cs/
usr/share/man/cs/man1/
usr/share/man/cs/man1/sensible-editor.1.gz
usr/share/man/pt/
usr/share/man/pt/man1/
usr/share/man/pt/man1/sensible-editor.1.gz
usr/share/man/fr/
usr/share/man/fr/man1/
usr/share/man/fr/man1/sensible-editor.1.gz
usr/share/sensible-utils/
usr/share/sensible-utils/bin/
usr/share/sensible-utils/bin/gettext
usr/bin/
usr/bin/sensible-browser
usr/bin/sensible-pager
usr/bin/sensible-editor
usr/bin/select-editor

[1;32m*** Info:[0;0m No debug files, skipping debuginfo subpackage

>>> Checking packages for missing or duplicate files

>>> Creating source patches
 0 files changed
>>> Creating source package
sensible-utils.src/
sensible-utils.src/sensible-utils.cygport
sensible-utils.src/sensible-utils_0.0.12.dsc
sensible-utils.src/sensible-utils_0.0.12.tar.xz

>>> sensible-utils requires: bash 
]0;/mnt
[32mAdministrator@- [33m/mnt[0m
$ exit

Script done on Tue Apr 14 20:58:54 2020
