Script started on Thu Apr  9 05:00:24 2020
cygport --32 strip-nondeterminism all
]0;/mnt
[32mAdministrator@- [33m/mnt[0m
$ cygport --32 strip-nondeterminism all
[1;39m>>> Preparing strip-nondeterminism.noarch[0;0m
>>> Unpacking source strip-nondeterminism_1.1.2-1.dsc
>>> Unpacking source strip-nondeterminism_1.1.2.orig.tar.bz2
>>> Unpacking source strip-nondeterminism_1.1.2-1.debian.tar.xz
[1mdpkg-source: [0m[1;33mwarning[0m: extracting unsigned source package (/mnt/strip-nondeterminism_1.1.2-1.dsc)
[1mdpkg-source: [0m[32minfo[0m: extracting strip-nondeterminism in strip-nondeterminism
[1mdpkg-source: [0m[32minfo[0m: unpacking strip-nondeterminism_1.1.2.orig.tar.bz2
[1mdpkg-source: [0m[32minfo[0m: unpacking strip-nondeterminism_1.1.2-1.debian.tar.xz
>>> Preparing working source directory
[1;33m*** Warning:[0;0m Some build dependencies are not installed.
[1;33m*** Warning:[0;0m This package may end up missing features, or not build at all.
[1;33m*** Warning:[0;0m Consider installing these packages first before continuing:
[1;33m*** Warning:[0;0m     libarchive-cpio-perl libarchive-zip-perl libdevel-cover-perl 
[1;39m>>> Compiling strip-nondeterminism.noarch[0;0m
dpkg-buildpackage: info: source package strip-nondeterminism
dpkg-buildpackage: info: source version 1.1.2-1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: source changed by Chris Lamb <lamby@debian.org>
dpkg-architecture: warning: default GNU system type i686-linux-gnu for Debian arch i386 does not match specified GNU system type i686-pc-cygwin
 dpkg-source --auto-commit --before-build .
dpkg-buildpackage: info: host architecture i386
dpkg-source: info: using options from strip-nondeterminism/debian/source/options: --single-debian-patch
 debian/rules clean
dh clean
   debian/rules override_dh_auto_clean
make[1]: Entering directory '/mnt/strip-nondeterminism.noarch/build/strip-nondeterminism'
rm -rf Makefile MYMETA.* cover_db/ blib/
dh_auto_clean
make[1]: Leaving directory '/mnt/strip-nondeterminism.noarch/build/strip-nondeterminism'
   dh_clean
 dpkg-source --auto-commit -b .
dpkg-source: info: using options from strip-nondeterminism/debian/source/options: --single-debian-patch
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building strip-nondeterminism using existing ./strip-nondeterminism_1.1.2.orig.tar.bz2
dpkg-source: info: building strip-nondeterminism in strip-nondeterminism_1.1.2-1.debian.tar.xz
dpkg-source: info: building strip-nondeterminism in strip-nondeterminism_1.1.2-1.dsc
 debian/rules binary
dh binary
   dh_update_autotools_config
   dh_autoreconf
   dh_auto_configure
	perl Makefile.PL INSTALLDIRS=vendor "OPTIMIZE=-ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/strip-nondeterminism.noarch/build=/usr/src/debug/strip-nondeterminism -fdebug-prefix-map=/mnt/strip-nondeterminism.noarch/src=/usr/src/debug/strip-nondeterminism "
Checking if your kit is complete...
Warning: the following files are missing in your kit:
	lib/File/StripNondeterminism/handlers/ar.pm
Please inform the author.
Generating a Unix-style Makefile
Writing Makefile for File::StripNondeterminism
Writing MYMETA.yml and MYMETA.json
   dh_auto_build
	make -j1
make[1]: Entering directory '/mnt/strip-nondeterminism.noarch/build/strip-nondeterminism'
cp lib/File/StripNondeterminism/handlers/zip.pm blib/lib/File/StripNondeterminism/handlers/zip.pm
cp lib/File/StripNondeterminism/handlers/jar.pm blib/lib/File/StripNondeterminism/handlers/jar.pm
cp lib/File/StripNondeterminism/Common.pm blib/lib/File/StripNondeterminism/Common.pm
cp lib/File/StripNondeterminism/handlers/javadoc.pm blib/lib/File/StripNondeterminism/handlers/javadoc.pm
cp lib/File/StripNondeterminism/handlers/gzip.pm blib/lib/File/StripNondeterminism/handlers/gzip.pm
cp lib/File/StripNondeterminism/handlers/gettext.pm blib/lib/File/StripNondeterminism/handlers/gettext.pm
cp lib/File/StripNondeterminism/handlers/bflt.pm blib/lib/File/StripNondeterminism/handlers/bflt.pm
cp lib/File/StripNondeterminism/handlers/uimage.pm blib/lib/File/StripNondeterminism/handlers/uimage.pm
cp lib/File/StripNondeterminism.pm blib/lib/File/StripNondeterminism.pm
cp lib/File/StripNondeterminism/handlers/png.pm blib/lib/File/StripNondeterminism/handlers/png.pm
cp lib/File/StripNondeterminism/handlers/cpio.pm blib/lib/File/StripNondeterminism/handlers/cpio.pm
cp bin/dh_strip_nondeterminism blib/script/dh_strip_nondeterminism
"/usr/bin/perl.exe" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/dh_strip_nondeterminism
cp bin/strip-nondeterminism blib/script/strip-nondeterminism
"/usr/bin/perl.exe" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/strip-nondeterminism
Manifying 2 pod documents
make[1]: Leaving directory '/mnt/strip-nondeterminism.noarch/build/strip-nondeterminism'
   create-stamp debian/debhelper-build-stamp
   dh_testroot
   dh_prep
   dh_auto_install
	make -j1 install DESTDIR=/mnt/strip-nondeterminism.noarch/build/strip-nondeterminism/debian/tmp AM_UPDATE_INFO_DIR=no PREFIX=/usr
make[1]: Entering directory '/mnt/strip-nondeterminism.noarch/build/strip-nondeterminism'
cp bin/dh_strip_nondeterminism blib/script/dh_strip_nondeterminism
"/usr/bin/perl.exe" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/dh_strip_nondeterminism
cp bin/strip-nondeterminism blib/script/strip-nondeterminism
"/usr/bin/perl.exe" -MExtUtils::MY -e 'MY->fixin(shift)' -- blib/script/strip-nondeterminism
Manifying 2 pod documents
Installing /mnt/strip-nondeterminism.noarch/build/strip-nondeterminism/debian/tmp/usr/share/perl5/File/StripNondeterminism.pm
Installing /mnt/strip-nondeterminism.noarch/build/strip-nondeterminism/debian/tmp/usr/share/perl5/File/StripNondeterminism/Common.pm
Installing /mnt/strip-nondeterminism.noarch/build/strip-nondeterminism/debian/tmp/usr/share/perl5/File/StripNondeterminism/handlers/uimage.pm
Installing /mnt/strip-nondeterminism.noarch/build/strip-nondeterminism/debian/tmp/usr/share/perl5/File/StripNondeterminism/handlers/png.pm
Installing /mnt/strip-nondeterminism.noarch/build/strip-nondeterminism/debian/tmp/usr/share/perl5/File/StripNondeterminism/handlers/zip.pm
Installing /mnt/strip-nondeterminism.noarch/build/strip-nondeterminism/debian/tmp/usr/share/perl5/File/StripNondeterminism/handlers/jar.pm
Installing /mnt/strip-nondeterminism.noarch/build/strip-nondeterminism/debian/tmp/usr/share/perl5/File/StripNondeterminism/handlers/cpio.pm
Installing /mnt/strip-nondeterminism.noarch/build/strip-nondeterminism/debian/tmp/usr/share/perl5/File/StripNondeterminism/handlers/gettext.pm
Installing /mnt/strip-nondeterminism.noarch/build/strip-nondeterminism/debian/tmp/usr/share/perl5/File/StripNondeterminism/handlers/javadoc.pm
Installing /mnt/strip-nondeterminism.noarch/build/strip-nondeterminism/debian/tmp/usr/share/perl5/File/StripNondeterminism/handlers/gzip.pm
Installing /mnt/strip-nondeterminism.noarch/build/strip-nondeterminism/debian/tmp/usr/share/perl5/File/StripNondeterminism/handlers/bflt.pm
Installing /mnt/strip-nondeterminism.noarch/build/strip-nondeterminism/debian/tmp/usr/share/man/man1/strip-nondeterminism.1
Installing /mnt/strip-nondeterminism.noarch/build/strip-nondeterminism/debian/tmp/usr/share/man/man1/dh_strip_nondeterminism.1
Installing /mnt/strip-nondeterminism.noarch/build/strip-nondeterminism/debian/tmp/usr/bin/dh_strip_nondeterminism
Installing /mnt/strip-nondeterminism.noarch/build/strip-nondeterminism/debian/tmp/usr/bin/strip-nondeterminism
Appending installation info to /mnt/strip-nondeterminism.noarch/build/strip-nondeterminism/debian/tmp/usr/lib/perl5/5.22/i686-cygwin-threads-64int/perllocal.pod
make[1]: Leaving directory '/mnt/strip-nondeterminism.noarch/build/strip-nondeterminism'
   dh_install
   dh_installdocs
   dh_installchangelogs
   dh_installman
man: unrecognized option '--version'
Try 'man --help' or 'man --usage' for more information.
   dh_perl
   dh_link
   dh_strip_nondeterminism
   dh_compress
   dh_fixperms
   dh_missing
   dh_installdeb
   dh_gencontrol
dpkg-gencontrol: warning: Depends field of package libfile-stripnondeterminism-perl: substitution variable ${perl:Depends} used, but is not defined
dpkg-gencontrol: warning: File::FcntlLock not available; using flock which is not NFS-safe
dpkg-gencontrol: warning: File::FcntlLock not available; using flock which is not NFS-safe
dpkg-gencontrol: warning: File::FcntlLock not available; using flock which is not NFS-safe
   dh_md5sums
   dh_builddeb
dpkg-deb: building package 'libfile-stripnondeterminism-perl' in '../libfile-stripnondeterminism-perl_1.1.2-1_all.deb'.
dpkg-deb: building package 'strip-nondeterminism' in '../strip-nondeterminism_1.1.2-1_all.deb'.
dpkg-deb: building package 'dh-strip-nondeterminism' in '../dh-strip-nondeterminism_1.1.2-1_all.deb'.
 dpkg-genbuildinfo
dpkg-genbuildinfo: warning: cannot open /var/lib/dpkg/status
readline() on closed filehandle $status_fh at /usr/bin/dpkg-genbuildinfo line 96.
dpkg-genbuildinfo: warning: File::FcntlLock not available; using flock which is not NFS-safe
Use of uninitialized value $value in pattern match (m//) at /usr/share/perl5/Dpkg/Control/HashCore.pm line 358.
 dpkg-genchanges  >../strip-nondeterminism_1.1.2-1_i386.changes
dpkg-genchanges: info: including full source code in upload
 dpkg-source --auto-commit --after-build .
dpkg-source: info: using options from strip-nondeterminism/debian/source/options: --single-debian-patch
dpkg-buildpackage: info: full upload (original source is included)
[1;39m>>> Installing strip-nondeterminism.noarch[0;0m
Fixing symlinks:
Compressing man pages:
Stripping executables:
Preparing debuginfo source files:

[1;39m>>> Packaging strip-nondeterminism.noarch[0;0m
>>> Creating binary package(s)
>>> strip-nondeterminism-strip-nondeterminism-nondeterminism.tar.xz
usr/
usr/share/
usr/share/doc/
usr/share/doc/libfile-stripnondeterminism-perl/
usr/share/doc/libfile-stripnondeterminism-perl/copyright
usr/share/doc/libfile-stripnondeterminism-perl/changelog.Debian.gz
usr/share/doc/dh-strip-nondeterminism/
usr/share/doc/dh-strip-nondeterminism/copyright
usr/share/doc/dh-strip-nondeterminism/changelog.Debian.gz
usr/share/doc/strip-nondeterminism/
usr/share/doc/strip-nondeterminism/copyright
usr/share/doc/strip-nondeterminism/changelog.Debian.gz
usr/share/man/
usr/share/man/man1/
usr/share/man/man1/strip-nondeterminism.1.gz
usr/share/man/man1/dh_strip_nondeterminism.1.gz
usr/share/perl5/
usr/share/perl5/File/
usr/share/perl5/File/StripNondeterminism.pm
usr/share/perl5/File/StripNondeterminism/
usr/share/perl5/File/StripNondeterminism/Common.pm
usr/share/perl5/File/StripNondeterminism/handlers/
usr/share/perl5/File/StripNondeterminism/handlers/uimage.pm
usr/share/perl5/File/StripNondeterminism/handlers/png.pm
usr/share/perl5/File/StripNondeterminism/handlers/zip.pm
usr/share/perl5/File/StripNondeterminism/handlers/jar.pm
usr/share/perl5/File/StripNondeterminism/handlers/cpio.pm
usr/share/perl5/File/StripNondeterminism/handlers/gettext.pm
usr/share/perl5/File/StripNondeterminism/handlers/javadoc.pm
usr/share/perl5/File/StripNondeterminism/handlers/gzip.pm
usr/share/perl5/File/StripNondeterminism/handlers/bflt.pm
usr/bin/
usr/bin/dh_strip_nondeterminism
usr/bin/strip-nondeterminism

[1;32m*** Info:[0;0m No debug files, skipping debuginfo subpackage

>>> Checking packages for missing or duplicate files

>>> Creating source patches
 0 files changed
>>> Creating source package
strip-nondeterminism.src/
strip-nondeterminism.src/strip-nondeterminism_1.1.2.orig.tar.bz2
strip-nondeterminism.src/strip-nondeterminism_1.1.2-1.debian.tar.xz
strip-nondeterminism.src/strip-nondeterminism.cygport
strip-nondeterminism.src/strip-nondeterminism_1.1.2-1.dsc

>>> strip-nondeterminism requires: perl-Archive-Zip perl-Scalar-List-Utils perl_base libfile-stripnondeterminism-perl perl
]0;/mnt
[32mAdministrator@- [33m/mnt[0m
$ exit

Script done on Thu Apr  9 05:04:12 2020
